/* =================================================================================================
FILE:         sdi_sp_dashboardPulseByod_silver_adobeByodEntryPages_weekly.sql
LAYER:        Silver View
DATASET:      prj-dbi-prd-1.ds_dbi_digitalmedia_automation
VIEW NAME:    vw_sdi_pulseByod_silver_adobeByodEntryPages_weekly

SOURCE:
  prdrzranalytics.lab42.sdi_tbl_adobeFunnel_silver_byodFlowEntryPagesByChannelGroupsPlusAll_weekly

DESTINATION:
  prdrzranalytics.lab42.sdi_tbl_dashboardPulseByod_silver_adobeByodEntryPages_weekly

PURPOSE:
  Silver view for Adobe Analytics BYOD funnel entry page metrics.
  Outputs a WIDE table — one row per week_sun_to_sat.
  Pivots ChannelGroup rows into columns so each channel
  becomes its own set of prefixed metric columns.
  Applies WoW/LY comparisons and max_data_date.

  Entry page metrics track where BYOD visitors entered the site:
    byodUpvVisitors                 — total unique non-bounced BYOD visitors
    byodEntryByodPageVisitors        — entered on BYOD page
    byodEntryHomePageVisitors        — entered on homepage
    byodEntryDevicePageVisitors      — entered on device page
    byodEntryPlansPageVisitors       — entered on plans page
    byodEntryOtherPageVisitors       — entered on other page (NEW: otherpage2 only — true residual)
    byodEntryGetStartedLandingPageVisitors       — entered on Get Started Landing page (NEW)
    byodEntryByodLandingPageVisitors — entered on BYOD landing page (NEW)
    byodEntryOffersSwitchVisitors    — entered on offers/switch page (NEW)

  -- OLD OTHER reference (not a live column):
  -- Old Other = byodEntryGetStartedLandingPageVisitors + byodEntryByodLandingPageVisitors
  --           + byodEntryOffersSwitchVisitors + byodEntryOtherPageVisitors (otherpage2)
  -- Previously sourced from: sdi_raw_adobe_byod_flow_{channel}_byod_entry_otherpage_visitors_weekly_tmo

BUSINESS GRAIN:
  One row per week_sun_to_sat

SOURCE GRAIN:
  One row per WeekSunSat + ChannelGroup
  ChannelGroup values: ALL, PAID SEARCH, ORGANIC SEARCH,
                       DIRECT, SOCIAL, PROGRAMMATIC, OTHER

COLUMN NAMING CONVENTION:
  adobe_{metric}_{channel}
  Channel suffixes: allChannels, paidSearch, organicSearch, direct, social, programmatic, other

BUSINESS LOGIC:
  - No derived/ratio metrics — all metrics are raw visitor counts
  - WoW: self-join on week_sun_to_sat - 7 days (gap-safe)
  - LY:  self-join on custom_week_num - 52 (gap-safe, Sun-to-Sat anchor)
  - wow_pct / yoy_pct as decimals — NULL when prior NULL or 0
  - max_data_date: latest week_sun_to_sat with any non-null metric

CUSTOM WEEK NUMBER:
  custom_week_num = DATEDIFF(WEEK, DATE '2023-01-01', DATE_SUB(week_sun_to_sat, 6))
  LY match: current.custom_week_num - prior.custom_week_num = 52

DOWNSTREAM:
  Gold Wide : vw_sdi_pulseByod_gold_unified_wide
  Gold Long : vw_sdi_pulseByod_gold_unified_long

CHANGES:
  2026-06-XX — Other segregation:
               byodEntryOtherPageVisitors redefined to otherpage2 only (from upstream Bronze)
               Added byodEntryGetStartedLandingPageVisitors, byodEntryByodLandingPageVisitors,
               byodEntryOffersSwitchVisitors across all 7 channels with full WoW/LY/pct treatment
================================================================================================= */

CREATE OR REPLACE PROCEDURE
prdrzranalytics.lab42.sdi_sp_dashboardPulseByod_silver_adobeByodEntryPages_weekly()
LANGUAGE SQL
SQL SECURITY INVOKER
MODIFIES SQL DATA
AS
BEGIN

  CREATE OR REPLACE TABLE
  prdrzranalytics.lab42.sdi_tbl_dashboardPulseByod_silver_adobeByodEntryPages_weekly
  USING DELTA
  AS

WITH base AS (
  SELECT
    WeekSunSat                         AS week_sun_to_sat,
    ChannelGroup,
    ByodUpvVisitors,
    ByodEntryByodPageVisitors,
    ByodEntryHomePageVisitors,
    ByodEntryDevicePageVisitors,
    ByodEntryPlansPageVisitors,
    ByodEntryOtherPageVisitors,
    ByodEntryStorePageVisitors as ByodEntryGetStartedLandingPageVisitors,          -- NEW
    ByodEntryByodLandingPageVisitors,    -- NEW
    ByodEntryOffersSwitchVisitors        -- NEW
  FROM prdrzranalytics.lab42.sdi_tbl_adobeFunnel_silver_byodFlowEntryPagesByChannelGroupsPlusAll_weekly
),

pivoted AS (
  SELECT
    week_sun_to_sat,
    -- ALL CHANNELS
    MAX(CASE WHEN ChannelGroup = 'All Channels' THEN ByodUpvVisitors END) AS adobe_byodUpvVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'All Channels' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'All Channels' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'All Channels' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'All Channels' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'All Channels' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'All Channels' THEN ByodEntryGetStartedLandingPageVisitors END) AS adobe_byodEntryGetStartedLandingPageVisitors_allChannels,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'All Channels' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_allChannels,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'All Channels' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_allChannels,  -- NEW
    -- PAID SEARCH
    MAX(CASE WHEN ChannelGroup = 'Paid Search' THEN ByodUpvVisitors END) AS adobe_byodUpvVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'Paid Search' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'Paid Search' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'Paid Search' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'Paid Search' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'Paid Search' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'Paid Search' THEN ByodEntryGetStartedLandingPageVisitors END) AS adobe_byodEntryGetStartedLandingPageVisitors_paidSearch,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'Paid Search' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_paidSearch,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'Paid Search' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_paidSearch,  -- NEW
    -- ORGANIC SEARCH
    MAX(CASE WHEN ChannelGroup = 'Organic Search' THEN ByodUpvVisitors END) AS adobe_byodUpvVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'Organic Search' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'Organic Search' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'Organic Search' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'Organic Search' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'Organic Search' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'Organic Search' THEN ByodEntryGetStartedLandingPageVisitors END) AS adobe_byodEntryGetStartedLandingPageVisitors_organicSearch,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'Organic Search' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_organicSearch,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'Organic Search' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_organicSearch,  -- NEW
    -- DIRECT
    MAX(CASE WHEN ChannelGroup = 'Direct' THEN ByodUpvVisitors END) AS adobe_byodUpvVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'Direct' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'Direct' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'Direct' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'Direct' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'Direct' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'Direct' THEN ByodEntryGetStartedLandingPageVisitors END) AS adobe_byodEntryGetStartedLandingPageVisitors_direct,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'Direct' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_direct,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'Direct' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_direct,  -- NEW
    -- SOCIAL
    MAX(CASE WHEN ChannelGroup = 'Paid Social' THEN ByodUpvVisitors END) AS adobe_byodUpvVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'Paid Social' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'Paid Social' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'Paid Social' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'Paid Social' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'Paid Social' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'Paid Social' THEN ByodEntryGetStartedLandingPageVisitors END) AS adobe_byodEntryGetStartedLandingPageVisitors_social,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'Paid Social' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_social,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'Paid Social' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_social,  -- NEW
    -- PROGRAMMATIC
    MAX(CASE WHEN ChannelGroup = 'Programmatic' THEN ByodUpvVisitors END) AS adobe_byodUpvVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'Programmatic' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'Programmatic' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'Programmatic' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'Programmatic' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'Programmatic' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'Programmatic' THEN ByodEntryGetStartedLandingPageVisitors END) AS adobe_byodEntryGetStartedLandingPageVisitors_programmatic,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'Programmatic' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_programmatic,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'Programmatic' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_programmatic,  -- NEW
    -- OTHER
    MAX(CASE WHEN ChannelGroup = 'Other' THEN ByodUpvVisitors END) AS adobe_byodUpvVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'Other' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'Other' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'Other' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'Other' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'Other' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'Other' THEN ByodEntryGetStartedLandingPageVisitors END) AS adobe_byodEntryGetStartedLandingPageVisitors_other,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'Other' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_other,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'Other' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_other  -- NEW
  FROM base
  GROUP BY week_sun_to_sat
),

with_week_num AS (
  SELECT
    *,
    DATEDIFF(WEEK, DATE '2023-01-01', DATE_SUB(week_sun_to_sat, 6)) AS custom_week_num
  FROM pivoted
),

with_comparisons AS (
  SELECT
    c.week_sun_to_sat, c.custom_week_num,
    -- ALL CHANNELS
    c.adobe_byodUpvVisitors_allChannels, w.adobe_byodUpvVisitors_allChannels AS adobe_byodUpvVisitors_allChannels_wow, l.adobe_byodUpvVisitors_allChannels AS adobe_byodUpvVisitors_allChannels_ly,
    c.adobe_byodEntryByodPageVisitors_allChannels, w.adobe_byodEntryByodPageVisitors_allChannels AS adobe_byodEntryByodPageVisitors_allChannels_wow, l.adobe_byodEntryByodPageVisitors_allChannels AS adobe_byodEntryByodPageVisitors_allChannels_ly,
    c.adobe_byodEntryHomePageVisitors_allChannels, w.adobe_byodEntryHomePageVisitors_allChannels AS adobe_byodEntryHomePageVisitors_allChannels_wow, l.adobe_byodEntryHomePageVisitors_allChannels AS adobe_byodEntryHomePageVisitors_allChannels_ly,
    c.adobe_byodEntryDevicePageVisitors_allChannels, w.adobe_byodEntryDevicePageVisitors_allChannels AS adobe_byodEntryDevicePageVisitors_allChannels_wow, l.adobe_byodEntryDevicePageVisitors_allChannels AS adobe_byodEntryDevicePageVisitors_allChannels_ly,
    c.adobe_byodEntryPlansPageVisitors_allChannels, w.adobe_byodEntryPlansPageVisitors_allChannels AS adobe_byodEntryPlansPageVisitors_allChannels_wow, l.adobe_byodEntryPlansPageVisitors_allChannels AS adobe_byodEntryPlansPageVisitors_allChannels_ly,
    c.adobe_byodEntryOtherPageVisitors_allChannels, w.adobe_byodEntryOtherPageVisitors_allChannels AS adobe_byodEntryOtherPageVisitors_allChannels_wow, l.adobe_byodEntryOtherPageVisitors_allChannels AS adobe_byodEntryOtherPageVisitors_allChannels_ly,
    c.adobe_byodEntryGetStartedLandingPageVisitors_allChannels, w.adobe_byodEntryGetStartedLandingPageVisitors_allChannels AS adobe_byodEntryGetStartedLandingPageVisitors_allChannels_wow, l.adobe_byodEntryGetStartedLandingPageVisitors_allChannels AS adobe_byodEntryGetStartedLandingPageVisitors_allChannels_ly,
    c.adobe_byodEntryByodLandingPageVisitors_allChannels, w.adobe_byodEntryByodLandingPageVisitors_allChannels AS adobe_byodEntryByodLandingPageVisitors_allChannels_wow, l.adobe_byodEntryByodLandingPageVisitors_allChannels AS adobe_byodEntryByodLandingPageVisitors_allChannels_ly,
    c.adobe_byodEntryOffersSwitchVisitors_allChannels, w.adobe_byodEntryOffersSwitchVisitors_allChannels AS adobe_byodEntryOffersSwitchVisitors_allChannels_wow, l.adobe_byodEntryOffersSwitchVisitors_allChannels AS adobe_byodEntryOffersSwitchVisitors_allChannels_ly,
    -- PAID SEARCH
    c.adobe_byodUpvVisitors_paidSearch, w.adobe_byodUpvVisitors_paidSearch AS adobe_byodUpvVisitors_paidSearch_wow, l.adobe_byodUpvVisitors_paidSearch AS adobe_byodUpvVisitors_paidSearch_ly,
    c.adobe_byodEntryByodPageVisitors_paidSearch, w.adobe_byodEntryByodPageVisitors_paidSearch AS adobe_byodEntryByodPageVisitors_paidSearch_wow, l.adobe_byodEntryByodPageVisitors_paidSearch AS adobe_byodEntryByodPageVisitors_paidSearch_ly,
    c.adobe_byodEntryHomePageVisitors_paidSearch, w.adobe_byodEntryHomePageVisitors_paidSearch AS adobe_byodEntryHomePageVisitors_paidSearch_wow, l.adobe_byodEntryHomePageVisitors_paidSearch AS adobe_byodEntryHomePageVisitors_paidSearch_ly,
    c.adobe_byodEntryDevicePageVisitors_paidSearch, w.adobe_byodEntryDevicePageVisitors_paidSearch AS adobe_byodEntryDevicePageVisitors_paidSearch_wow, l.adobe_byodEntryDevicePageVisitors_paidSearch AS adobe_byodEntryDevicePageVisitors_paidSearch_ly,
    c.adobe_byodEntryPlansPageVisitors_paidSearch, w.adobe_byodEntryPlansPageVisitors_paidSearch AS adobe_byodEntryPlansPageVisitors_paidSearch_wow, l.adobe_byodEntryPlansPageVisitors_paidSearch AS adobe_byodEntryPlansPageVisitors_paidSearch_ly,
    c.adobe_byodEntryOtherPageVisitors_paidSearch, w.adobe_byodEntryOtherPageVisitors_paidSearch AS adobe_byodEntryOtherPageVisitors_paidSearch_wow, l.adobe_byodEntryOtherPageVisitors_paidSearch AS adobe_byodEntryOtherPageVisitors_paidSearch_ly,
    c.adobe_byodEntryGetStartedLandingPageVisitors_paidSearch, w.adobe_byodEntryGetStartedLandingPageVisitors_paidSearch AS adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_wow, l.adobe_byodEntryGetStartedLandingPageVisitors_paidSearch AS adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_ly,
    c.adobe_byodEntryByodLandingPageVisitors_paidSearch, w.adobe_byodEntryByodLandingPageVisitors_paidSearch AS adobe_byodEntryByodLandingPageVisitors_paidSearch_wow, l.adobe_byodEntryByodLandingPageVisitors_paidSearch AS adobe_byodEntryByodLandingPageVisitors_paidSearch_ly,
    c.adobe_byodEntryOffersSwitchVisitors_paidSearch, w.adobe_byodEntryOffersSwitchVisitors_paidSearch AS adobe_byodEntryOffersSwitchVisitors_paidSearch_wow, l.adobe_byodEntryOffersSwitchVisitors_paidSearch AS adobe_byodEntryOffersSwitchVisitors_paidSearch_ly,
    -- ORGANIC SEARCH
    c.adobe_byodUpvVisitors_organicSearch, w.adobe_byodUpvVisitors_organicSearch AS adobe_byodUpvVisitors_organicSearch_wow, l.adobe_byodUpvVisitors_organicSearch AS adobe_byodUpvVisitors_organicSearch_ly,
    c.adobe_byodEntryByodPageVisitors_organicSearch, w.adobe_byodEntryByodPageVisitors_organicSearch AS adobe_byodEntryByodPageVisitors_organicSearch_wow, l.adobe_byodEntryByodPageVisitors_organicSearch AS adobe_byodEntryByodPageVisitors_organicSearch_ly,
    c.adobe_byodEntryHomePageVisitors_organicSearch, w.adobe_byodEntryHomePageVisitors_organicSearch AS adobe_byodEntryHomePageVisitors_organicSearch_wow, l.adobe_byodEntryHomePageVisitors_organicSearch AS adobe_byodEntryHomePageVisitors_organicSearch_ly,
    c.adobe_byodEntryDevicePageVisitors_organicSearch, w.adobe_byodEntryDevicePageVisitors_organicSearch AS adobe_byodEntryDevicePageVisitors_organicSearch_wow, l.adobe_byodEntryDevicePageVisitors_organicSearch AS adobe_byodEntryDevicePageVisitors_organicSearch_ly,
    c.adobe_byodEntryPlansPageVisitors_organicSearch, w.adobe_byodEntryPlansPageVisitors_organicSearch AS adobe_byodEntryPlansPageVisitors_organicSearch_wow, l.adobe_byodEntryPlansPageVisitors_organicSearch AS adobe_byodEntryPlansPageVisitors_organicSearch_ly,
    c.adobe_byodEntryOtherPageVisitors_organicSearch, w.adobe_byodEntryOtherPageVisitors_organicSearch AS adobe_byodEntryOtherPageVisitors_organicSearch_wow, l.adobe_byodEntryOtherPageVisitors_organicSearch AS adobe_byodEntryOtherPageVisitors_organicSearch_ly,
    c.adobe_byodEntryGetStartedLandingPageVisitors_organicSearch, w.adobe_byodEntryGetStartedLandingPageVisitors_organicSearch AS adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_wow, l.adobe_byodEntryGetStartedLandingPageVisitors_organicSearch AS adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_ly,
    c.adobe_byodEntryByodLandingPageVisitors_organicSearch, w.adobe_byodEntryByodLandingPageVisitors_organicSearch AS adobe_byodEntryByodLandingPageVisitors_organicSearch_wow, l.adobe_byodEntryByodLandingPageVisitors_organicSearch AS adobe_byodEntryByodLandingPageVisitors_organicSearch_ly,
    c.adobe_byodEntryOffersSwitchVisitors_organicSearch, w.adobe_byodEntryOffersSwitchVisitors_organicSearch AS adobe_byodEntryOffersSwitchVisitors_organicSearch_wow, l.adobe_byodEntryOffersSwitchVisitors_organicSearch AS adobe_byodEntryOffersSwitchVisitors_organicSearch_ly,
    -- DIRECT
    c.adobe_byodUpvVisitors_direct, w.adobe_byodUpvVisitors_direct AS adobe_byodUpvVisitors_direct_wow, l.adobe_byodUpvVisitors_direct AS adobe_byodUpvVisitors_direct_ly,
    c.adobe_byodEntryByodPageVisitors_direct, w.adobe_byodEntryByodPageVisitors_direct AS adobe_byodEntryByodPageVisitors_direct_wow, l.adobe_byodEntryByodPageVisitors_direct AS adobe_byodEntryByodPageVisitors_direct_ly,
    c.adobe_byodEntryHomePageVisitors_direct, w.adobe_byodEntryHomePageVisitors_direct AS adobe_byodEntryHomePageVisitors_direct_wow, l.adobe_byodEntryHomePageVisitors_direct AS adobe_byodEntryHomePageVisitors_direct_ly,
    c.adobe_byodEntryDevicePageVisitors_direct, w.adobe_byodEntryDevicePageVisitors_direct AS adobe_byodEntryDevicePageVisitors_direct_wow, l.adobe_byodEntryDevicePageVisitors_direct AS adobe_byodEntryDevicePageVisitors_direct_ly,
    c.adobe_byodEntryPlansPageVisitors_direct, w.adobe_byodEntryPlansPageVisitors_direct AS adobe_byodEntryPlansPageVisitors_direct_wow, l.adobe_byodEntryPlansPageVisitors_direct AS adobe_byodEntryPlansPageVisitors_direct_ly,
    c.adobe_byodEntryOtherPageVisitors_direct, w.adobe_byodEntryOtherPageVisitors_direct AS adobe_byodEntryOtherPageVisitors_direct_wow, l.adobe_byodEntryOtherPageVisitors_direct AS adobe_byodEntryOtherPageVisitors_direct_ly,
    c.adobe_byodEntryGetStartedLandingPageVisitors_direct, w.adobe_byodEntryGetStartedLandingPageVisitors_direct AS adobe_byodEntryGetStartedLandingPageVisitors_direct_wow, l.adobe_byodEntryGetStartedLandingPageVisitors_direct AS adobe_byodEntryGetStartedLandingPageVisitors_direct_ly,
    c.adobe_byodEntryByodLandingPageVisitors_direct, w.adobe_byodEntryByodLandingPageVisitors_direct AS adobe_byodEntryByodLandingPageVisitors_direct_wow, l.adobe_byodEntryByodLandingPageVisitors_direct AS adobe_byodEntryByodLandingPageVisitors_direct_ly,
    c.adobe_byodEntryOffersSwitchVisitors_direct, w.adobe_byodEntryOffersSwitchVisitors_direct AS adobe_byodEntryOffersSwitchVisitors_direct_wow, l.adobe_byodEntryOffersSwitchVisitors_direct AS adobe_byodEntryOffersSwitchVisitors_direct_ly,
    -- SOCIAL
    c.adobe_byodUpvVisitors_social, w.adobe_byodUpvVisitors_social AS adobe_byodUpvVisitors_social_wow, l.adobe_byodUpvVisitors_social AS adobe_byodUpvVisitors_social_ly,
    c.adobe_byodEntryByodPageVisitors_social, w.adobe_byodEntryByodPageVisitors_social AS adobe_byodEntryByodPageVisitors_social_wow, l.adobe_byodEntryByodPageVisitors_social AS adobe_byodEntryByodPageVisitors_social_ly,
    c.adobe_byodEntryHomePageVisitors_social, w.adobe_byodEntryHomePageVisitors_social AS adobe_byodEntryHomePageVisitors_social_wow, l.adobe_byodEntryHomePageVisitors_social AS adobe_byodEntryHomePageVisitors_social_ly,
    c.adobe_byodEntryDevicePageVisitors_social, w.adobe_byodEntryDevicePageVisitors_social AS adobe_byodEntryDevicePageVisitors_social_wow, l.adobe_byodEntryDevicePageVisitors_social AS adobe_byodEntryDevicePageVisitors_social_ly,
    c.adobe_byodEntryPlansPageVisitors_social, w.adobe_byodEntryPlansPageVisitors_social AS adobe_byodEntryPlansPageVisitors_social_wow, l.adobe_byodEntryPlansPageVisitors_social AS adobe_byodEntryPlansPageVisitors_social_ly,
    c.adobe_byodEntryOtherPageVisitors_social, w.adobe_byodEntryOtherPageVisitors_social AS adobe_byodEntryOtherPageVisitors_social_wow, l.adobe_byodEntryOtherPageVisitors_social AS adobe_byodEntryOtherPageVisitors_social_ly,
    c.adobe_byodEntryGetStartedLandingPageVisitors_social, w.adobe_byodEntryGetStartedLandingPageVisitors_social AS adobe_byodEntryGetStartedLandingPageVisitors_social_wow, l.adobe_byodEntryGetStartedLandingPageVisitors_social AS adobe_byodEntryGetStartedLandingPageVisitors_social_ly,
    c.adobe_byodEntryByodLandingPageVisitors_social, w.adobe_byodEntryByodLandingPageVisitors_social AS adobe_byodEntryByodLandingPageVisitors_social_wow, l.adobe_byodEntryByodLandingPageVisitors_social AS adobe_byodEntryByodLandingPageVisitors_social_ly,
    c.adobe_byodEntryOffersSwitchVisitors_social, w.adobe_byodEntryOffersSwitchVisitors_social AS adobe_byodEntryOffersSwitchVisitors_social_wow, l.adobe_byodEntryOffersSwitchVisitors_social AS adobe_byodEntryOffersSwitchVisitors_social_ly,
    -- PROGRAMMATIC
    c.adobe_byodUpvVisitors_programmatic, w.adobe_byodUpvVisitors_programmatic AS adobe_byodUpvVisitors_programmatic_wow, l.adobe_byodUpvVisitors_programmatic AS adobe_byodUpvVisitors_programmatic_ly,
    c.adobe_byodEntryByodPageVisitors_programmatic, w.adobe_byodEntryByodPageVisitors_programmatic AS adobe_byodEntryByodPageVisitors_programmatic_wow, l.adobe_byodEntryByodPageVisitors_programmatic AS adobe_byodEntryByodPageVisitors_programmatic_ly,
    c.adobe_byodEntryHomePageVisitors_programmatic, w.adobe_byodEntryHomePageVisitors_programmatic AS adobe_byodEntryHomePageVisitors_programmatic_wow, l.adobe_byodEntryHomePageVisitors_programmatic AS adobe_byodEntryHomePageVisitors_programmatic_ly,
    c.adobe_byodEntryDevicePageVisitors_programmatic, w.adobe_byodEntryDevicePageVisitors_programmatic AS adobe_byodEntryDevicePageVisitors_programmatic_wow, l.adobe_byodEntryDevicePageVisitors_programmatic AS adobe_byodEntryDevicePageVisitors_programmatic_ly,
    c.adobe_byodEntryPlansPageVisitors_programmatic, w.adobe_byodEntryPlansPageVisitors_programmatic AS adobe_byodEntryPlansPageVisitors_programmatic_wow, l.adobe_byodEntryPlansPageVisitors_programmatic AS adobe_byodEntryPlansPageVisitors_programmatic_ly,
    c.adobe_byodEntryOtherPageVisitors_programmatic, w.adobe_byodEntryOtherPageVisitors_programmatic AS adobe_byodEntryOtherPageVisitors_programmatic_wow, l.adobe_byodEntryOtherPageVisitors_programmatic AS adobe_byodEntryOtherPageVisitors_programmatic_ly,
    c.adobe_byodEntryGetStartedLandingPageVisitors_programmatic, w.adobe_byodEntryGetStartedLandingPageVisitors_programmatic AS adobe_byodEntryGetStartedLandingPageVisitors_programmatic_wow, l.adobe_byodEntryGetStartedLandingPageVisitors_programmatic AS adobe_byodEntryGetStartedLandingPageVisitors_programmatic_ly,
    c.adobe_byodEntryByodLandingPageVisitors_programmatic, w.adobe_byodEntryByodLandingPageVisitors_programmatic AS adobe_byodEntryByodLandingPageVisitors_programmatic_wow, l.adobe_byodEntryByodLandingPageVisitors_programmatic AS adobe_byodEntryByodLandingPageVisitors_programmatic_ly,
    c.adobe_byodEntryOffersSwitchVisitors_programmatic, w.adobe_byodEntryOffersSwitchVisitors_programmatic AS adobe_byodEntryOffersSwitchVisitors_programmatic_wow, l.adobe_byodEntryOffersSwitchVisitors_programmatic AS adobe_byodEntryOffersSwitchVisitors_programmatic_ly,
    -- OTHER
    c.adobe_byodUpvVisitors_other, w.adobe_byodUpvVisitors_other AS adobe_byodUpvVisitors_other_wow, l.adobe_byodUpvVisitors_other AS adobe_byodUpvVisitors_other_ly,
    c.adobe_byodEntryByodPageVisitors_other, w.adobe_byodEntryByodPageVisitors_other AS adobe_byodEntryByodPageVisitors_other_wow, l.adobe_byodEntryByodPageVisitors_other AS adobe_byodEntryByodPageVisitors_other_ly,
    c.adobe_byodEntryHomePageVisitors_other, w.adobe_byodEntryHomePageVisitors_other AS adobe_byodEntryHomePageVisitors_other_wow, l.adobe_byodEntryHomePageVisitors_other AS adobe_byodEntryHomePageVisitors_other_ly,
    c.adobe_byodEntryDevicePageVisitors_other, w.adobe_byodEntryDevicePageVisitors_other AS adobe_byodEntryDevicePageVisitors_other_wow, l.adobe_byodEntryDevicePageVisitors_other AS adobe_byodEntryDevicePageVisitors_other_ly,
    c.adobe_byodEntryPlansPageVisitors_other, w.adobe_byodEntryPlansPageVisitors_other AS adobe_byodEntryPlansPageVisitors_other_wow, l.adobe_byodEntryPlansPageVisitors_other AS adobe_byodEntryPlansPageVisitors_other_ly,
    c.adobe_byodEntryOtherPageVisitors_other, w.adobe_byodEntryOtherPageVisitors_other AS adobe_byodEntryOtherPageVisitors_other_wow, l.adobe_byodEntryOtherPageVisitors_other AS adobe_byodEntryOtherPageVisitors_other_ly,
    c.adobe_byodEntryGetStartedLandingPageVisitors_other, w.adobe_byodEntryGetStartedLandingPageVisitors_other AS adobe_byodEntryGetStartedLandingPageVisitors_other_wow, l.adobe_byodEntryGetStartedLandingPageVisitors_other AS adobe_byodEntryGetStartedLandingPageVisitors_other_ly,
    c.adobe_byodEntryByodLandingPageVisitors_other, w.adobe_byodEntryByodLandingPageVisitors_other AS adobe_byodEntryByodLandingPageVisitors_other_wow, l.adobe_byodEntryByodLandingPageVisitors_other AS adobe_byodEntryByodLandingPageVisitors_other_ly,
    c.adobe_byodEntryOffersSwitchVisitors_other, w.adobe_byodEntryOffersSwitchVisitors_other AS adobe_byodEntryOffersSwitchVisitors_other_wow, l.adobe_byodEntryOffersSwitchVisitors_other AS adobe_byodEntryOffersSwitchVisitors_other_ly
  FROM with_week_num c
  LEFT JOIN with_week_num w ON c.week_sun_to_sat = DATE_ADD(w.week_sun_to_sat, 7)
  LEFT JOIN with_week_num l ON (c.custom_week_num - l.custom_week_num) = 52
),

with_pcts AS (
  SELECT
    week_sun_to_sat, custom_week_num,
    -- ALL CHANNELS
    adobe_byodUpvVisitors_allChannels, adobe_byodUpvVisitors_allChannels_wow, adobe_byodUpvVisitors_allChannels_ly, CASE WHEN adobe_byodUpvVisitors_allChannels_wow IS NULL OR adobe_byodUpvVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_allChannels - adobe_byodUpvVisitors_allChannels_wow) / adobe_byodUpvVisitors_allChannels_wow, 6) END AS adobe_byodUpvVisitors_allChannels_wow_pct, CASE WHEN adobe_byodUpvVisitors_allChannels_ly  IS NULL OR adobe_byodUpvVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_allChannels - adobe_byodUpvVisitors_allChannels_ly)  / adobe_byodUpvVisitors_allChannels_ly,  6) END AS adobe_byodUpvVisitors_allChannels_yoy_pct,
    adobe_byodEntryByodPageVisitors_allChannels, adobe_byodEntryByodPageVisitors_allChannels_wow, adobe_byodEntryByodPageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryByodPageVisitors_allChannels_wow IS NULL OR adobe_byodEntryByodPageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_allChannels - adobe_byodEntryByodPageVisitors_allChannels_wow) / adobe_byodEntryByodPageVisitors_allChannels_wow, 6) END AS adobe_byodEntryByodPageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryByodPageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_allChannels - adobe_byodEntryByodPageVisitors_allChannels_ly)  / adobe_byodEntryByodPageVisitors_allChannels_ly,  6) END AS adobe_byodEntryByodPageVisitors_allChannels_yoy_pct,
    adobe_byodEntryHomePageVisitors_allChannels, adobe_byodEntryHomePageVisitors_allChannels_wow, adobe_byodEntryHomePageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryHomePageVisitors_allChannels_wow IS NULL OR adobe_byodEntryHomePageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_allChannels - adobe_byodEntryHomePageVisitors_allChannels_wow) / adobe_byodEntryHomePageVisitors_allChannels_wow, 6) END AS adobe_byodEntryHomePageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryHomePageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_allChannels - adobe_byodEntryHomePageVisitors_allChannels_ly)  / adobe_byodEntryHomePageVisitors_allChannels_ly,  6) END AS adobe_byodEntryHomePageVisitors_allChannels_yoy_pct,
    adobe_byodEntryDevicePageVisitors_allChannels, adobe_byodEntryDevicePageVisitors_allChannels_wow, adobe_byodEntryDevicePageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_allChannels_wow IS NULL OR adobe_byodEntryDevicePageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_allChannels - adobe_byodEntryDevicePageVisitors_allChannels_wow) / adobe_byodEntryDevicePageVisitors_allChannels_wow, 6) END AS adobe_byodEntryDevicePageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_allChannels - adobe_byodEntryDevicePageVisitors_allChannels_ly)  / adobe_byodEntryDevicePageVisitors_allChannels_ly,  6) END AS adobe_byodEntryDevicePageVisitors_allChannels_yoy_pct,
    adobe_byodEntryPlansPageVisitors_allChannels, adobe_byodEntryPlansPageVisitors_allChannels_wow, adobe_byodEntryPlansPageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_allChannels_wow IS NULL OR adobe_byodEntryPlansPageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_allChannels - adobe_byodEntryPlansPageVisitors_allChannels_wow) / adobe_byodEntryPlansPageVisitors_allChannels_wow, 6) END AS adobe_byodEntryPlansPageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_allChannels - adobe_byodEntryPlansPageVisitors_allChannels_ly)  / adobe_byodEntryPlansPageVisitors_allChannels_ly,  6) END AS adobe_byodEntryPlansPageVisitors_allChannels_yoy_pct,
    adobe_byodEntryOtherPageVisitors_allChannels, adobe_byodEntryOtherPageVisitors_allChannels_wow, adobe_byodEntryOtherPageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_allChannels_wow IS NULL OR adobe_byodEntryOtherPageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_allChannels - adobe_byodEntryOtherPageVisitors_allChannels_wow) / adobe_byodEntryOtherPageVisitors_allChannels_wow, 6) END AS adobe_byodEntryOtherPageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_allChannels - adobe_byodEntryOtherPageVisitors_allChannels_ly)  / adobe_byodEntryOtherPageVisitors_allChannels_ly,  6) END AS adobe_byodEntryOtherPageVisitors_allChannels_yoy_pct,
    adobe_byodEntryGetStartedLandingPageVisitors_allChannels, adobe_byodEntryGetStartedLandingPageVisitors_allChannels_wow, adobe_byodEntryGetStartedLandingPageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_allChannels_wow IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_allChannels - adobe_byodEntryGetStartedLandingPageVisitors_allChannels_wow) / adobe_byodEntryGetStartedLandingPageVisitors_allChannels_wow, 6) END AS adobe_byodEntryGetStartedLandingPageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_allChannels - adobe_byodEntryGetStartedLandingPageVisitors_allChannels_ly)  / adobe_byodEntryGetStartedLandingPageVisitors_allChannels_ly,  6) END AS adobe_byodEntryGetStartedLandingPageVisitors_allChannels_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_allChannels, adobe_byodEntryByodLandingPageVisitors_allChannels_wow, adobe_byodEntryByodLandingPageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_allChannels_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_allChannels - adobe_byodEntryByodLandingPageVisitors_allChannels_wow) / adobe_byodEntryByodLandingPageVisitors_allChannels_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_allChannels - adobe_byodEntryByodLandingPageVisitors_allChannels_ly)  / adobe_byodEntryByodLandingPageVisitors_allChannels_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_allChannels_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_allChannels, adobe_byodEntryOffersSwitchVisitors_allChannels_wow, adobe_byodEntryOffersSwitchVisitors_allChannels_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_allChannels_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_allChannels - adobe_byodEntryOffersSwitchVisitors_allChannels_wow) / adobe_byodEntryOffersSwitchVisitors_allChannels_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_allChannels_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_allChannels - adobe_byodEntryOffersSwitchVisitors_allChannels_ly)  / adobe_byodEntryOffersSwitchVisitors_allChannels_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_allChannels_yoy_pct,
    -- PAID SEARCH
    adobe_byodUpvVisitors_paidSearch, adobe_byodUpvVisitors_paidSearch_wow, adobe_byodUpvVisitors_paidSearch_ly, CASE WHEN adobe_byodUpvVisitors_paidSearch_wow IS NULL OR adobe_byodUpvVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_paidSearch - adobe_byodUpvVisitors_paidSearch_wow) / adobe_byodUpvVisitors_paidSearch_wow, 6) END AS adobe_byodUpvVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodUpvVisitors_paidSearch_ly  IS NULL OR adobe_byodUpvVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_paidSearch - adobe_byodUpvVisitors_paidSearch_ly)  / adobe_byodUpvVisitors_paidSearch_ly,  6) END AS adobe_byodUpvVisitors_paidSearch_yoy_pct,
    adobe_byodEntryByodPageVisitors_paidSearch, adobe_byodEntryByodPageVisitors_paidSearch_wow, adobe_byodEntryByodPageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryByodPageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryByodPageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_paidSearch - adobe_byodEntryByodPageVisitors_paidSearch_wow) / adobe_byodEntryByodPageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryByodPageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryByodPageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_paidSearch - adobe_byodEntryByodPageVisitors_paidSearch_ly)  / adobe_byodEntryByodPageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryByodPageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryHomePageVisitors_paidSearch, adobe_byodEntryHomePageVisitors_paidSearch_wow, adobe_byodEntryHomePageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryHomePageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryHomePageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_paidSearch - adobe_byodEntryHomePageVisitors_paidSearch_wow) / adobe_byodEntryHomePageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryHomePageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryHomePageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_paidSearch - adobe_byodEntryHomePageVisitors_paidSearch_ly)  / adobe_byodEntryHomePageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryHomePageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryDevicePageVisitors_paidSearch, adobe_byodEntryDevicePageVisitors_paidSearch_wow, adobe_byodEntryDevicePageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryDevicePageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_paidSearch - adobe_byodEntryDevicePageVisitors_paidSearch_wow) / adobe_byodEntryDevicePageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryDevicePageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_paidSearch - adobe_byodEntryDevicePageVisitors_paidSearch_ly)  / adobe_byodEntryDevicePageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryDevicePageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryPlansPageVisitors_paidSearch, adobe_byodEntryPlansPageVisitors_paidSearch_wow, adobe_byodEntryPlansPageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryPlansPageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_paidSearch - adobe_byodEntryPlansPageVisitors_paidSearch_wow) / adobe_byodEntryPlansPageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryPlansPageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_paidSearch - adobe_byodEntryPlansPageVisitors_paidSearch_ly)  / adobe_byodEntryPlansPageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryPlansPageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryOtherPageVisitors_paidSearch, adobe_byodEntryOtherPageVisitors_paidSearch_wow, adobe_byodEntryOtherPageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryOtherPageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_paidSearch - adobe_byodEntryOtherPageVisitors_paidSearch_wow) / adobe_byodEntryOtherPageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryOtherPageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_paidSearch - adobe_byodEntryOtherPageVisitors_paidSearch_ly)  / adobe_byodEntryOtherPageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryOtherPageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryGetStartedLandingPageVisitors_paidSearch, adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_wow, adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_paidSearch - adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_wow) / adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_paidSearch - adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_ly)  / adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_paidSearch, adobe_byodEntryByodLandingPageVisitors_paidSearch_wow, adobe_byodEntryByodLandingPageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_paidSearch - adobe_byodEntryByodLandingPageVisitors_paidSearch_wow) / adobe_byodEntryByodLandingPageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_paidSearch - adobe_byodEntryByodLandingPageVisitors_paidSearch_ly)  / adobe_byodEntryByodLandingPageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_paidSearch, adobe_byodEntryOffersSwitchVisitors_paidSearch_wow, adobe_byodEntryOffersSwitchVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_paidSearch_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_paidSearch - adobe_byodEntryOffersSwitchVisitors_paidSearch_wow) / adobe_byodEntryOffersSwitchVisitors_paidSearch_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_paidSearch - adobe_byodEntryOffersSwitchVisitors_paidSearch_ly)  / adobe_byodEntryOffersSwitchVisitors_paidSearch_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_paidSearch_yoy_pct,
    -- ORGANIC SEARCH
    adobe_byodUpvVisitors_organicSearch, adobe_byodUpvVisitors_organicSearch_wow, adobe_byodUpvVisitors_organicSearch_ly, CASE WHEN adobe_byodUpvVisitors_organicSearch_wow IS NULL OR adobe_byodUpvVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_organicSearch - adobe_byodUpvVisitors_organicSearch_wow) / adobe_byodUpvVisitors_organicSearch_wow, 6) END AS adobe_byodUpvVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodUpvVisitors_organicSearch_ly  IS NULL OR adobe_byodUpvVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_organicSearch - adobe_byodUpvVisitors_organicSearch_ly)  / adobe_byodUpvVisitors_organicSearch_ly,  6) END AS adobe_byodUpvVisitors_organicSearch_yoy_pct,
    adobe_byodEntryByodPageVisitors_organicSearch, adobe_byodEntryByodPageVisitors_organicSearch_wow, adobe_byodEntryByodPageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryByodPageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryByodPageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_organicSearch - adobe_byodEntryByodPageVisitors_organicSearch_wow) / adobe_byodEntryByodPageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryByodPageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryByodPageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_organicSearch - adobe_byodEntryByodPageVisitors_organicSearch_ly)  / adobe_byodEntryByodPageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryByodPageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryHomePageVisitors_organicSearch, adobe_byodEntryHomePageVisitors_organicSearch_wow, adobe_byodEntryHomePageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryHomePageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryHomePageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_organicSearch - adobe_byodEntryHomePageVisitors_organicSearch_wow) / adobe_byodEntryHomePageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryHomePageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryHomePageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_organicSearch - adobe_byodEntryHomePageVisitors_organicSearch_ly)  / adobe_byodEntryHomePageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryHomePageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryDevicePageVisitors_organicSearch, adobe_byodEntryDevicePageVisitors_organicSearch_wow, adobe_byodEntryDevicePageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryDevicePageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_organicSearch - adobe_byodEntryDevicePageVisitors_organicSearch_wow) / adobe_byodEntryDevicePageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryDevicePageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_organicSearch - adobe_byodEntryDevicePageVisitors_organicSearch_ly)  / adobe_byodEntryDevicePageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryDevicePageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryPlansPageVisitors_organicSearch, adobe_byodEntryPlansPageVisitors_organicSearch_wow, adobe_byodEntryPlansPageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryPlansPageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_organicSearch - adobe_byodEntryPlansPageVisitors_organicSearch_wow) / adobe_byodEntryPlansPageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryPlansPageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_organicSearch - adobe_byodEntryPlansPageVisitors_organicSearch_ly)  / adobe_byodEntryPlansPageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryPlansPageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryOtherPageVisitors_organicSearch, adobe_byodEntryOtherPageVisitors_organicSearch_wow, adobe_byodEntryOtherPageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryOtherPageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_organicSearch - adobe_byodEntryOtherPageVisitors_organicSearch_wow) / adobe_byodEntryOtherPageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryOtherPageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_organicSearch - adobe_byodEntryOtherPageVisitors_organicSearch_ly)  / adobe_byodEntryOtherPageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryOtherPageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryGetStartedLandingPageVisitors_organicSearch, adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_wow, adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_organicSearch - adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_wow) / adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_organicSearch - adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_ly)  / adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_organicSearch, adobe_byodEntryByodLandingPageVisitors_organicSearch_wow, adobe_byodEntryByodLandingPageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_organicSearch - adobe_byodEntryByodLandingPageVisitors_organicSearch_wow) / adobe_byodEntryByodLandingPageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_organicSearch - adobe_byodEntryByodLandingPageVisitors_organicSearch_ly)  / adobe_byodEntryByodLandingPageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_organicSearch, adobe_byodEntryOffersSwitchVisitors_organicSearch_wow, adobe_byodEntryOffersSwitchVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_organicSearch_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_organicSearch - adobe_byodEntryOffersSwitchVisitors_organicSearch_wow) / adobe_byodEntryOffersSwitchVisitors_organicSearch_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_organicSearch - adobe_byodEntryOffersSwitchVisitors_organicSearch_ly)  / adobe_byodEntryOffersSwitchVisitors_organicSearch_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_organicSearch_yoy_pct,
    -- DIRECT
    adobe_byodUpvVisitors_direct, adobe_byodUpvVisitors_direct_wow, adobe_byodUpvVisitors_direct_ly, CASE WHEN adobe_byodUpvVisitors_direct_wow IS NULL OR adobe_byodUpvVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_direct - adobe_byodUpvVisitors_direct_wow) / adobe_byodUpvVisitors_direct_wow, 6) END AS adobe_byodUpvVisitors_direct_wow_pct, CASE WHEN adobe_byodUpvVisitors_direct_ly  IS NULL OR adobe_byodUpvVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_direct - adobe_byodUpvVisitors_direct_ly)  / adobe_byodUpvVisitors_direct_ly,  6) END AS adobe_byodUpvVisitors_direct_yoy_pct,
    adobe_byodEntryByodPageVisitors_direct, adobe_byodEntryByodPageVisitors_direct_wow, adobe_byodEntryByodPageVisitors_direct_ly, CASE WHEN adobe_byodEntryByodPageVisitors_direct_wow IS NULL OR adobe_byodEntryByodPageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_direct - adobe_byodEntryByodPageVisitors_direct_wow) / adobe_byodEntryByodPageVisitors_direct_wow, 6) END AS adobe_byodEntryByodPageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_direct_ly  IS NULL OR adobe_byodEntryByodPageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_direct - adobe_byodEntryByodPageVisitors_direct_ly)  / adobe_byodEntryByodPageVisitors_direct_ly,  6) END AS adobe_byodEntryByodPageVisitors_direct_yoy_pct,
    adobe_byodEntryHomePageVisitors_direct, adobe_byodEntryHomePageVisitors_direct_wow, adobe_byodEntryHomePageVisitors_direct_ly, CASE WHEN adobe_byodEntryHomePageVisitors_direct_wow IS NULL OR adobe_byodEntryHomePageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_direct - adobe_byodEntryHomePageVisitors_direct_wow) / adobe_byodEntryHomePageVisitors_direct_wow, 6) END AS adobe_byodEntryHomePageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_direct_ly  IS NULL OR adobe_byodEntryHomePageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_direct - adobe_byodEntryHomePageVisitors_direct_ly)  / adobe_byodEntryHomePageVisitors_direct_ly,  6) END AS adobe_byodEntryHomePageVisitors_direct_yoy_pct,
    adobe_byodEntryDevicePageVisitors_direct, adobe_byodEntryDevicePageVisitors_direct_wow, adobe_byodEntryDevicePageVisitors_direct_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_direct_wow IS NULL OR adobe_byodEntryDevicePageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_direct - adobe_byodEntryDevicePageVisitors_direct_wow) / adobe_byodEntryDevicePageVisitors_direct_wow, 6) END AS adobe_byodEntryDevicePageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_direct_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_direct - adobe_byodEntryDevicePageVisitors_direct_ly)  / adobe_byodEntryDevicePageVisitors_direct_ly,  6) END AS adobe_byodEntryDevicePageVisitors_direct_yoy_pct,
    adobe_byodEntryPlansPageVisitors_direct, adobe_byodEntryPlansPageVisitors_direct_wow, adobe_byodEntryPlansPageVisitors_direct_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_direct_wow IS NULL OR adobe_byodEntryPlansPageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_direct - adobe_byodEntryPlansPageVisitors_direct_wow) / adobe_byodEntryPlansPageVisitors_direct_wow, 6) END AS adobe_byodEntryPlansPageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_direct_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_direct - adobe_byodEntryPlansPageVisitors_direct_ly)  / adobe_byodEntryPlansPageVisitors_direct_ly,  6) END AS adobe_byodEntryPlansPageVisitors_direct_yoy_pct,
    adobe_byodEntryOtherPageVisitors_direct, adobe_byodEntryOtherPageVisitors_direct_wow, adobe_byodEntryOtherPageVisitors_direct_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_direct_wow IS NULL OR adobe_byodEntryOtherPageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_direct - adobe_byodEntryOtherPageVisitors_direct_wow) / adobe_byodEntryOtherPageVisitors_direct_wow, 6) END AS adobe_byodEntryOtherPageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_direct_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_direct - adobe_byodEntryOtherPageVisitors_direct_ly)  / adobe_byodEntryOtherPageVisitors_direct_ly,  6) END AS adobe_byodEntryOtherPageVisitors_direct_yoy_pct,
    adobe_byodEntryGetStartedLandingPageVisitors_direct, adobe_byodEntryGetStartedLandingPageVisitors_direct_wow, adobe_byodEntryGetStartedLandingPageVisitors_direct_ly, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_direct_wow IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_direct - adobe_byodEntryGetStartedLandingPageVisitors_direct_wow) / adobe_byodEntryGetStartedLandingPageVisitors_direct_wow, 6) END AS adobe_byodEntryGetStartedLandingPageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_direct_ly  IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_direct - adobe_byodEntryGetStartedLandingPageVisitors_direct_ly)  / adobe_byodEntryGetStartedLandingPageVisitors_direct_ly,  6) END AS adobe_byodEntryGetStartedLandingPageVisitors_direct_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_direct, adobe_byodEntryByodLandingPageVisitors_direct_wow, adobe_byodEntryByodLandingPageVisitors_direct_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_direct_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_direct - adobe_byodEntryByodLandingPageVisitors_direct_wow) / adobe_byodEntryByodLandingPageVisitors_direct_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_direct_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_direct - adobe_byodEntryByodLandingPageVisitors_direct_ly)  / adobe_byodEntryByodLandingPageVisitors_direct_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_direct_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_direct, adobe_byodEntryOffersSwitchVisitors_direct_wow, adobe_byodEntryOffersSwitchVisitors_direct_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_direct_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_direct - adobe_byodEntryOffersSwitchVisitors_direct_wow) / adobe_byodEntryOffersSwitchVisitors_direct_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_direct_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_direct - adobe_byodEntryOffersSwitchVisitors_direct_ly)  / adobe_byodEntryOffersSwitchVisitors_direct_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_direct_yoy_pct,
    -- SOCIAL
    adobe_byodUpvVisitors_social, adobe_byodUpvVisitors_social_wow, adobe_byodUpvVisitors_social_ly, CASE WHEN adobe_byodUpvVisitors_social_wow IS NULL OR adobe_byodUpvVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_social - adobe_byodUpvVisitors_social_wow) / adobe_byodUpvVisitors_social_wow, 6) END AS adobe_byodUpvVisitors_social_wow_pct, CASE WHEN adobe_byodUpvVisitors_social_ly  IS NULL OR adobe_byodUpvVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_social - adobe_byodUpvVisitors_social_ly)  / adobe_byodUpvVisitors_social_ly,  6) END AS adobe_byodUpvVisitors_social_yoy_pct,
    adobe_byodEntryByodPageVisitors_social, adobe_byodEntryByodPageVisitors_social_wow, adobe_byodEntryByodPageVisitors_social_ly, CASE WHEN adobe_byodEntryByodPageVisitors_social_wow IS NULL OR adobe_byodEntryByodPageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_social - adobe_byodEntryByodPageVisitors_social_wow) / adobe_byodEntryByodPageVisitors_social_wow, 6) END AS adobe_byodEntryByodPageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_social_ly  IS NULL OR adobe_byodEntryByodPageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_social - adobe_byodEntryByodPageVisitors_social_ly)  / adobe_byodEntryByodPageVisitors_social_ly,  6) END AS adobe_byodEntryByodPageVisitors_social_yoy_pct,
    adobe_byodEntryHomePageVisitors_social, adobe_byodEntryHomePageVisitors_social_wow, adobe_byodEntryHomePageVisitors_social_ly, CASE WHEN adobe_byodEntryHomePageVisitors_social_wow IS NULL OR adobe_byodEntryHomePageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_social - adobe_byodEntryHomePageVisitors_social_wow) / adobe_byodEntryHomePageVisitors_social_wow, 6) END AS adobe_byodEntryHomePageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_social_ly  IS NULL OR adobe_byodEntryHomePageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_social - adobe_byodEntryHomePageVisitors_social_ly)  / adobe_byodEntryHomePageVisitors_social_ly,  6) END AS adobe_byodEntryHomePageVisitors_social_yoy_pct,
    adobe_byodEntryDevicePageVisitors_social, adobe_byodEntryDevicePageVisitors_social_wow, adobe_byodEntryDevicePageVisitors_social_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_social_wow IS NULL OR adobe_byodEntryDevicePageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_social - adobe_byodEntryDevicePageVisitors_social_wow) / adobe_byodEntryDevicePageVisitors_social_wow, 6) END AS adobe_byodEntryDevicePageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_social_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_social - adobe_byodEntryDevicePageVisitors_social_ly)  / adobe_byodEntryDevicePageVisitors_social_ly,  6) END AS adobe_byodEntryDevicePageVisitors_social_yoy_pct,
    adobe_byodEntryPlansPageVisitors_social, adobe_byodEntryPlansPageVisitors_social_wow, adobe_byodEntryPlansPageVisitors_social_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_social_wow IS NULL OR adobe_byodEntryPlansPageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_social - adobe_byodEntryPlansPageVisitors_social_wow) / adobe_byodEntryPlansPageVisitors_social_wow, 6) END AS adobe_byodEntryPlansPageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_social_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_social - adobe_byodEntryPlansPageVisitors_social_ly)  / adobe_byodEntryPlansPageVisitors_social_ly,  6) END AS adobe_byodEntryPlansPageVisitors_social_yoy_pct,
    adobe_byodEntryOtherPageVisitors_social, adobe_byodEntryOtherPageVisitors_social_wow, adobe_byodEntryOtherPageVisitors_social_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_social_wow IS NULL OR adobe_byodEntryOtherPageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_social - adobe_byodEntryOtherPageVisitors_social_wow) / adobe_byodEntryOtherPageVisitors_social_wow, 6) END AS adobe_byodEntryOtherPageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_social_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_social - adobe_byodEntryOtherPageVisitors_social_ly)  / adobe_byodEntryOtherPageVisitors_social_ly,  6) END AS adobe_byodEntryOtherPageVisitors_social_yoy_pct,
    adobe_byodEntryGetStartedLandingPageVisitors_social, adobe_byodEntryGetStartedLandingPageVisitors_social_wow, adobe_byodEntryGetStartedLandingPageVisitors_social_ly, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_social_wow IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_social - adobe_byodEntryGetStartedLandingPageVisitors_social_wow) / adobe_byodEntryGetStartedLandingPageVisitors_social_wow, 6) END AS adobe_byodEntryGetStartedLandingPageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_social_ly  IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_social - adobe_byodEntryGetStartedLandingPageVisitors_social_ly)  / adobe_byodEntryGetStartedLandingPageVisitors_social_ly,  6) END AS adobe_byodEntryGetStartedLandingPageVisitors_social_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_social, adobe_byodEntryByodLandingPageVisitors_social_wow, adobe_byodEntryByodLandingPageVisitors_social_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_social_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_social - adobe_byodEntryByodLandingPageVisitors_social_wow) / adobe_byodEntryByodLandingPageVisitors_social_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_social_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_social - adobe_byodEntryByodLandingPageVisitors_social_ly)  / adobe_byodEntryByodLandingPageVisitors_social_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_social_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_social, adobe_byodEntryOffersSwitchVisitors_social_wow, adobe_byodEntryOffersSwitchVisitors_social_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_social_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_social - adobe_byodEntryOffersSwitchVisitors_social_wow) / adobe_byodEntryOffersSwitchVisitors_social_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_social_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_social_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_social - adobe_byodEntryOffersSwitchVisitors_social_ly)  / adobe_byodEntryOffersSwitchVisitors_social_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_social_yoy_pct,
    -- PROGRAMMATIC
    adobe_byodUpvVisitors_programmatic, adobe_byodUpvVisitors_programmatic_wow, adobe_byodUpvVisitors_programmatic_ly, CASE WHEN adobe_byodUpvVisitors_programmatic_wow IS NULL OR adobe_byodUpvVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_programmatic - adobe_byodUpvVisitors_programmatic_wow) / adobe_byodUpvVisitors_programmatic_wow, 6) END AS adobe_byodUpvVisitors_programmatic_wow_pct, CASE WHEN adobe_byodUpvVisitors_programmatic_ly  IS NULL OR adobe_byodUpvVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_programmatic - adobe_byodUpvVisitors_programmatic_ly)  / adobe_byodUpvVisitors_programmatic_ly,  6) END AS adobe_byodUpvVisitors_programmatic_yoy_pct,
    adobe_byodEntryByodPageVisitors_programmatic, adobe_byodEntryByodPageVisitors_programmatic_wow, adobe_byodEntryByodPageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryByodPageVisitors_programmatic_wow IS NULL OR adobe_byodEntryByodPageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_programmatic - adobe_byodEntryByodPageVisitors_programmatic_wow) / adobe_byodEntryByodPageVisitors_programmatic_wow, 6) END AS adobe_byodEntryByodPageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryByodPageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_programmatic - adobe_byodEntryByodPageVisitors_programmatic_ly)  / adobe_byodEntryByodPageVisitors_programmatic_ly,  6) END AS adobe_byodEntryByodPageVisitors_programmatic_yoy_pct,
    adobe_byodEntryHomePageVisitors_programmatic, adobe_byodEntryHomePageVisitors_programmatic_wow, adobe_byodEntryHomePageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryHomePageVisitors_programmatic_wow IS NULL OR adobe_byodEntryHomePageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_programmatic - adobe_byodEntryHomePageVisitors_programmatic_wow) / adobe_byodEntryHomePageVisitors_programmatic_wow, 6) END AS adobe_byodEntryHomePageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryHomePageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_programmatic - adobe_byodEntryHomePageVisitors_programmatic_ly)  / adobe_byodEntryHomePageVisitors_programmatic_ly,  6) END AS adobe_byodEntryHomePageVisitors_programmatic_yoy_pct,
    adobe_byodEntryDevicePageVisitors_programmatic, adobe_byodEntryDevicePageVisitors_programmatic_wow, adobe_byodEntryDevicePageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_programmatic_wow IS NULL OR adobe_byodEntryDevicePageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_programmatic - adobe_byodEntryDevicePageVisitors_programmatic_wow) / adobe_byodEntryDevicePageVisitors_programmatic_wow, 6) END AS adobe_byodEntryDevicePageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_programmatic - adobe_byodEntryDevicePageVisitors_programmatic_ly)  / adobe_byodEntryDevicePageVisitors_programmatic_ly,  6) END AS adobe_byodEntryDevicePageVisitors_programmatic_yoy_pct,
    adobe_byodEntryPlansPageVisitors_programmatic, adobe_byodEntryPlansPageVisitors_programmatic_wow, adobe_byodEntryPlansPageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_programmatic_wow IS NULL OR adobe_byodEntryPlansPageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_programmatic - adobe_byodEntryPlansPageVisitors_programmatic_wow) / adobe_byodEntryPlansPageVisitors_programmatic_wow, 6) END AS adobe_byodEntryPlansPageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_programmatic - adobe_byodEntryPlansPageVisitors_programmatic_ly)  / adobe_byodEntryPlansPageVisitors_programmatic_ly,  6) END AS adobe_byodEntryPlansPageVisitors_programmatic_yoy_pct,
    adobe_byodEntryOtherPageVisitors_programmatic, adobe_byodEntryOtherPageVisitors_programmatic_wow, adobe_byodEntryOtherPageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_programmatic_wow IS NULL OR adobe_byodEntryOtherPageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_programmatic - adobe_byodEntryOtherPageVisitors_programmatic_wow) / adobe_byodEntryOtherPageVisitors_programmatic_wow, 6) END AS adobe_byodEntryOtherPageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_programmatic - adobe_byodEntryOtherPageVisitors_programmatic_ly)  / adobe_byodEntryOtherPageVisitors_programmatic_ly,  6) END AS adobe_byodEntryOtherPageVisitors_programmatic_yoy_pct,
    adobe_byodEntryGetStartedLandingPageVisitors_programmatic, adobe_byodEntryGetStartedLandingPageVisitors_programmatic_wow, adobe_byodEntryGetStartedLandingPageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_programmatic_wow IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_programmatic - adobe_byodEntryGetStartedLandingPageVisitors_programmatic_wow) / adobe_byodEntryGetStartedLandingPageVisitors_programmatic_wow, 6) END AS adobe_byodEntryGetStartedLandingPageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_programmatic - adobe_byodEntryGetStartedLandingPageVisitors_programmatic_ly)  / adobe_byodEntryGetStartedLandingPageVisitors_programmatic_ly,  6) END AS adobe_byodEntryGetStartedLandingPageVisitors_programmatic_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_programmatic, adobe_byodEntryByodLandingPageVisitors_programmatic_wow, adobe_byodEntryByodLandingPageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_programmatic_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_programmatic - adobe_byodEntryByodLandingPageVisitors_programmatic_wow) / adobe_byodEntryByodLandingPageVisitors_programmatic_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_programmatic - adobe_byodEntryByodLandingPageVisitors_programmatic_ly)  / adobe_byodEntryByodLandingPageVisitors_programmatic_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_programmatic_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_programmatic, adobe_byodEntryOffersSwitchVisitors_programmatic_wow, adobe_byodEntryOffersSwitchVisitors_programmatic_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_programmatic_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_programmatic - adobe_byodEntryOffersSwitchVisitors_programmatic_wow) / adobe_byodEntryOffersSwitchVisitors_programmatic_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_programmatic_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_programmatic - adobe_byodEntryOffersSwitchVisitors_programmatic_ly)  / adobe_byodEntryOffersSwitchVisitors_programmatic_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_programmatic_yoy_pct,
    -- OTHER
    adobe_byodUpvVisitors_other, adobe_byodUpvVisitors_other_wow, adobe_byodUpvVisitors_other_ly, CASE WHEN adobe_byodUpvVisitors_other_wow IS NULL OR adobe_byodUpvVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_other - adobe_byodUpvVisitors_other_wow) / adobe_byodUpvVisitors_other_wow, 6) END AS adobe_byodUpvVisitors_other_wow_pct, CASE WHEN adobe_byodUpvVisitors_other_ly  IS NULL OR adobe_byodUpvVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUpvVisitors_other - adobe_byodUpvVisitors_other_ly)  / adobe_byodUpvVisitors_other_ly,  6) END AS adobe_byodUpvVisitors_other_yoy_pct,
    adobe_byodEntryByodPageVisitors_other, adobe_byodEntryByodPageVisitors_other_wow, adobe_byodEntryByodPageVisitors_other_ly, CASE WHEN adobe_byodEntryByodPageVisitors_other_wow IS NULL OR adobe_byodEntryByodPageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_other - adobe_byodEntryByodPageVisitors_other_wow) / adobe_byodEntryByodPageVisitors_other_wow, 6) END AS adobe_byodEntryByodPageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_other_ly  IS NULL OR adobe_byodEntryByodPageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_other - adobe_byodEntryByodPageVisitors_other_ly)  / adobe_byodEntryByodPageVisitors_other_ly,  6) END AS adobe_byodEntryByodPageVisitors_other_yoy_pct,
    adobe_byodEntryHomePageVisitors_other, adobe_byodEntryHomePageVisitors_other_wow, adobe_byodEntryHomePageVisitors_other_ly, CASE WHEN adobe_byodEntryHomePageVisitors_other_wow IS NULL OR adobe_byodEntryHomePageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_other - adobe_byodEntryHomePageVisitors_other_wow) / adobe_byodEntryHomePageVisitors_other_wow, 6) END AS adobe_byodEntryHomePageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_other_ly  IS NULL OR adobe_byodEntryHomePageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_other - adobe_byodEntryHomePageVisitors_other_ly)  / adobe_byodEntryHomePageVisitors_other_ly,  6) END AS adobe_byodEntryHomePageVisitors_other_yoy_pct,
    adobe_byodEntryDevicePageVisitors_other, adobe_byodEntryDevicePageVisitors_other_wow, adobe_byodEntryDevicePageVisitors_other_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_other_wow IS NULL OR adobe_byodEntryDevicePageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_other - adobe_byodEntryDevicePageVisitors_other_wow) / adobe_byodEntryDevicePageVisitors_other_wow, 6) END AS adobe_byodEntryDevicePageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_other_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_other - adobe_byodEntryDevicePageVisitors_other_ly)  / adobe_byodEntryDevicePageVisitors_other_ly,  6) END AS adobe_byodEntryDevicePageVisitors_other_yoy_pct,
    adobe_byodEntryPlansPageVisitors_other, adobe_byodEntryPlansPageVisitors_other_wow, adobe_byodEntryPlansPageVisitors_other_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_other_wow IS NULL OR adobe_byodEntryPlansPageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_other - adobe_byodEntryPlansPageVisitors_other_wow) / adobe_byodEntryPlansPageVisitors_other_wow, 6) END AS adobe_byodEntryPlansPageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_other_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_other - adobe_byodEntryPlansPageVisitors_other_ly)  / adobe_byodEntryPlansPageVisitors_other_ly,  6) END AS adobe_byodEntryPlansPageVisitors_other_yoy_pct,
    adobe_byodEntryOtherPageVisitors_other, adobe_byodEntryOtherPageVisitors_other_wow, adobe_byodEntryOtherPageVisitors_other_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_other_wow IS NULL OR adobe_byodEntryOtherPageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_other - adobe_byodEntryOtherPageVisitors_other_wow) / adobe_byodEntryOtherPageVisitors_other_wow, 6) END AS adobe_byodEntryOtherPageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_other_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_other - adobe_byodEntryOtherPageVisitors_other_ly)  / adobe_byodEntryOtherPageVisitors_other_ly,  6) END AS adobe_byodEntryOtherPageVisitors_other_yoy_pct,
    adobe_byodEntryGetStartedLandingPageVisitors_other, adobe_byodEntryGetStartedLandingPageVisitors_other_wow, adobe_byodEntryGetStartedLandingPageVisitors_other_ly, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_other_wow IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_other - adobe_byodEntryGetStartedLandingPageVisitors_other_wow) / adobe_byodEntryGetStartedLandingPageVisitors_other_wow, 6) END AS adobe_byodEntryGetStartedLandingPageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryGetStartedLandingPageVisitors_other_ly  IS NULL OR adobe_byodEntryGetStartedLandingPageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryGetStartedLandingPageVisitors_other - adobe_byodEntryGetStartedLandingPageVisitors_other_ly)  / adobe_byodEntryGetStartedLandingPageVisitors_other_ly,  6) END AS adobe_byodEntryGetStartedLandingPageVisitors_other_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_other, adobe_byodEntryByodLandingPageVisitors_other_wow, adobe_byodEntryByodLandingPageVisitors_other_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_other_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_other - adobe_byodEntryByodLandingPageVisitors_other_wow) / adobe_byodEntryByodLandingPageVisitors_other_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_other_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_other - adobe_byodEntryByodLandingPageVisitors_other_ly)  / adobe_byodEntryByodLandingPageVisitors_other_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_other_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_other, adobe_byodEntryOffersSwitchVisitors_other_wow, adobe_byodEntryOffersSwitchVisitors_other_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_other_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_other - adobe_byodEntryOffersSwitchVisitors_other_wow) / adobe_byodEntryOffersSwitchVisitors_other_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_other_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_other_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_other - adobe_byodEntryOffersSwitchVisitors_other_ly)  / adobe_byodEntryOffersSwitchVisitors_other_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_other_yoy_pct
  FROM with_comparisons
),

with_max_date AS (
  SELECT
    *,
    MAX(CASE WHEN adobe_byodUpvVisitors_allChannels IS NOT NULL THEN week_sun_to_sat END) OVER () AS max_data_date
  FROM with_pcts
)

SELECT
  week_sun_to_sat,
  'ADOBE_BYOD_ENTRY_PAGES' AS data_source,
  max_data_date,
  -- ALL CHANNELS
  adobe_byodUpvVisitors_allChannels, adobe_byodUpvVisitors_allChannels_wow, adobe_byodUpvVisitors_allChannels_ly, adobe_byodUpvVisitors_allChannels_wow_pct, adobe_byodUpvVisitors_allChannels_yoy_pct,
  adobe_byodEntryByodPageVisitors_allChannels, adobe_byodEntryByodPageVisitors_allChannels_wow, adobe_byodEntryByodPageVisitors_allChannels_ly, adobe_byodEntryByodPageVisitors_allChannels_wow_pct, adobe_byodEntryByodPageVisitors_allChannels_yoy_pct,
  adobe_byodEntryHomePageVisitors_allChannels, adobe_byodEntryHomePageVisitors_allChannels_wow, adobe_byodEntryHomePageVisitors_allChannels_ly, adobe_byodEntryHomePageVisitors_allChannels_wow_pct, adobe_byodEntryHomePageVisitors_allChannels_yoy_pct,
  adobe_byodEntryDevicePageVisitors_allChannels, adobe_byodEntryDevicePageVisitors_allChannels_wow, adobe_byodEntryDevicePageVisitors_allChannels_ly, adobe_byodEntryDevicePageVisitors_allChannels_wow_pct, adobe_byodEntryDevicePageVisitors_allChannels_yoy_pct,
  adobe_byodEntryPlansPageVisitors_allChannels, adobe_byodEntryPlansPageVisitors_allChannels_wow, adobe_byodEntryPlansPageVisitors_allChannels_ly, adobe_byodEntryPlansPageVisitors_allChannels_wow_pct, adobe_byodEntryPlansPageVisitors_allChannels_yoy_pct,
  adobe_byodEntryOtherPageVisitors_allChannels, adobe_byodEntryOtherPageVisitors_allChannels_wow, adobe_byodEntryOtherPageVisitors_allChannels_ly, adobe_byodEntryOtherPageVisitors_allChannels_wow_pct, adobe_byodEntryOtherPageVisitors_allChannels_yoy_pct,
  adobe_byodEntryGetStartedLandingPageVisitors_allChannels, adobe_byodEntryGetStartedLandingPageVisitors_allChannels_wow, adobe_byodEntryGetStartedLandingPageVisitors_allChannels_ly, adobe_byodEntryGetStartedLandingPageVisitors_allChannels_wow_pct, adobe_byodEntryGetStartedLandingPageVisitors_allChannels_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_allChannels, adobe_byodEntryByodLandingPageVisitors_allChannels_wow, adobe_byodEntryByodLandingPageVisitors_allChannels_ly, adobe_byodEntryByodLandingPageVisitors_allChannels_wow_pct, adobe_byodEntryByodLandingPageVisitors_allChannels_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_allChannels, adobe_byodEntryOffersSwitchVisitors_allChannels_wow, adobe_byodEntryOffersSwitchVisitors_allChannels_ly, adobe_byodEntryOffersSwitchVisitors_allChannels_wow_pct, adobe_byodEntryOffersSwitchVisitors_allChannels_yoy_pct,  -- NEW
  -- PAID SEARCH
  adobe_byodUpvVisitors_paidSearch, adobe_byodUpvVisitors_paidSearch_wow, adobe_byodUpvVisitors_paidSearch_ly, adobe_byodUpvVisitors_paidSearch_wow_pct, adobe_byodUpvVisitors_paidSearch_yoy_pct,
  adobe_byodEntryByodPageVisitors_paidSearch, adobe_byodEntryByodPageVisitors_paidSearch_wow, adobe_byodEntryByodPageVisitors_paidSearch_ly, adobe_byodEntryByodPageVisitors_paidSearch_wow_pct, adobe_byodEntryByodPageVisitors_paidSearch_yoy_pct,
  adobe_byodEntryHomePageVisitors_paidSearch, adobe_byodEntryHomePageVisitors_paidSearch_wow, adobe_byodEntryHomePageVisitors_paidSearch_ly, adobe_byodEntryHomePageVisitors_paidSearch_wow_pct, adobe_byodEntryHomePageVisitors_paidSearch_yoy_pct,
  adobe_byodEntryDevicePageVisitors_paidSearch, adobe_byodEntryDevicePageVisitors_paidSearch_wow, adobe_byodEntryDevicePageVisitors_paidSearch_ly, adobe_byodEntryDevicePageVisitors_paidSearch_wow_pct, adobe_byodEntryDevicePageVisitors_paidSearch_yoy_pct,
  adobe_byodEntryPlansPageVisitors_paidSearch, adobe_byodEntryPlansPageVisitors_paidSearch_wow, adobe_byodEntryPlansPageVisitors_paidSearch_ly, adobe_byodEntryPlansPageVisitors_paidSearch_wow_pct, adobe_byodEntryPlansPageVisitors_paidSearch_yoy_pct,
  adobe_byodEntryOtherPageVisitors_paidSearch, adobe_byodEntryOtherPageVisitors_paidSearch_wow, adobe_byodEntryOtherPageVisitors_paidSearch_ly, adobe_byodEntryOtherPageVisitors_paidSearch_wow_pct, adobe_byodEntryOtherPageVisitors_paidSearch_yoy_pct,
  adobe_byodEntryGetStartedLandingPageVisitors_paidSearch, adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_wow, adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_ly, adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_wow_pct, adobe_byodEntryGetStartedLandingPageVisitors_paidSearch_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_paidSearch, adobe_byodEntryByodLandingPageVisitors_paidSearch_wow, adobe_byodEntryByodLandingPageVisitors_paidSearch_ly, adobe_byodEntryByodLandingPageVisitors_paidSearch_wow_pct, adobe_byodEntryByodLandingPageVisitors_paidSearch_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_paidSearch, adobe_byodEntryOffersSwitchVisitors_paidSearch_wow, adobe_byodEntryOffersSwitchVisitors_paidSearch_ly, adobe_byodEntryOffersSwitchVisitors_paidSearch_wow_pct, adobe_byodEntryOffersSwitchVisitors_paidSearch_yoy_pct,  -- NEW
  -- ORGANIC SEARCH
  adobe_byodUpvVisitors_organicSearch, adobe_byodUpvVisitors_organicSearch_wow, adobe_byodUpvVisitors_organicSearch_ly, adobe_byodUpvVisitors_organicSearch_wow_pct, adobe_byodUpvVisitors_organicSearch_yoy_pct,
  adobe_byodEntryByodPageVisitors_organicSearch, adobe_byodEntryByodPageVisitors_organicSearch_wow, adobe_byodEntryByodPageVisitors_organicSearch_ly, adobe_byodEntryByodPageVisitors_organicSearch_wow_pct, adobe_byodEntryByodPageVisitors_organicSearch_yoy_pct,
  adobe_byodEntryHomePageVisitors_organicSearch, adobe_byodEntryHomePageVisitors_organicSearch_wow, adobe_byodEntryHomePageVisitors_organicSearch_ly, adobe_byodEntryHomePageVisitors_organicSearch_wow_pct, adobe_byodEntryHomePageVisitors_organicSearch_yoy_pct,
  adobe_byodEntryDevicePageVisitors_organicSearch, adobe_byodEntryDevicePageVisitors_organicSearch_wow, adobe_byodEntryDevicePageVisitors_organicSearch_ly, adobe_byodEntryDevicePageVisitors_organicSearch_wow_pct, adobe_byodEntryDevicePageVisitors_organicSearch_yoy_pct,
  adobe_byodEntryPlansPageVisitors_organicSearch, adobe_byodEntryPlansPageVisitors_organicSearch_wow, adobe_byodEntryPlansPageVisitors_organicSearch_ly, adobe_byodEntryPlansPageVisitors_organicSearch_wow_pct, adobe_byodEntryPlansPageVisitors_organicSearch_yoy_pct,
  adobe_byodEntryOtherPageVisitors_organicSearch, adobe_byodEntryOtherPageVisitors_organicSearch_wow, adobe_byodEntryOtherPageVisitors_organicSearch_ly, adobe_byodEntryOtherPageVisitors_organicSearch_wow_pct, adobe_byodEntryOtherPageVisitors_organicSearch_yoy_pct,
  adobe_byodEntryGetStartedLandingPageVisitors_organicSearch, adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_wow, adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_ly, adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_wow_pct, adobe_byodEntryGetStartedLandingPageVisitors_organicSearch_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_organicSearch, adobe_byodEntryByodLandingPageVisitors_organicSearch_wow, adobe_byodEntryByodLandingPageVisitors_organicSearch_ly, adobe_byodEntryByodLandingPageVisitors_organicSearch_wow_pct, adobe_byodEntryByodLandingPageVisitors_organicSearch_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_organicSearch, adobe_byodEntryOffersSwitchVisitors_organicSearch_wow, adobe_byodEntryOffersSwitchVisitors_organicSearch_ly, adobe_byodEntryOffersSwitchVisitors_organicSearch_wow_pct, adobe_byodEntryOffersSwitchVisitors_organicSearch_yoy_pct,  -- NEW
  -- DIRECT
  adobe_byodUpvVisitors_direct, adobe_byodUpvVisitors_direct_wow, adobe_byodUpvVisitors_direct_ly, adobe_byodUpvVisitors_direct_wow_pct, adobe_byodUpvVisitors_direct_yoy_pct,
  adobe_byodEntryByodPageVisitors_direct, adobe_byodEntryByodPageVisitors_direct_wow, adobe_byodEntryByodPageVisitors_direct_ly, adobe_byodEntryByodPageVisitors_direct_wow_pct, adobe_byodEntryByodPageVisitors_direct_yoy_pct,
  adobe_byodEntryHomePageVisitors_direct, adobe_byodEntryHomePageVisitors_direct_wow, adobe_byodEntryHomePageVisitors_direct_ly, adobe_byodEntryHomePageVisitors_direct_wow_pct, adobe_byodEntryHomePageVisitors_direct_yoy_pct,
  adobe_byodEntryDevicePageVisitors_direct, adobe_byodEntryDevicePageVisitors_direct_wow, adobe_byodEntryDevicePageVisitors_direct_ly, adobe_byodEntryDevicePageVisitors_direct_wow_pct, adobe_byodEntryDevicePageVisitors_direct_yoy_pct,
  adobe_byodEntryPlansPageVisitors_direct, adobe_byodEntryPlansPageVisitors_direct_wow, adobe_byodEntryPlansPageVisitors_direct_ly, adobe_byodEntryPlansPageVisitors_direct_wow_pct, adobe_byodEntryPlansPageVisitors_direct_yoy_pct,
  adobe_byodEntryOtherPageVisitors_direct, adobe_byodEntryOtherPageVisitors_direct_wow, adobe_byodEntryOtherPageVisitors_direct_ly, adobe_byodEntryOtherPageVisitors_direct_wow_pct, adobe_byodEntryOtherPageVisitors_direct_yoy_pct,
  adobe_byodEntryGetStartedLandingPageVisitors_direct, adobe_byodEntryGetStartedLandingPageVisitors_direct_wow, adobe_byodEntryGetStartedLandingPageVisitors_direct_ly, adobe_byodEntryGetStartedLandingPageVisitors_direct_wow_pct, adobe_byodEntryGetStartedLandingPageVisitors_direct_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_direct, adobe_byodEntryByodLandingPageVisitors_direct_wow, adobe_byodEntryByodLandingPageVisitors_direct_ly, adobe_byodEntryByodLandingPageVisitors_direct_wow_pct, adobe_byodEntryByodLandingPageVisitors_direct_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_direct, adobe_byodEntryOffersSwitchVisitors_direct_wow, adobe_byodEntryOffersSwitchVisitors_direct_ly, adobe_byodEntryOffersSwitchVisitors_direct_wow_pct, adobe_byodEntryOffersSwitchVisitors_direct_yoy_pct,  -- NEW
  -- SOCIAL
  adobe_byodUpvVisitors_social, adobe_byodUpvVisitors_social_wow, adobe_byodUpvVisitors_social_ly, adobe_byodUpvVisitors_social_wow_pct, adobe_byodUpvVisitors_social_yoy_pct,
  adobe_byodEntryByodPageVisitors_social, adobe_byodEntryByodPageVisitors_social_wow, adobe_byodEntryByodPageVisitors_social_ly, adobe_byodEntryByodPageVisitors_social_wow_pct, adobe_byodEntryByodPageVisitors_social_yoy_pct,
  adobe_byodEntryHomePageVisitors_social, adobe_byodEntryHomePageVisitors_social_wow, adobe_byodEntryHomePageVisitors_social_ly, adobe_byodEntryHomePageVisitors_social_wow_pct, adobe_byodEntryHomePageVisitors_social_yoy_pct,
  adobe_byodEntryDevicePageVisitors_social, adobe_byodEntryDevicePageVisitors_social_wow, adobe_byodEntryDevicePageVisitors_social_ly, adobe_byodEntryDevicePageVisitors_social_wow_pct, adobe_byodEntryDevicePageVisitors_social_yoy_pct,
  adobe_byodEntryPlansPageVisitors_social, adobe_byodEntryPlansPageVisitors_social_wow, adobe_byodEntryPlansPageVisitors_social_ly, adobe_byodEntryPlansPageVisitors_social_wow_pct, adobe_byodEntryPlansPageVisitors_social_yoy_pct,
  adobe_byodEntryOtherPageVisitors_social, adobe_byodEntryOtherPageVisitors_social_wow, adobe_byodEntryOtherPageVisitors_social_ly, adobe_byodEntryOtherPageVisitors_social_wow_pct, adobe_byodEntryOtherPageVisitors_social_yoy_pct,
  adobe_byodEntryGetStartedLandingPageVisitors_social, adobe_byodEntryGetStartedLandingPageVisitors_social_wow, adobe_byodEntryGetStartedLandingPageVisitors_social_ly, adobe_byodEntryGetStartedLandingPageVisitors_social_wow_pct, adobe_byodEntryGetStartedLandingPageVisitors_social_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_social, adobe_byodEntryByodLandingPageVisitors_social_wow, adobe_byodEntryByodLandingPageVisitors_social_ly, adobe_byodEntryByodLandingPageVisitors_social_wow_pct, adobe_byodEntryByodLandingPageVisitors_social_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_social, adobe_byodEntryOffersSwitchVisitors_social_wow, adobe_byodEntryOffersSwitchVisitors_social_ly, adobe_byodEntryOffersSwitchVisitors_social_wow_pct, adobe_byodEntryOffersSwitchVisitors_social_yoy_pct,  -- NEW
  -- PROGRAMMATIC
  adobe_byodUpvVisitors_programmatic, adobe_byodUpvVisitors_programmatic_wow, adobe_byodUpvVisitors_programmatic_ly, adobe_byodUpvVisitors_programmatic_wow_pct, adobe_byodUpvVisitors_programmatic_yoy_pct,
  adobe_byodEntryByodPageVisitors_programmatic, adobe_byodEntryByodPageVisitors_programmatic_wow, adobe_byodEntryByodPageVisitors_programmatic_ly, adobe_byodEntryByodPageVisitors_programmatic_wow_pct, adobe_byodEntryByodPageVisitors_programmatic_yoy_pct,
  adobe_byodEntryHomePageVisitors_programmatic, adobe_byodEntryHomePageVisitors_programmatic_wow, adobe_byodEntryHomePageVisitors_programmatic_ly, adobe_byodEntryHomePageVisitors_programmatic_wow_pct, adobe_byodEntryHomePageVisitors_programmatic_yoy_pct,
  adobe_byodEntryDevicePageVisitors_programmatic, adobe_byodEntryDevicePageVisitors_programmatic_wow, adobe_byodEntryDevicePageVisitors_programmatic_ly, adobe_byodEntryDevicePageVisitors_programmatic_wow_pct, adobe_byodEntryDevicePageVisitors_programmatic_yoy_pct,
  adobe_byodEntryPlansPageVisitors_programmatic, adobe_byodEntryPlansPageVisitors_programmatic_wow, adobe_byodEntryPlansPageVisitors_programmatic_ly, adobe_byodEntryPlansPageVisitors_programmatic_wow_pct, adobe_byodEntryPlansPageVisitors_programmatic_yoy_pct,
  adobe_byodEntryOtherPageVisitors_programmatic, adobe_byodEntryOtherPageVisitors_programmatic_wow, adobe_byodEntryOtherPageVisitors_programmatic_ly, adobe_byodEntryOtherPageVisitors_programmatic_wow_pct, adobe_byodEntryOtherPageVisitors_programmatic_yoy_pct,
  adobe_byodEntryGetStartedLandingPageVisitors_programmatic, adobe_byodEntryGetStartedLandingPageVisitors_programmatic_wow, adobe_byodEntryGetStartedLandingPageVisitors_programmatic_ly, adobe_byodEntryGetStartedLandingPageVisitors_programmatic_wow_pct, adobe_byodEntryGetStartedLandingPageVisitors_programmatic_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_programmatic, adobe_byodEntryByodLandingPageVisitors_programmatic_wow, adobe_byodEntryByodLandingPageVisitors_programmatic_ly, adobe_byodEntryByodLandingPageVisitors_programmatic_wow_pct, adobe_byodEntryByodLandingPageVisitors_programmatic_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_programmatic, adobe_byodEntryOffersSwitchVisitors_programmatic_wow, adobe_byodEntryOffersSwitchVisitors_programmatic_ly, adobe_byodEntryOffersSwitchVisitors_programmatic_wow_pct, adobe_byodEntryOffersSwitchVisitors_programmatic_yoy_pct,  -- NEW
  -- OTHER
  adobe_byodUpvVisitors_other, adobe_byodUpvVisitors_other_wow, adobe_byodUpvVisitors_other_ly, adobe_byodUpvVisitors_other_wow_pct, adobe_byodUpvVisitors_other_yoy_pct,
  adobe_byodEntryByodPageVisitors_other, adobe_byodEntryByodPageVisitors_other_wow, adobe_byodEntryByodPageVisitors_other_ly, adobe_byodEntryByodPageVisitors_other_wow_pct, adobe_byodEntryByodPageVisitors_other_yoy_pct,
  adobe_byodEntryHomePageVisitors_other, adobe_byodEntryHomePageVisitors_other_wow, adobe_byodEntryHomePageVisitors_other_ly, adobe_byodEntryHomePageVisitors_other_wow_pct, adobe_byodEntryHomePageVisitors_other_yoy_pct,
  adobe_byodEntryDevicePageVisitors_other, adobe_byodEntryDevicePageVisitors_other_wow, adobe_byodEntryDevicePageVisitors_other_ly, adobe_byodEntryDevicePageVisitors_other_wow_pct, adobe_byodEntryDevicePageVisitors_other_yoy_pct,
  adobe_byodEntryPlansPageVisitors_other, adobe_byodEntryPlansPageVisitors_other_wow, adobe_byodEntryPlansPageVisitors_other_ly, adobe_byodEntryPlansPageVisitors_other_wow_pct, adobe_byodEntryPlansPageVisitors_other_yoy_pct,
  adobe_byodEntryOtherPageVisitors_other, adobe_byodEntryOtherPageVisitors_other_wow, adobe_byodEntryOtherPageVisitors_other_ly, adobe_byodEntryOtherPageVisitors_other_wow_pct, adobe_byodEntryOtherPageVisitors_other_yoy_pct,
  adobe_byodEntryGetStartedLandingPageVisitors_other, adobe_byodEntryGetStartedLandingPageVisitors_other_wow, adobe_byodEntryGetStartedLandingPageVisitors_other_ly, adobe_byodEntryGetStartedLandingPageVisitors_other_wow_pct, adobe_byodEntryGetStartedLandingPageVisitors_other_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_other, adobe_byodEntryByodLandingPageVisitors_other_wow, adobe_byodEntryByodLandingPageVisitors_other_ly, adobe_byodEntryByodLandingPageVisitors_other_wow_pct, adobe_byodEntryByodLandingPageVisitors_other_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_other, adobe_byodEntryOffersSwitchVisitors_other_wow, adobe_byodEntryOffersSwitchVisitors_other_ly, adobe_byodEntryOffersSwitchVisitors_other_wow_pct, adobe_byodEntryOffersSwitchVisitors_other_yoy_pct  -- NEW
FROM with_max_date
;

END;