/* =================================================================================================
FILE:         01_vw_sdi_pulseTms_gold_unified_wide.sql
LAYER:        Gold View — Wide
DATASET:      prj-dbi-prd-1.ds_dbi_digitalmedia_automation
VIEW NAME:    vw_sdi_pulseTms_gold_unified_wide

SOURCES:
  prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_silver_profound_weekly
  prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_silver_profoundGofish_weekly
  prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_silver_sa360_weekly
  prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_silver_gsc_weekly
  prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_silver_googleTrends_weekly
  prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_silver_adobe_weekly

DESTINATION:
  prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_gold_unified_wide

PURPOSE:
  Gold Wide view for the pulseTms pipeline.
  One row per week with all metrics from all sources as columns.
  All product lines: BYOD, Postpaid, HSI, Totals.
  Used for: ad-hoc analysis and Excel exports.

BUSINESS GRAIN:
  One row per week_sun_to_sat

PERFORMANCE NOTES:
  - FULL OUTER JOIN chain — each Silver view scanned exactly once
  - SA360 used as base (longest history)
  - COALESCE on week_sun_to_sat ensures no week is lost

DOWNSTREAM:
  vw_sdi_pulseTms_gold_unified_long reads Silver directly (not this view)
================================================================================================= */

CREATE OR REPLACE VIEW `prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_gold_unified_wide`
AS

SELECT

    COALESCE(
        sa.week_sun_to_sat,
        gsc.week_sun_to_sat,
        p.week_sun_to_sat,
        g.week_sun_to_sat,
        t.week_sun_to_sat,
        ab.week_sun_to_sat
    )                                                                   AS week_sun_to_sat,
    'WEEKLY'                                                            AS time_granularity,

    -- -----------------------------------------------------------------------
    -- PROFOUND
    -- -----------------------------------------------------------------------
    p.max_data_date                                                     AS profound_max_data_date,
    p.profound_tmo_nonbrand_visibility_score,
    p.profound_tmo_nonbrand_visibility_score_wow,
    p.profound_tmo_nonbrand_visibility_score_ly,
    p.profound_tmo_nonbrand_visibility_score_wow_pct,
    p.profound_tmo_nonbrand_visibility_score_yoy_pct,
    p.profound_tmo_nonbrand_executions,
    p.profound_tmo_nonbrand_executions_wow,
    p.profound_tmo_nonbrand_executions_ly,
    p.profound_tmo_nonbrand_executions_wow_pct,
    p.profound_tmo_nonbrand_executions_yoy_pct,
    p.profound_tmo_nonbrand_mentions_count,
    p.profound_tmo_nonbrand_mentions_count_wow,
    p.profound_tmo_nonbrand_mentions_count_ly,
    p.profound_tmo_nonbrand_mentions_count_wow_pct,
    p.profound_tmo_nonbrand_mentions_count_yoy_pct,
    p.profound_tmo_nonbrand_share_of_voice,
    p.profound_tmo_nonbrand_share_of_voice_wow,
    p.profound_tmo_nonbrand_share_of_voice_ly,
    p.profound_tmo_nonbrand_share_of_voice_wow_pct,
    p.profound_tmo_nonbrand_share_of_voice_yoy_pct,
    p.profound_verizon_nonbrand_visibility_score,
    p.profound_verizon_nonbrand_visibility_score_wow,
    p.profound_verizon_nonbrand_visibility_score_ly,
    p.profound_verizon_nonbrand_visibility_score_wow_pct,
    p.profound_verizon_nonbrand_visibility_score_yoy_pct,
    p.profound_verizon_nonbrand_executions,
    p.profound_verizon_nonbrand_executions_wow,
    p.profound_verizon_nonbrand_executions_ly,
    p.profound_verizon_nonbrand_executions_wow_pct,
    p.profound_verizon_nonbrand_executions_yoy_pct,
    p.profound_verizon_nonbrand_mentions_count,
    p.profound_verizon_nonbrand_mentions_count_wow,
    p.profound_verizon_nonbrand_mentions_count_ly,
    p.profound_verizon_nonbrand_mentions_count_wow_pct,
    p.profound_verizon_nonbrand_mentions_count_yoy_pct,
    p.profound_verizon_nonbrand_share_of_voice,
    p.profound_verizon_nonbrand_share_of_voice_wow,
    p.profound_verizon_nonbrand_share_of_voice_ly,
    p.profound_verizon_nonbrand_share_of_voice_wow_pct,
    p.profound_verizon_nonbrand_share_of_voice_yoy_pct,
    p.profound_att_nonbrand_visibility_score,
    p.profound_att_nonbrand_visibility_score_wow,
    p.profound_att_nonbrand_visibility_score_ly,
    p.profound_att_nonbrand_visibility_score_wow_pct,
    p.profound_att_nonbrand_visibility_score_yoy_pct,
    p.profound_att_nonbrand_executions,
    p.profound_att_nonbrand_executions_wow,
    p.profound_att_nonbrand_executions_ly,
    p.profound_att_nonbrand_executions_wow_pct,
    p.profound_att_nonbrand_executions_yoy_pct,
    p.profound_att_nonbrand_mentions_count,
    p.profound_att_nonbrand_mentions_count_wow,
    p.profound_att_nonbrand_mentions_count_ly,
    p.profound_att_nonbrand_mentions_count_wow_pct,
    p.profound_att_nonbrand_mentions_count_yoy_pct,
    p.profound_att_nonbrand_share_of_voice,
    p.profound_att_nonbrand_share_of_voice_wow,
    p.profound_att_nonbrand_share_of_voice_ly,
    p.profound_att_nonbrand_share_of_voice_wow_pct,
    p.profound_att_nonbrand_share_of_voice_yoy_pct,

    -- -----------------------------------------------------------------------
    -- GOFISH
    -- -----------------------------------------------------------------------
    g.max_data_date                                                     AS gofish_max_data_date,
    g.gofish_tmo_brand_visibility_score,
    g.gofish_tmo_brand_visibility_score_wow,
    g.gofish_tmo_brand_visibility_score_ly,
    g.gofish_tmo_brand_visibility_score_wow_pct,
    g.gofish_tmo_brand_visibility_score_yoy_pct,
    g.gofish_tmo_brand_executions,
    g.gofish_tmo_brand_executions_wow,
    g.gofish_tmo_brand_executions_ly,
    g.gofish_tmo_brand_executions_wow_pct,
    g.gofish_tmo_brand_executions_yoy_pct,
    g.gofish_tmo_brand_mentions_count,
    g.gofish_tmo_brand_mentions_count_wow,
    g.gofish_tmo_brand_mentions_count_ly,
    g.gofish_tmo_brand_mentions_count_wow_pct,
    g.gofish_tmo_brand_mentions_count_yoy_pct,
    g.gofish_tmo_brand_share_of_voice,
    g.gofish_tmo_brand_share_of_voice_wow,
    g.gofish_tmo_brand_share_of_voice_ly,
    g.gofish_tmo_brand_share_of_voice_wow_pct,
    g.gofish_tmo_brand_share_of_voice_yoy_pct,
    g.gofish_verizon_brand_visibility_score,
    g.gofish_verizon_brand_visibility_score_wow,
    g.gofish_verizon_brand_visibility_score_ly,
    g.gofish_verizon_brand_visibility_score_wow_pct,
    g.gofish_verizon_brand_visibility_score_yoy_pct,
    g.gofish_verizon_brand_executions,
    g.gofish_verizon_brand_executions_wow,
    g.gofish_verizon_brand_executions_ly,
    g.gofish_verizon_brand_executions_wow_pct,
    g.gofish_verizon_brand_executions_yoy_pct,
    g.gofish_verizon_brand_mentions_count,
    g.gofish_verizon_brand_mentions_count_wow,
    g.gofish_verizon_brand_mentions_count_ly,
    g.gofish_verizon_brand_mentions_count_wow_pct,
    g.gofish_verizon_brand_mentions_count_yoy_pct,
    g.gofish_verizon_brand_share_of_voice,
    g.gofish_verizon_brand_share_of_voice_wow,
    g.gofish_verizon_brand_share_of_voice_ly,
    g.gofish_verizon_brand_share_of_voice_wow_pct,
    g.gofish_verizon_brand_share_of_voice_yoy_pct,
    g.gofish_att_brand_visibility_score,
    g.gofish_att_brand_visibility_score_wow,
    g.gofish_att_brand_visibility_score_ly,
    g.gofish_att_brand_visibility_score_wow_pct,
    g.gofish_att_brand_visibility_score_yoy_pct,
    g.gofish_att_brand_executions,
    g.gofish_att_brand_executions_wow,
    g.gofish_att_brand_executions_ly,
    g.gofish_att_brand_executions_wow_pct,
    g.gofish_att_brand_executions_yoy_pct,
    g.gofish_att_brand_mentions_count,
    g.gofish_att_brand_mentions_count_wow,
    g.gofish_att_brand_mentions_count_ly,
    g.gofish_att_brand_mentions_count_wow_pct,
    g.gofish_att_brand_mentions_count_yoy_pct,
    g.gofish_att_brand_share_of_voice,
    g.gofish_att_brand_share_of_voice_wow,
    g.gofish_att_brand_share_of_voice_ly,
    g.gofish_att_brand_share_of_voice_wow_pct,
    g.gofish_att_brand_share_of_voice_yoy_pct,

    -- -----------------------------------------------------------------------
    -- SA360
    -- -----------------------------------------------------------------------
    sa.max_data_date                                                    AS sa360_max_data_date,
    sa.sa360_tmo_brand_impressions,
    sa.sa360_tmo_brand_impressions_wow,
    sa.sa360_tmo_brand_impressions_ly,
    sa.sa360_tmo_brand_impressions_wow_pct,
    sa.sa360_tmo_brand_impressions_yoy_pct,
    sa.sa360_tmo_brand_clicks,
    sa.sa360_tmo_brand_clicks_wow,
    sa.sa360_tmo_brand_clicks_ly,
    sa.sa360_tmo_brand_clicks_wow_pct,
    sa.sa360_tmo_brand_clicks_yoy_pct,
    sa.sa360_tmo_brand_cost,
    sa.sa360_tmo_brand_cost_wow,
    sa.sa360_tmo_brand_cost_ly,
    sa.sa360_tmo_brand_cost_wow_pct,
    sa.sa360_tmo_brand_cost_yoy_pct,
    sa.sa360_tmo_brand_orders,
    sa.sa360_tmo_brand_orders_wow,
    sa.sa360_tmo_brand_orders_ly,
    sa.sa360_tmo_brand_orders_wow_pct,
    sa.sa360_tmo_brand_orders_yoy_pct,
    sa.sa360_tmo_brand_cart_start,
    sa.sa360_tmo_brand_cart_start_wow,
    sa.sa360_tmo_brand_cart_start_ly,
    sa.sa360_tmo_brand_cart_start_wow_pct,
    sa.sa360_tmo_brand_cart_start_yoy_pct,
    sa.sa360_tmo_brand_postpaid_pspv,
    sa.sa360_tmo_brand_postpaid_pspv_wow,
    sa.sa360_tmo_brand_postpaid_pspv_ly,
    sa.sa360_tmo_brand_postpaid_pspv_wow_pct,
    sa.sa360_tmo_brand_postpaid_pspv_yoy_pct,
    sa.sa360_tmo_nonbrand_impressions,
    sa.sa360_tmo_nonbrand_impressions_wow,
    sa.sa360_tmo_nonbrand_impressions_ly,
    sa.sa360_tmo_nonbrand_impressions_wow_pct,
    sa.sa360_tmo_nonbrand_impressions_yoy_pct,
    sa.sa360_tmo_nonbrand_clicks,
    sa.sa360_tmo_nonbrand_clicks_wow,
    sa.sa360_tmo_nonbrand_clicks_ly,
    sa.sa360_tmo_nonbrand_clicks_wow_pct,
    sa.sa360_tmo_nonbrand_clicks_yoy_pct,
    sa.sa360_tmo_nonbrand_cost,
    sa.sa360_tmo_nonbrand_cost_wow,
    sa.sa360_tmo_nonbrand_cost_ly,
    sa.sa360_tmo_nonbrand_cost_wow_pct,
    sa.sa360_tmo_nonbrand_cost_yoy_pct,
    sa.sa360_tmo_nonbrand_orders,
    sa.sa360_tmo_nonbrand_orders_wow,
    sa.sa360_tmo_nonbrand_orders_ly,
    sa.sa360_tmo_nonbrand_orders_wow_pct,
    sa.sa360_tmo_nonbrand_orders_yoy_pct,
    sa.sa360_tmo_nonbrand_cart_start,
    sa.sa360_tmo_nonbrand_cart_start_wow,
    sa.sa360_tmo_nonbrand_cart_start_ly,
    sa.sa360_tmo_nonbrand_cart_start_wow_pct,
    sa.sa360_tmo_nonbrand_cart_start_yoy_pct,
    sa.sa360_tmo_nonbrand_postpaid_pspv,
    sa.sa360_tmo_nonbrand_postpaid_pspv_wow,
    sa.sa360_tmo_nonbrand_postpaid_pspv_ly,
    sa.sa360_tmo_nonbrand_postpaid_pspv_wow_pct,
    sa.sa360_tmo_nonbrand_postpaid_pspv_yoy_pct,

    -- -----------------------------------------------------------------------
    -- GSC
    -- -----------------------------------------------------------------------
    gsc.max_data_date                                                   AS gsc_max_data_date,
    gsc.gsc_tmo_brand_impressions,
    gsc.gsc_tmo_brand_impressions_wow,
    gsc.gsc_tmo_brand_impressions_ly,
    gsc.gsc_tmo_brand_impressions_wow_pct,
    gsc.gsc_tmo_brand_impressions_yoy_pct,
    gsc.gsc_tmo_brand_clicks,
    gsc.gsc_tmo_brand_clicks_wow,
    gsc.gsc_tmo_brand_clicks_ly,
    gsc.gsc_tmo_brand_clicks_wow_pct,
    gsc.gsc_tmo_brand_clicks_yoy_pct,
    gsc.gsc_tmo_nonbrand_impressions,
    gsc.gsc_tmo_nonbrand_impressions_wow,
    gsc.gsc_tmo_nonbrand_impressions_ly,
    gsc.gsc_tmo_nonbrand_impressions_wow_pct,
    gsc.gsc_tmo_nonbrand_impressions_yoy_pct,
    gsc.gsc_tmo_nonbrand_clicks,
    gsc.gsc_tmo_nonbrand_clicks_wow,
    gsc.gsc_tmo_nonbrand_clicks_ly,
    gsc.gsc_tmo_nonbrand_clicks_wow_pct,
    gsc.gsc_tmo_nonbrand_clicks_yoy_pct,

    -- -----------------------------------------------------------------------
    -- TRENDS
    -- -----------------------------------------------------------------------
    t.max_data_date                                                     AS trends_max_data_date,
    t.trends_byod_index,
    t.trends_byod_index_wow,
    t.trends_byod_index_ly,
    t.trends_byod_index_wow_pct,
    t.trends_byod_index_yoy_pct,
    t.trends_top_kw_1,
    t.trends_kw1_interest,
    t.trends_kw1_change,
    t.trends_top_kw_2,
    t.trends_kw2_interest,
    t.trends_kw2_change,
    t.trends_top_kw_3,
    t.trends_kw3_interest,
    t.trends_kw3_change,
    t.trends_top_kw_4,
    t.trends_kw4_interest,
    t.trends_kw4_change,
    t.trends_top_kw_5,
    t.trends_kw5_interest,
    t.trends_kw5_change,

    -- -----------------------------------------------------------------------
    -- ADOBE: All product lines + all channels
    -- -----------------------------------------------------------------------
    ab.max_data_date                                                    AS adobe_max_data_date,

    ab.adobe_uvnbTotalAdobe_allChannels,
    ab.adobe_uvnbTotalAdobe_allChannels_wow,
    ab.adobe_uvnbTotalAdobe_allChannels_ly,
    ab.adobe_uvnbTotalAdobe_allChannels_wow_pct,
    ab.adobe_uvnbTotalAdobe_allChannels_yoy_pct,

    ab.adobe_uvnbFlowTotal_allChannels,
    ab.adobe_uvnbFlowTotal_allChannels_wow,
    ab.adobe_uvnbFlowTotal_allChannels_ly,
    ab.adobe_uvnbFlowTotal_allChannels_wow_pct,
    ab.adobe_uvnbFlowTotal_allChannels_yoy_pct,

    ab.adobe_uvnbByodPctOfUvnbFlow_allChannels,
    ab.adobe_uvnbByodPctOfUvnbFlow_allChannels_wow,
    ab.adobe_uvnbByodPctOfUvnbFlow_allChannels_ly,
    ab.adobe_uvnbByodPctOfUvnbFlow_allChannels_wow_pct,
    ab.adobe_uvnbByodPctOfUvnbFlow_allChannels_yoy_pct,

    ab.adobe_uvnbPostpaid_allChannels,
    ab.adobe_uvnbPostpaid_allChannels_wow,
    ab.adobe_uvnbPostpaid_allChannels_ly,
    ab.adobe_uvnbPostpaid_allChannels_wow_pct,
    ab.adobe_uvnbPostpaid_allChannels_yoy_pct,

    ab.adobe_uvnbPostpaid_paidSearch,
    ab.adobe_uvnbPostpaid_paidSearch_wow,
    ab.adobe_uvnbPostpaid_paidSearch_ly,
    ab.adobe_uvnbPostpaid_paidSearch_wow_pct,
    ab.adobe_uvnbPostpaid_paidSearch_yoy_pct,

    ab.adobe_uvnbPostpaid_organicSearch,
    ab.adobe_uvnbPostpaid_organicSearch_wow,
    ab.adobe_uvnbPostpaid_organicSearch_ly,
    ab.adobe_uvnbPostpaid_organicSearch_wow_pct,
    ab.adobe_uvnbPostpaid_organicSearch_yoy_pct,

    ab.adobe_uvnbPostpaid_direct,
    ab.adobe_uvnbPostpaid_direct_wow,
    ab.adobe_uvnbPostpaid_direct_ly,
    ab.adobe_uvnbPostpaid_direct_wow_pct,
    ab.adobe_uvnbPostpaid_direct_yoy_pct,

    ab.adobe_uvnbPostpaid_social,
    ab.adobe_uvnbPostpaid_social_wow,
    ab.adobe_uvnbPostpaid_social_ly,
    ab.adobe_uvnbPostpaid_social_wow_pct,
    ab.adobe_uvnbPostpaid_social_yoy_pct,

    ab.adobe_uvnbPostpaid_programmatic,
    ab.adobe_uvnbPostpaid_programmatic_wow,
    ab.adobe_uvnbPostpaid_programmatic_ly,
    ab.adobe_uvnbPostpaid_programmatic_wow_pct,
    ab.adobe_uvnbPostpaid_programmatic_yoy_pct,

    ab.adobe_uvnbPostpaid_other,
    ab.adobe_uvnbPostpaid_other_wow,
    ab.adobe_uvnbPostpaid_other_ly,
    ab.adobe_uvnbPostpaid_other_wow_pct,
    ab.adobe_uvnbPostpaid_other_yoy_pct,

    ab.adobe_uvnbHsi_allChannels,
    ab.adobe_uvnbHsi_allChannels_wow,
    ab.adobe_uvnbHsi_allChannels_ly,
    ab.adobe_uvnbHsi_allChannels_wow_pct,
    ab.adobe_uvnbHsi_allChannels_yoy_pct,

    ab.adobe_uvnbHsi_paidSearch,
    ab.adobe_uvnbHsi_paidSearch_wow,
    ab.adobe_uvnbHsi_paidSearch_ly,
    ab.adobe_uvnbHsi_paidSearch_wow_pct,
    ab.adobe_uvnbHsi_paidSearch_yoy_pct,

    ab.adobe_uvnbHsi_organicSearch,
    ab.adobe_uvnbHsi_organicSearch_wow,
    ab.adobe_uvnbHsi_organicSearch_ly,
    ab.adobe_uvnbHsi_organicSearch_wow_pct,
    ab.adobe_uvnbHsi_organicSearch_yoy_pct,

    ab.adobe_uvnbHsi_direct,
    ab.adobe_uvnbHsi_direct_wow,
    ab.adobe_uvnbHsi_direct_ly,
    ab.adobe_uvnbHsi_direct_wow_pct,
    ab.adobe_uvnbHsi_direct_yoy_pct,

    ab.adobe_uvnbHsi_social,
    ab.adobe_uvnbHsi_social_wow,
    ab.adobe_uvnbHsi_social_ly,
    ab.adobe_uvnbHsi_social_wow_pct,
    ab.adobe_uvnbHsi_social_yoy_pct,

    ab.adobe_uvnbHsi_programmatic,
    ab.adobe_uvnbHsi_programmatic_wow,
    ab.adobe_uvnbHsi_programmatic_ly,
    ab.adobe_uvnbHsi_programmatic_wow_pct,
    ab.adobe_uvnbHsi_programmatic_yoy_pct,

    ab.adobe_uvnbHsi_other,
    ab.adobe_uvnbHsi_other_wow,
    ab.adobe_uvnbHsi_other_ly,
    ab.adobe_uvnbHsi_other_wow_pct,
    ab.adobe_uvnbHsi_other_yoy_pct,

    ab.adobe_uvnbByod_allChannels,
    ab.adobe_uvnbByod_allChannels_wow,
    ab.adobe_uvnbByod_allChannels_ly,
    ab.adobe_uvnbByod_allChannels_wow_pct,
    ab.adobe_uvnbByod_allChannels_yoy_pct,

    ab.adobe_uvnbByod_paidSearch,
    ab.adobe_uvnbByod_paidSearch_wow,
    ab.adobe_uvnbByod_paidSearch_ly,
    ab.adobe_uvnbByod_paidSearch_wow_pct,
    ab.adobe_uvnbByod_paidSearch_yoy_pct,

    ab.adobe_uvnbByod_organicSearch,
    ab.adobe_uvnbByod_organicSearch_wow,
    ab.adobe_uvnbByod_organicSearch_ly,
    ab.adobe_uvnbByod_organicSearch_wow_pct,
    ab.adobe_uvnbByod_organicSearch_yoy_pct,

    ab.adobe_uvnbByod_direct,
    ab.adobe_uvnbByod_direct_wow,
    ab.adobe_uvnbByod_direct_ly,
    ab.adobe_uvnbByod_direct_wow_pct,
    ab.adobe_uvnbByod_direct_yoy_pct,

    ab.adobe_uvnbByod_social,
    ab.adobe_uvnbByod_social_wow,
    ab.adobe_uvnbByod_social_ly,
    ab.adobe_uvnbByod_social_wow_pct,
    ab.adobe_uvnbByod_social_yoy_pct,

    ab.adobe_uvnbByod_programmatic,
    ab.adobe_uvnbByod_programmatic_wow,
    ab.adobe_uvnbByod_programmatic_ly,
    ab.adobe_uvnbByod_programmatic_wow_pct,
    ab.adobe_uvnbByod_programmatic_yoy_pct,

    ab.adobe_uvnbByod_other,
    ab.adobe_uvnbByod_other_wow,
    ab.adobe_uvnbByod_other_ly,
    ab.adobe_uvnbByod_other_wow_pct,
    ab.adobe_uvnbByod_other_yoy_pct,

    ab.adobe_uvnbTrackedFlowSum_allChannels,
    ab.adobe_uvnbTrackedFlowSum_allChannels_wow,
    ab.adobe_uvnbTrackedFlowSum_allChannels_ly,
    ab.adobe_uvnbTrackedFlowSum_allChannels_wow_pct,
    ab.adobe_uvnbTrackedFlowSum_allChannels_yoy_pct,

    ab.adobe_uvnbTrackedFlowSum_paidSearch,
    ab.adobe_uvnbTrackedFlowSum_paidSearch_wow,
    ab.adobe_uvnbTrackedFlowSum_paidSearch_ly,
    ab.adobe_uvnbTrackedFlowSum_paidSearch_wow_pct,
    ab.adobe_uvnbTrackedFlowSum_paidSearch_yoy_pct,

    ab.adobe_uvnbTrackedFlowSum_organicSearch,
    ab.adobe_uvnbTrackedFlowSum_organicSearch_wow,
    ab.adobe_uvnbTrackedFlowSum_organicSearch_ly,
    ab.adobe_uvnbTrackedFlowSum_organicSearch_wow_pct,
    ab.adobe_uvnbTrackedFlowSum_organicSearch_yoy_pct,

    ab.adobe_uvnbTrackedFlowSum_direct,
    ab.adobe_uvnbTrackedFlowSum_direct_wow,
    ab.adobe_uvnbTrackedFlowSum_direct_ly,
    ab.adobe_uvnbTrackedFlowSum_direct_wow_pct,
    ab.adobe_uvnbTrackedFlowSum_direct_yoy_pct,

    ab.adobe_uvnbTrackedFlowSum_social,
    ab.adobe_uvnbTrackedFlowSum_social_wow,
    ab.adobe_uvnbTrackedFlowSum_social_ly,
    ab.adobe_uvnbTrackedFlowSum_social_wow_pct,
    ab.adobe_uvnbTrackedFlowSum_social_yoy_pct,

    ab.adobe_uvnbTrackedFlowSum_programmatic,
    ab.adobe_uvnbTrackedFlowSum_programmatic_wow,
    ab.adobe_uvnbTrackedFlowSum_programmatic_ly,
    ab.adobe_uvnbTrackedFlowSum_programmatic_wow_pct,
    ab.adobe_uvnbTrackedFlowSum_programmatic_yoy_pct,

    ab.adobe_uvnbTrackedFlowSum_other,
    ab.adobe_uvnbTrackedFlowSum_other_wow,
    ab.adobe_uvnbTrackedFlowSum_other_ly,
    ab.adobe_uvnbTrackedFlowSum_other_wow_pct,
    ab.adobe_uvnbTrackedFlowSum_other_yoy_pct,

    ab.adobe_cartStartTotal_allChannels,
    ab.adobe_cartStartTotal_allChannels_wow,
    ab.adobe_cartStartTotal_allChannels_ly,
    ab.adobe_cartStartTotal_allChannels_wow_pct,
    ab.adobe_cartStartTotal_allChannels_yoy_pct,

    ab.adobe_cartStartTotal_paidSearch,
    ab.adobe_cartStartTotal_paidSearch_wow,
    ab.adobe_cartStartTotal_paidSearch_ly,
    ab.adobe_cartStartTotal_paidSearch_wow_pct,
    ab.adobe_cartStartTotal_paidSearch_yoy_pct,

    ab.adobe_cartStartTotal_organicSearch,
    ab.adobe_cartStartTotal_organicSearch_wow,
    ab.adobe_cartStartTotal_organicSearch_ly,
    ab.adobe_cartStartTotal_organicSearch_wow_pct,
    ab.adobe_cartStartTotal_organicSearch_yoy_pct,

    ab.adobe_cartStartTotal_direct,
    ab.adobe_cartStartTotal_direct_wow,
    ab.adobe_cartStartTotal_direct_ly,
    ab.adobe_cartStartTotal_direct_wow_pct,
    ab.adobe_cartStartTotal_direct_yoy_pct,

    ab.adobe_cartStartTotal_social,
    ab.adobe_cartStartTotal_social_wow,
    ab.adobe_cartStartTotal_social_ly,
    ab.adobe_cartStartTotal_social_wow_pct,
    ab.adobe_cartStartTotal_social_yoy_pct,

    ab.adobe_cartStartTotal_programmatic,
    ab.adobe_cartStartTotal_programmatic_wow,
    ab.adobe_cartStartTotal_programmatic_ly,
    ab.adobe_cartStartTotal_programmatic_wow_pct,
    ab.adobe_cartStartTotal_programmatic_yoy_pct,

    ab.adobe_cartStartTotal_other,
    ab.adobe_cartStartTotal_other_wow,
    ab.adobe_cartStartTotal_other_ly,
    ab.adobe_cartStartTotal_other_wow_pct,
    ab.adobe_cartStartTotal_other_yoy_pct,

    ab.adobe_cartStartPostpaid_allChannels,
    ab.adobe_cartStartPostpaid_allChannels_wow,
    ab.adobe_cartStartPostpaid_allChannels_ly,
    ab.adobe_cartStartPostpaid_allChannels_wow_pct,
    ab.adobe_cartStartPostpaid_allChannels_yoy_pct,

    ab.adobe_cartStartPostpaid_paidSearch,
    ab.adobe_cartStartPostpaid_paidSearch_wow,
    ab.adobe_cartStartPostpaid_paidSearch_ly,
    ab.adobe_cartStartPostpaid_paidSearch_wow_pct,
    ab.adobe_cartStartPostpaid_paidSearch_yoy_pct,

    ab.adobe_cartStartPostpaid_organicSearch,
    ab.adobe_cartStartPostpaid_organicSearch_wow,
    ab.adobe_cartStartPostpaid_organicSearch_ly,
    ab.adobe_cartStartPostpaid_organicSearch_wow_pct,
    ab.adobe_cartStartPostpaid_organicSearch_yoy_pct,

    ab.adobe_cartStartPostpaid_direct,
    ab.adobe_cartStartPostpaid_direct_wow,
    ab.adobe_cartStartPostpaid_direct_ly,
    ab.adobe_cartStartPostpaid_direct_wow_pct,
    ab.adobe_cartStartPostpaid_direct_yoy_pct,

    ab.adobe_cartStartPostpaid_social,
    ab.adobe_cartStartPostpaid_social_wow,
    ab.adobe_cartStartPostpaid_social_ly,
    ab.adobe_cartStartPostpaid_social_wow_pct,
    ab.adobe_cartStartPostpaid_social_yoy_pct,

    ab.adobe_cartStartPostpaid_programmatic,
    ab.adobe_cartStartPostpaid_programmatic_wow,
    ab.adobe_cartStartPostpaid_programmatic_ly,
    ab.adobe_cartStartPostpaid_programmatic_wow_pct,
    ab.adobe_cartStartPostpaid_programmatic_yoy_pct,

    ab.adobe_cartStartPostpaid_other,
    ab.adobe_cartStartPostpaid_other_wow,
    ab.adobe_cartStartPostpaid_other_ly,
    ab.adobe_cartStartPostpaid_other_wow_pct,
    ab.adobe_cartStartPostpaid_other_yoy_pct,

    ab.adobe_cartStartHsi_allChannels,
    ab.adobe_cartStartHsi_allChannels_wow,
    ab.adobe_cartStartHsi_allChannels_ly,
    ab.adobe_cartStartHsi_allChannels_wow_pct,
    ab.adobe_cartStartHsi_allChannels_yoy_pct,

    ab.adobe_cartStartHsi_paidSearch,
    ab.adobe_cartStartHsi_paidSearch_wow,
    ab.adobe_cartStartHsi_paidSearch_ly,
    ab.adobe_cartStartHsi_paidSearch_wow_pct,
    ab.adobe_cartStartHsi_paidSearch_yoy_pct,

    ab.adobe_cartStartHsi_organicSearch,
    ab.adobe_cartStartHsi_organicSearch_wow,
    ab.adobe_cartStartHsi_organicSearch_ly,
    ab.adobe_cartStartHsi_organicSearch_wow_pct,
    ab.adobe_cartStartHsi_organicSearch_yoy_pct,

    ab.adobe_cartStartHsi_direct,
    ab.adobe_cartStartHsi_direct_wow,
    ab.adobe_cartStartHsi_direct_ly,
    ab.adobe_cartStartHsi_direct_wow_pct,
    ab.adobe_cartStartHsi_direct_yoy_pct,

    ab.adobe_cartStartHsi_social,
    ab.adobe_cartStartHsi_social_wow,
    ab.adobe_cartStartHsi_social_ly,
    ab.adobe_cartStartHsi_social_wow_pct,
    ab.adobe_cartStartHsi_social_yoy_pct,

    ab.adobe_cartStartHsi_programmatic,
    ab.adobe_cartStartHsi_programmatic_wow,
    ab.adobe_cartStartHsi_programmatic_ly,
    ab.adobe_cartStartHsi_programmatic_wow_pct,
    ab.adobe_cartStartHsi_programmatic_yoy_pct,

    ab.adobe_cartStartHsi_other,
    ab.adobe_cartStartHsi_other_wow,
    ab.adobe_cartStartHsi_other_ly,
    ab.adobe_cartStartHsi_other_wow_pct,
    ab.adobe_cartStartHsi_other_yoy_pct,

    ab.adobe_cartStartByod_allChannels,
    ab.adobe_cartStartByod_allChannels_wow,
    ab.adobe_cartStartByod_allChannels_ly,
    ab.adobe_cartStartByod_allChannels_wow_pct,
    ab.adobe_cartStartByod_allChannels_yoy_pct,

    ab.adobe_cartStartByod_paidSearch,
    ab.adobe_cartStartByod_paidSearch_wow,
    ab.adobe_cartStartByod_paidSearch_ly,
    ab.adobe_cartStartByod_paidSearch_wow_pct,
    ab.adobe_cartStartByod_paidSearch_yoy_pct,

    ab.adobe_cartStartByod_organicSearch,
    ab.adobe_cartStartByod_organicSearch_wow,
    ab.adobe_cartStartByod_organicSearch_ly,
    ab.adobe_cartStartByod_organicSearch_wow_pct,
    ab.adobe_cartStartByod_organicSearch_yoy_pct,

    ab.adobe_cartStartByod_direct,
    ab.adobe_cartStartByod_direct_wow,
    ab.adobe_cartStartByod_direct_ly,
    ab.adobe_cartStartByod_direct_wow_pct,
    ab.adobe_cartStartByod_direct_yoy_pct,

    ab.adobe_cartStartByod_social,
    ab.adobe_cartStartByod_social_wow,
    ab.adobe_cartStartByod_social_ly,
    ab.adobe_cartStartByod_social_wow_pct,
    ab.adobe_cartStartByod_social_yoy_pct,

    ab.adobe_cartStartByod_programmatic,
    ab.adobe_cartStartByod_programmatic_wow,
    ab.adobe_cartStartByod_programmatic_ly,
    ab.adobe_cartStartByod_programmatic_wow_pct,
    ab.adobe_cartStartByod_programmatic_yoy_pct,

    ab.adobe_cartStartByod_other,
    ab.adobe_cartStartByod_other_wow,
    ab.adobe_cartStartByod_other_ly,
    ab.adobe_cartStartByod_other_wow_pct,
    ab.adobe_cartStartByod_other_yoy_pct,

    ab.adobe_ordersTotal_allChannels,
    ab.adobe_ordersTotal_allChannels_wow,
    ab.adobe_ordersTotal_allChannels_ly,
    ab.adobe_ordersTotal_allChannels_wow_pct,
    ab.adobe_ordersTotal_allChannels_yoy_pct,

    ab.adobe_ordersTotal_paidSearch,
    ab.adobe_ordersTotal_paidSearch_wow,
    ab.adobe_ordersTotal_paidSearch_ly,
    ab.adobe_ordersTotal_paidSearch_wow_pct,
    ab.adobe_ordersTotal_paidSearch_yoy_pct,

    ab.adobe_ordersTotal_organicSearch,
    ab.adobe_ordersTotal_organicSearch_wow,
    ab.adobe_ordersTotal_organicSearch_ly,
    ab.adobe_ordersTotal_organicSearch_wow_pct,
    ab.adobe_ordersTotal_organicSearch_yoy_pct,

    ab.adobe_ordersTotal_direct,
    ab.adobe_ordersTotal_direct_wow,
    ab.adobe_ordersTotal_direct_ly,
    ab.adobe_ordersTotal_direct_wow_pct,
    ab.adobe_ordersTotal_direct_yoy_pct,

    ab.adobe_ordersTotal_social,
    ab.adobe_ordersTotal_social_wow,
    ab.adobe_ordersTotal_social_ly,
    ab.adobe_ordersTotal_social_wow_pct,
    ab.adobe_ordersTotal_social_yoy_pct,

    ab.adobe_ordersTotal_programmatic,
    ab.adobe_ordersTotal_programmatic_wow,
    ab.adobe_ordersTotal_programmatic_ly,
    ab.adobe_ordersTotal_programmatic_wow_pct,
    ab.adobe_ordersTotal_programmatic_yoy_pct,

    ab.adobe_ordersTotal_other,
    ab.adobe_ordersTotal_other_wow,
    ab.adobe_ordersTotal_other_ly,
    ab.adobe_ordersTotal_other_wow_pct,
    ab.adobe_ordersTotal_other_yoy_pct,

    ab.adobe_ordersUnassistedTotal_allChannels,
    ab.adobe_ordersUnassistedTotal_allChannels_wow,
    ab.adobe_ordersUnassistedTotal_allChannels_ly,
    ab.adobe_ordersUnassistedTotal_allChannels_wow_pct,
    ab.adobe_ordersUnassistedTotal_allChannels_yoy_pct,

    ab.adobe_ordersUnassistedTotal_paidSearch,
    ab.adobe_ordersUnassistedTotal_paidSearch_wow,
    ab.adobe_ordersUnassistedTotal_paidSearch_ly,
    ab.adobe_ordersUnassistedTotal_paidSearch_wow_pct,
    ab.adobe_ordersUnassistedTotal_paidSearch_yoy_pct,

    ab.adobe_ordersUnassistedTotal_organicSearch,
    ab.adobe_ordersUnassistedTotal_organicSearch_wow,
    ab.adobe_ordersUnassistedTotal_organicSearch_ly,
    ab.adobe_ordersUnassistedTotal_organicSearch_wow_pct,
    ab.adobe_ordersUnassistedTotal_organicSearch_yoy_pct,

    ab.adobe_ordersUnassistedTotal_direct,
    ab.adobe_ordersUnassistedTotal_direct_wow,
    ab.adobe_ordersUnassistedTotal_direct_ly,
    ab.adobe_ordersUnassistedTotal_direct_wow_pct,
    ab.adobe_ordersUnassistedTotal_direct_yoy_pct,

    ab.adobe_ordersUnassistedTotal_social,
    ab.adobe_ordersUnassistedTotal_social_wow,
    ab.adobe_ordersUnassistedTotal_social_ly,
    ab.adobe_ordersUnassistedTotal_social_wow_pct,
    ab.adobe_ordersUnassistedTotal_social_yoy_pct,

    ab.adobe_ordersUnassistedTotal_programmatic,
    ab.adobe_ordersUnassistedTotal_programmatic_wow,
    ab.adobe_ordersUnassistedTotal_programmatic_ly,
    ab.adobe_ordersUnassistedTotal_programmatic_wow_pct,
    ab.adobe_ordersUnassistedTotal_programmatic_yoy_pct,

    ab.adobe_ordersUnassistedTotal_other,
    ab.adobe_ordersUnassistedTotal_other_wow,
    ab.adobe_ordersUnassistedTotal_other_ly,
    ab.adobe_ordersUnassistedTotal_other_wow_pct,
    ab.adobe_ordersUnassistedTotal_other_yoy_pct,

    ab.adobe_ordersUnassistedPostpaid_allChannels,
    ab.adobe_ordersUnassistedPostpaid_allChannels_wow,
    ab.adobe_ordersUnassistedPostpaid_allChannels_ly,
    ab.adobe_ordersUnassistedPostpaid_allChannels_wow_pct,
    ab.adobe_ordersUnassistedPostpaid_allChannels_yoy_pct,

    ab.adobe_ordersUnassistedPostpaid_paidSearch,
    ab.adobe_ordersUnassistedPostpaid_paidSearch_wow,
    ab.adobe_ordersUnassistedPostpaid_paidSearch_ly,
    ab.adobe_ordersUnassistedPostpaid_paidSearch_wow_pct,
    ab.adobe_ordersUnassistedPostpaid_paidSearch_yoy_pct,

    ab.adobe_ordersUnassistedPostpaid_organicSearch,
    ab.adobe_ordersUnassistedPostpaid_organicSearch_wow,
    ab.adobe_ordersUnassistedPostpaid_organicSearch_ly,
    ab.adobe_ordersUnassistedPostpaid_organicSearch_wow_pct,
    ab.adobe_ordersUnassistedPostpaid_organicSearch_yoy_pct,

    ab.adobe_ordersUnassistedPostpaid_direct,
    ab.adobe_ordersUnassistedPostpaid_direct_wow,
    ab.adobe_ordersUnassistedPostpaid_direct_ly,
    ab.adobe_ordersUnassistedPostpaid_direct_wow_pct,
    ab.adobe_ordersUnassistedPostpaid_direct_yoy_pct,

    ab.adobe_ordersUnassistedPostpaid_social,
    ab.adobe_ordersUnassistedPostpaid_social_wow,
    ab.adobe_ordersUnassistedPostpaid_social_ly,
    ab.adobe_ordersUnassistedPostpaid_social_wow_pct,
    ab.adobe_ordersUnassistedPostpaid_social_yoy_pct,

    ab.adobe_ordersUnassistedPostpaid_programmatic,
    ab.adobe_ordersUnassistedPostpaid_programmatic_wow,
    ab.adobe_ordersUnassistedPostpaid_programmatic_ly,
    ab.adobe_ordersUnassistedPostpaid_programmatic_wow_pct,
    ab.adobe_ordersUnassistedPostpaid_programmatic_yoy_pct,

    ab.adobe_ordersUnassistedPostpaid_other,
    ab.adobe_ordersUnassistedPostpaid_other_wow,
    ab.adobe_ordersUnassistedPostpaid_other_ly,
    ab.adobe_ordersUnassistedPostpaid_other_wow_pct,
    ab.adobe_ordersUnassistedPostpaid_other_yoy_pct,

    ab.adobe_ordersUnassistedHsi_allChannels,
    ab.adobe_ordersUnassistedHsi_allChannels_wow,
    ab.adobe_ordersUnassistedHsi_allChannels_ly,
    ab.adobe_ordersUnassistedHsi_allChannels_wow_pct,
    ab.adobe_ordersUnassistedHsi_allChannels_yoy_pct,

    ab.adobe_ordersUnassistedHsi_paidSearch,
    ab.adobe_ordersUnassistedHsi_paidSearch_wow,
    ab.adobe_ordersUnassistedHsi_paidSearch_ly,
    ab.adobe_ordersUnassistedHsi_paidSearch_wow_pct,
    ab.adobe_ordersUnassistedHsi_paidSearch_yoy_pct,

    ab.adobe_ordersUnassistedHsi_organicSearch,
    ab.adobe_ordersUnassistedHsi_organicSearch_wow,
    ab.adobe_ordersUnassistedHsi_organicSearch_ly,
    ab.adobe_ordersUnassistedHsi_organicSearch_wow_pct,
    ab.adobe_ordersUnassistedHsi_organicSearch_yoy_pct,

    ab.adobe_ordersUnassistedHsi_direct,
    ab.adobe_ordersUnassistedHsi_direct_wow,
    ab.adobe_ordersUnassistedHsi_direct_ly,
    ab.adobe_ordersUnassistedHsi_direct_wow_pct,
    ab.adobe_ordersUnassistedHsi_direct_yoy_pct,

    ab.adobe_ordersUnassistedHsi_social,
    ab.adobe_ordersUnassistedHsi_social_wow,
    ab.adobe_ordersUnassistedHsi_social_ly,
    ab.adobe_ordersUnassistedHsi_social_wow_pct,
    ab.adobe_ordersUnassistedHsi_social_yoy_pct,

    ab.adobe_ordersUnassistedHsi_programmatic,
    ab.adobe_ordersUnassistedHsi_programmatic_wow,
    ab.adobe_ordersUnassistedHsi_programmatic_ly,
    ab.adobe_ordersUnassistedHsi_programmatic_wow_pct,
    ab.adobe_ordersUnassistedHsi_programmatic_yoy_pct,

    ab.adobe_ordersUnassistedHsi_other,
    ab.adobe_ordersUnassistedHsi_other_wow,
    ab.adobe_ordersUnassistedHsi_other_ly,
    ab.adobe_ordersUnassistedHsi_other_wow_pct,
    ab.adobe_ordersUnassistedHsi_other_yoy_pct,

    ab.adobe_ordersUnassistedByod_allChannels,
    ab.adobe_ordersUnassistedByod_allChannels_wow,
    ab.adobe_ordersUnassistedByod_allChannels_ly,
    ab.adobe_ordersUnassistedByod_allChannels_wow_pct,
    ab.adobe_ordersUnassistedByod_allChannels_yoy_pct,

    ab.adobe_ordersUnassistedByod_paidSearch,
    ab.adobe_ordersUnassistedByod_paidSearch_wow,
    ab.adobe_ordersUnassistedByod_paidSearch_ly,
    ab.adobe_ordersUnassistedByod_paidSearch_wow_pct,
    ab.adobe_ordersUnassistedByod_paidSearch_yoy_pct,

    ab.adobe_ordersUnassistedByod_organicSearch,
    ab.adobe_ordersUnassistedByod_organicSearch_wow,
    ab.adobe_ordersUnassistedByod_organicSearch_ly,
    ab.adobe_ordersUnassistedByod_organicSearch_wow_pct,
    ab.adobe_ordersUnassistedByod_organicSearch_yoy_pct,

    ab.adobe_ordersUnassistedByod_direct,
    ab.adobe_ordersUnassistedByod_direct_wow,
    ab.adobe_ordersUnassistedByod_direct_ly,
    ab.adobe_ordersUnassistedByod_direct_wow_pct,
    ab.adobe_ordersUnassistedByod_direct_yoy_pct,

    ab.adobe_ordersUnassistedByod_social,
    ab.adobe_ordersUnassistedByod_social_wow,
    ab.adobe_ordersUnassistedByod_social_ly,
    ab.adobe_ordersUnassistedByod_social_wow_pct,
    ab.adobe_ordersUnassistedByod_social_yoy_pct,

    ab.adobe_ordersUnassistedByod_programmatic,
    ab.adobe_ordersUnassistedByod_programmatic_wow,
    ab.adobe_ordersUnassistedByod_programmatic_ly,
    ab.adobe_ordersUnassistedByod_programmatic_wow_pct,
    ab.adobe_ordersUnassistedByod_programmatic_yoy_pct,

    ab.adobe_ordersUnassistedByod_other,
    ab.adobe_ordersUnassistedByod_other_wow,
    ab.adobe_ordersUnassistedByod_other_ly,
    ab.adobe_ordersUnassistedByod_other_wow_pct,
    ab.adobe_ordersUnassistedByod_other_yoy_pct,

    ab.adobe_ordersAssistedTotal_allChannels,
    ab.adobe_ordersAssistedTotal_allChannels_wow,
    ab.adobe_ordersAssistedTotal_allChannels_ly,
    ab.adobe_ordersAssistedTotal_allChannels_wow_pct,
    ab.adobe_ordersAssistedTotal_allChannels_yoy_pct,

    ab.adobe_ordersAssistedTotal_paidSearch,
    ab.adobe_ordersAssistedTotal_paidSearch_wow,
    ab.adobe_ordersAssistedTotal_paidSearch_ly,
    ab.adobe_ordersAssistedTotal_paidSearch_wow_pct,
    ab.adobe_ordersAssistedTotal_paidSearch_yoy_pct,

    ab.adobe_ordersAssistedTotal_organicSearch,
    ab.adobe_ordersAssistedTotal_organicSearch_wow,
    ab.adobe_ordersAssistedTotal_organicSearch_ly,
    ab.adobe_ordersAssistedTotal_organicSearch_wow_pct,
    ab.adobe_ordersAssistedTotal_organicSearch_yoy_pct,

    ab.adobe_ordersAssistedTotal_direct,
    ab.adobe_ordersAssistedTotal_direct_wow,
    ab.adobe_ordersAssistedTotal_direct_ly,
    ab.adobe_ordersAssistedTotal_direct_wow_pct,
    ab.adobe_ordersAssistedTotal_direct_yoy_pct,

    ab.adobe_ordersAssistedTotal_social,
    ab.adobe_ordersAssistedTotal_social_wow,
    ab.adobe_ordersAssistedTotal_social_ly,
    ab.adobe_ordersAssistedTotal_social_wow_pct,
    ab.adobe_ordersAssistedTotal_social_yoy_pct,

    ab.adobe_ordersAssistedTotal_programmatic,
    ab.adobe_ordersAssistedTotal_programmatic_wow,
    ab.adobe_ordersAssistedTotal_programmatic_ly,
    ab.adobe_ordersAssistedTotal_programmatic_wow_pct,
    ab.adobe_ordersAssistedTotal_programmatic_yoy_pct,

    ab.adobe_ordersAssistedTotal_other,
    ab.adobe_ordersAssistedTotal_other_wow,
    ab.adobe_ordersAssistedTotal_other_ly,
    ab.adobe_ordersAssistedTotal_other_wow_pct,
    ab.adobe_ordersAssistedTotal_other_yoy_pct,

    ab.adobe_ordersAssistedPostpaid_allChannels,
    ab.adobe_ordersAssistedPostpaid_allChannels_wow,
    ab.adobe_ordersAssistedPostpaid_allChannels_ly,
    ab.adobe_ordersAssistedPostpaid_allChannels_wow_pct,
    ab.adobe_ordersAssistedPostpaid_allChannels_yoy_pct,

    ab.adobe_ordersAssistedPostpaid_paidSearch,
    ab.adobe_ordersAssistedPostpaid_paidSearch_wow,
    ab.adobe_ordersAssistedPostpaid_paidSearch_ly,
    ab.adobe_ordersAssistedPostpaid_paidSearch_wow_pct,
    ab.adobe_ordersAssistedPostpaid_paidSearch_yoy_pct,

    ab.adobe_ordersAssistedPostpaid_organicSearch,
    ab.adobe_ordersAssistedPostpaid_organicSearch_wow,
    ab.adobe_ordersAssistedPostpaid_organicSearch_ly,
    ab.adobe_ordersAssistedPostpaid_organicSearch_wow_pct,
    ab.adobe_ordersAssistedPostpaid_organicSearch_yoy_pct,

    ab.adobe_ordersAssistedPostpaid_direct,
    ab.adobe_ordersAssistedPostpaid_direct_wow,
    ab.adobe_ordersAssistedPostpaid_direct_ly,
    ab.adobe_ordersAssistedPostpaid_direct_wow_pct,
    ab.adobe_ordersAssistedPostpaid_direct_yoy_pct,

    ab.adobe_ordersAssistedPostpaid_social,
    ab.adobe_ordersAssistedPostpaid_social_wow,
    ab.adobe_ordersAssistedPostpaid_social_ly,
    ab.adobe_ordersAssistedPostpaid_social_wow_pct,
    ab.adobe_ordersAssistedPostpaid_social_yoy_pct,

    ab.adobe_ordersAssistedPostpaid_programmatic,
    ab.adobe_ordersAssistedPostpaid_programmatic_wow,
    ab.adobe_ordersAssistedPostpaid_programmatic_ly,
    ab.adobe_ordersAssistedPostpaid_programmatic_wow_pct,
    ab.adobe_ordersAssistedPostpaid_programmatic_yoy_pct,

    ab.adobe_ordersAssistedPostpaid_other,
    ab.adobe_ordersAssistedPostpaid_other_wow,
    ab.adobe_ordersAssistedPostpaid_other_ly,
    ab.adobe_ordersAssistedPostpaid_other_wow_pct,
    ab.adobe_ordersAssistedPostpaid_other_yoy_pct,

    ab.adobe_ordersAssistedHsi_allChannels,
    ab.adobe_ordersAssistedHsi_allChannels_wow,
    ab.adobe_ordersAssistedHsi_allChannels_ly,
    ab.adobe_ordersAssistedHsi_allChannels_wow_pct,
    ab.adobe_ordersAssistedHsi_allChannels_yoy_pct,

    ab.adobe_ordersAssistedHsi_paidSearch,
    ab.adobe_ordersAssistedHsi_paidSearch_wow,
    ab.adobe_ordersAssistedHsi_paidSearch_ly,
    ab.adobe_ordersAssistedHsi_paidSearch_wow_pct,
    ab.adobe_ordersAssistedHsi_paidSearch_yoy_pct,

    ab.adobe_ordersAssistedHsi_organicSearch,
    ab.adobe_ordersAssistedHsi_organicSearch_wow,
    ab.adobe_ordersAssistedHsi_organicSearch_ly,
    ab.adobe_ordersAssistedHsi_organicSearch_wow_pct,
    ab.adobe_ordersAssistedHsi_organicSearch_yoy_pct,

    ab.adobe_ordersAssistedHsi_direct,
    ab.adobe_ordersAssistedHsi_direct_wow,
    ab.adobe_ordersAssistedHsi_direct_ly,
    ab.adobe_ordersAssistedHsi_direct_wow_pct,
    ab.adobe_ordersAssistedHsi_direct_yoy_pct,

    ab.adobe_ordersAssistedHsi_social,
    ab.adobe_ordersAssistedHsi_social_wow,
    ab.adobe_ordersAssistedHsi_social_ly,
    ab.adobe_ordersAssistedHsi_social_wow_pct,
    ab.adobe_ordersAssistedHsi_social_yoy_pct,

    ab.adobe_ordersAssistedHsi_programmatic,
    ab.adobe_ordersAssistedHsi_programmatic_wow,
    ab.adobe_ordersAssistedHsi_programmatic_ly,
    ab.adobe_ordersAssistedHsi_programmatic_wow_pct,
    ab.adobe_ordersAssistedHsi_programmatic_yoy_pct,

    ab.adobe_ordersAssistedHsi_other,
    ab.adobe_ordersAssistedHsi_other_wow,
    ab.adobe_ordersAssistedHsi_other_ly,
    ab.adobe_ordersAssistedHsi_other_wow_pct,
    ab.adobe_ordersAssistedHsi_other_yoy_pct,

    ab.adobe_ordersAssistedByod_allChannels,
    ab.adobe_ordersAssistedByod_allChannels_wow,
    ab.adobe_ordersAssistedByod_allChannels_ly,
    ab.adobe_ordersAssistedByod_allChannels_wow_pct,
    ab.adobe_ordersAssistedByod_allChannels_yoy_pct,

    ab.adobe_ordersAssistedByod_paidSearch,
    ab.adobe_ordersAssistedByod_paidSearch_wow,
    ab.adobe_ordersAssistedByod_paidSearch_ly,
    ab.adobe_ordersAssistedByod_paidSearch_wow_pct,
    ab.adobe_ordersAssistedByod_paidSearch_yoy_pct,

    ab.adobe_ordersAssistedByod_organicSearch,
    ab.adobe_ordersAssistedByod_organicSearch_wow,
    ab.adobe_ordersAssistedByod_organicSearch_ly,
    ab.adobe_ordersAssistedByod_organicSearch_wow_pct,
    ab.adobe_ordersAssistedByod_organicSearch_yoy_pct,

    ab.adobe_ordersAssistedByod_direct,
    ab.adobe_ordersAssistedByod_direct_wow,
    ab.adobe_ordersAssistedByod_direct_ly,
    ab.adobe_ordersAssistedByod_direct_wow_pct,
    ab.adobe_ordersAssistedByod_direct_yoy_pct,

    ab.adobe_ordersAssistedByod_social,
    ab.adobe_ordersAssistedByod_social_wow,
    ab.adobe_ordersAssistedByod_social_ly,
    ab.adobe_ordersAssistedByod_social_wow_pct,
    ab.adobe_ordersAssistedByod_social_yoy_pct,

    ab.adobe_ordersAssistedByod_programmatic,
    ab.adobe_ordersAssistedByod_programmatic_wow,
    ab.adobe_ordersAssistedByod_programmatic_ly,
    ab.adobe_ordersAssistedByod_programmatic_wow_pct,
    ab.adobe_ordersAssistedByod_programmatic_yoy_pct,

    ab.adobe_ordersAssistedByod_other,
    ab.adobe_ordersAssistedByod_other_wow,
    ab.adobe_ordersAssistedByod_other_ly,
    ab.adobe_ordersAssistedByod_other_wow_pct,
    ab.adobe_ordersAssistedByod_other_yoy_pct

FROM `prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_silver_sa360_weekly`             sa
FULL OUTER JOIN `prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_silver_gsc_weekly`            gsc
    ON sa.week_sun_to_sat = gsc.week_sun_to_sat
FULL OUTER JOIN `prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_silver_profound_weekly`       p
    ON COALESCE(sa.week_sun_to_sat, gsc.week_sun_to_sat) = p.week_sun_to_sat
FULL OUTER JOIN `prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_silver_profoundGofish_weekly` g
    ON COALESCE(sa.week_sun_to_sat, gsc.week_sun_to_sat, p.week_sun_to_sat) = g.week_sun_to_sat
FULL OUTER JOIN `prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_silver_googleTrends_weekly`   t
    ON COALESCE(sa.week_sun_to_sat, gsc.week_sun_to_sat, p.week_sun_to_sat, g.week_sun_to_sat) = t.week_sun_to_sat
FULL OUTER JOIN `prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseTms_silver_adobe_weekly`          ab
    ON COALESCE(sa.week_sun_to_sat, gsc.week_sun_to_sat, p.week_sun_to_sat, g.week_sun_to_sat, t.week_sun_to_sat) = ab.week_sun_to_sat

ORDER BY week_sun_to_sat ASC
;