/* =================================================================================================
FILE:         02_sdi_sp_dashboardPulseTms_bronze_adobeFunnel_weekly.sql   (Databricks port)
LAYER:        Stored Procedure
PROCEDURE:    sdi_sp_dashboardPulseTms_bronze_adobeFunnel_weekly

PURPOSE:
  Creates/refreshes physical table sdi_tbl_dashboardPulseTms_bronze_adobeFunnel_weekly.
  Called as part of the weekly refresh.

CHANNEL GROUPS (standard vocabulary):
  'All Channels' | 'Paid Search' | 'Paid Social' | 'Organic Search' |
  'Direct' | 'Programmatic' | 'Other'

PORTING NOTES (BQ -> Databricks), applies to this file only:
  - Adobe/Improvado raw source tables now live under prd_dbi_analytics.improvado.<table>
    (was prj-dbi-prd-1.ds_dbi_improvado_master.<table> in BigQuery) -- per your confirmation.
  - PARSE_DATE('%Y%m%d', date_yyyymmdd) -> to_date(date_yyyymmdd, 'yyyyMMdd')
  - DATE_ADD(x, INTERVAL 6 DAY)         -> date_add(x, 6)
  - SAFE_CAST(x AS FLOAT64)             -> TRY_CAST(x AS DOUBLE)
  - QUALIFY ROW_NUMBER() ... = 1        -> unchanged; Databricks SQL supports QUALIFY natively (DBR 10.4 LTS+)
  - STRING_AGG(DISTINCT x, ', ' ORDER BY x) -> array_join(sort_array(collect_set(x)), ', ')
    ⚠ REVISED after hitting a real Databricks bug: this originally used
    string_agg(DISTINCT x, ', ') WITHIN GROUP (ORDER BY x), which is the more direct syntactic
    equivalent of BQ's STRING_AGG. That works fine with ONE such call in a query, but this
    procedure has TWO (source_tables_used and filenames_used, over different columns) in the
    same GROUP BY. With two different-column DISTINCT string_agg calls in one aggregate,
    Spark's RewriteDistinctAggregates optimizer rule throws a ClassCastException inside
    ListAgg.withNewChildrenInternal (AttributeReference cannot be cast to SortOrder) --
    confirmed against DBR's actual execution, not just a syntax guess. collect_set() +
    sort_array() + array_join() produces the identical result (deduplicated, sorted,
    comma-joined) using older, more mature Spark functions that don't go through that rewrite
    path, so it sidesteps the bug entirely rather than working around it.
  - MAX(IF(cond, val, NULL))            -> unchanged; Databricks SQL supports IF() as a CASE WHEN alias
  - OPTIONS(strict_mode=false)          -> dropped; BQ-scripting-only setting, no Databricks equivalent
  - CREATE TABLE ... PARTITION BY x CLUSTER BY y ... OPTIONS(description=...)
                                         -> CREATE TABLE ... CLUSTER BY (x, y) COMMENT '...'
                                            (Databricks Liquid Clustering supersedes the BQ partition+cluster split)
  - CREATE OR REPLACE PROCEDURE ... BEGIN...END -> needs explicit LANGUAGE SQL clause

CHANGE LOG:
  - 'Social' renamed to 'Paid Social' throughout to align with standard channel_group vocabulary.
================================================================================================= */

CREATE OR REPLACE PROCEDURE
  prdrzranalytics.lab42.sdi_sp_dashboardPulseTms_bronze_adobeFunnel_weekly()
LANGUAGE SQL
AS
BEGIN

  CREATE OR REPLACE TABLE
    prdrzranalytics.lab42.sdi_tbl_dashboardPulseTms_bronze_adobeFunnel_weekly
  USING DELTA
  CLUSTER BY (week_sun_sat, channel_group)
  COMMENT 'PulseTMS Bronze — Adobe UPV funnel metrics. Wide format, one row per week_sun_sat x channel_group. Clustered by week_sun_sat, channel_group. Refreshed weekly via sdi_sp_dashboardPulseTms_bronze_adobeFunnel_weekly. Channel groups: All Channels, Paid Search, Paid Social, Organic Search, Direct, Programmatic, Other.'
  AS
  WITH RawUnion AS (

    /* ======= ALL CHANNELS ======= */
    SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6) AS week_sun_sat, 'All Channels' AS channel_group, 'upvPostpaid' AS metric_name, TRY_CAST(visitors AS DOUBLE) AS metric_value, 'sdi_raw_adobe_pp_uvnb_all_uvnb_postpaid_flow_visitors_weekly_tmo' AS source_table, __insert_date AS insert_date, File_Load_datetime AS file_load_datetime, Filename AS filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_uvnb_postpaid_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'upvHsi',                   TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_all_uvnb_hsi_flow_visitors_weekly_tmo',                __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_uvnb_hsi_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'upvByod',                  TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_all_uvnb_byod_flow_visitors_weekly_tmo',               __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_uvnb_byod_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'upvFlowTotal',             TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_all_flow_total_visitors_weekly_tmo',                   __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_flow_total_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'upvTotalAdobe',            TRY_CAST(visitors AS DOUBLE), 'sdi_raw_pp_pro_uvnb_weekly_tmo',                                            __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_pp_pro_uvnb_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'cartstartPostpaid',        TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_all_postpaid_cartstart_visits_weekly_tmo',             __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_postpaid_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'cartstartHsi',             TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_all_hsi_cartstart_visits_weekly_tmo',                 __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_hsi_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'cartstartByod',            TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_all_byod_cartstart_visits_weekly_tmo',                __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_byod_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'ordersUnassistedPostpaid', TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_all_postpaid_order_weekly_tmo',                       __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_postpaid_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'ordersUnassistedHsi',      TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_all_hsi_order_weekly_tmo',                            __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_hsi_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'ordersUnassistedByod',     TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_all_byod_order_weekly_tmo',                           __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_byod_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'ordersAssistedPostpaid',   TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_all_postpaid_order_assisted_weekly_tmo',              __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_postpaid_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'ordersAssistedHsi',        TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_all_hsi_order_assisted_weekly_tmo',                   __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_hsi_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'All Channels', 'ordersAssistedByod',       TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_all_byod_order_assisted_weekly_tmo',                  __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_all_byod_order_assisted_weekly_tmo

    /* ======= DIRECT ======= */
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'upvPostpaid',             TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_direct_uvnb_postpaid_flow_visitors_weekly_tmo',        __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_uvnb_postpaid_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'upvHsi',                  TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_direct_uvnb_hsi_flow_visitors_weekly_tmo',             __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_uvnb_hsi_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'upvByod',                 TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_direct_uvnb_byod_flow_visitors_weekly_tmo',            __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_uvnb_byod_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'upvFlowTotal',            TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_direct_flow_total_visitors_weekly_tmo',                __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_flow_total_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'upvTotalAdobe',           TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_direct_uvnb_visitors_weekly_tmo',                      __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_uvnb_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'cartstartPostpaid',       TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_direct_postpaid_cartstart_visits_weekly_tmo',          __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_postpaid_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'cartstartHsi',            TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_direct_hsi_cartstart_visits_weekly_tmo',               __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_hsi_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'cartstartByod',           TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_direct_byod_cartstart_visits_weekly_tmo',              __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_byod_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'ordersUnassistedPostpaid',TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_direct_postpaid_order_weekly_tmo',                     __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_postpaid_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'ordersUnassistedHsi',     TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_direct_hsi_order_weekly_tmo',                          __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_hsi_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'ordersUnassistedByod',    TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_direct_byod_order_weekly_tmo',                         __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_byod_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'ordersAssistedPostpaid',  TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_direct_postpaid_order_assisted_weekly_tmo',            __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_postpaid_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'ordersAssistedHsi',       TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_direct_hsi_order_assisted_weekly_tmo',                 __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_hsi_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Direct', 'ordersAssistedByod',      TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_direct_byod_order_assisted_weekly_tmo',                __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_direct_byod_order_assisted_weekly_tmo

    /* ======= ORGANIC SEARCH ======= */
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'upvPostpaid',             TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_organic_search_uvnb_postpaid_flow_visitors_weekly_tmo',  __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_uvnb_postpaid_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'upvHsi',                  TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_organic_search_uvnb_hsi_flow_visitors_weekly_tmo',       __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_uvnb_hsi_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'upvByod',                 TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_organic_search_uvnb_byod_flow_visitors_weekly_tmo',      __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_uvnb_byod_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'upvFlowTotal',            TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_organic_search_flow_total_visitors_weekly_tmo',         __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_flow_total_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'upvTotalAdobe',           TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_organic_search_uvnb_visitors_weekly_tmo',               __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_uvnb_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'cartstartPostpaid',       TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_organic_search_postpaid_cartstart_visits_weekly_tmo',   __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_postpaid_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'cartstartHsi',            TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_organic_search_hsi_cartstart_visits_weekly_tmo',        __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_hsi_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'cartstartByod',           TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_organic_search_byod_cartstart_visits_weekly_tmo',       __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_byod_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'ordersUnassistedPostpaid',TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_organic_search_postpaid_order_weekly_tmo',              __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_postpaid_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'ordersUnassistedHsi',     TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_organic_search_hsi_order_weekly_tmo',                   __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_hsi_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'ordersUnassistedByod',    TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_organic_search_byod_order_weekly_tmo',                  __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_byod_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'ordersAssistedPostpaid',  TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_organic_search_postpaid_order_assisted_weekly_tmo',     __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_postpaid_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'ordersAssistedHsi',       TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_organic_search_hsi_order_assisted_weekly_tmo',          __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_hsi_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Organic Search', 'ordersAssistedByod',      TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_organic_search_byod_order_assisted_weekly_tmo',         __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_organic_search_byod_order_assisted_weekly_tmo

    /* ======= OTHER ======= */
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'upvPostpaid',             TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_other_uvnb_postpaid_flow_visitors_weekly_tmo',  __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_uvnb_postpaid_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'upvHsi',                  TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_other_uvnb_hsi_flow_visitors_weekly_tmo',       __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_uvnb_hsi_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'upvByod',                 TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_other_uvnb_byod_flow_visitors_weekly_tmo',      __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_uvnb_byod_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'upvFlowTotal',            TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_other_flow_total_visitors_weekly_tmo',          __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_flow_total_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'upvTotalAdobe',           TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_other_uvnb_visitors_weekly_tmo',                __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_uvnb_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'cartstartPostpaid',       TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_other_postpaid_cartstart_visits_weekly_tmo',    __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_postpaid_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'cartstartHsi',            TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_other_hsi_cartstart_visits_weekly_tmo',         __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_hsi_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'cartstartByod',           TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_other_byod_cartstart_visits_weekly_tmo',        __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_byod_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'ordersUnassistedPostpaid',TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_other_postpaid_order_weekly_tmo',               __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_postpaid_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'ordersUnassistedHsi',     TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_other_hsi_order_weekly_tmo',                    __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_hsi_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'ordersUnassistedByod',    TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_other_byod_order_weekly_tmo',                   __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_byod_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'ordersAssistedPostpaid',  TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_other_postpaid_order_assisted_weekly_tmo',      __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_postpaid_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'ordersAssistedHsi',       TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_other_hsi_order_assisted_weekly_tmo',           __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_hsi_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Other', 'ordersAssistedByod',      TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_other_byod_order_assisted_weekly_tmo',          __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_other_byod_order_assisted_weekly_tmo

    /* ======= PAID SEARCH ======= */
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'upvPostpaid',             TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_paid_search_uvnb_postpaid_flow_visitors_weekly_tmo',  __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_uvnb_postpaid_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'upvHsi',                  TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_paid_search_uvnb_hsi_flow_visitors_weekly_tmo',       __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_uvnb_hsi_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'upvByod',                 TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_paid_search_uvnb_byod_flow_visitors_weekly_tmo',      __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_uvnb_byod_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'upvFlowTotal',            TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_paid_search_flow_total_visitors_weekly_tmo',          __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_flow_total_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'upvTotalAdobe',           TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_paid_search_uvnb_visitors_weekly_tmo',                __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_uvnb_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'cartstartPostpaid',       TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_paid_search_postpaid_cartstart_visits_weekly_tmo',    __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_postpaid_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'cartstartHsi',            TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_paid_search_hsi_cartstart_visits_weekly_tmo',         __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_hsi_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'cartstartByod',           TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_paid_search_byod_cartstart_visits_weekly_tmo',        __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_byod_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'ordersUnassistedPostpaid',TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_paid_search_postpaid_order_weekly_tmo',               __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_postpaid_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'ordersUnassistedHsi',     TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_paid_search_hsi_order_weekly_tmo',                    __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_hsi_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'ordersUnassistedByod',    TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_paid_search_byod_order_weekly_tmo',                   __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_byod_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'ordersAssistedPostpaid',  TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_paid_search_postpaid_order_assisted_weekly_tmo',      __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_postpaid_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'ordersAssistedHsi',       TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_paid_search_hsi_order_assisted_weekly_tmo',           __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_hsi_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Search', 'ordersAssistedByod',      TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_paid_search_byod_order_assisted_weekly_tmo',          __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_paid_search_byod_order_assisted_weekly_tmo

    /* ======= PAID SOCIAL ======= */
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'upvPostpaid',             TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_social_uvnb_postpaid_flow_visitors_weekly_tmo',  __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_uvnb_postpaid_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'upvHsi',                  TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_social_uvnb_hsi_flow_visitors_weekly_tmo',       __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_uvnb_hsi_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'upvByod',                 TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_social_uvnb_byod_flow_visitors_weekly_tmo',      __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_uvnb_byod_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'upvFlowTotal',            TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_social_flow_total_visitors_weekly_tmo',          __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_flow_total_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'upvTotalAdobe',           TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_social_uvnb_visitors_weekly_tmo',                __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_uvnb_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'cartstartPostpaid',       TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_social_postpaid_cartstart_visits_weekly_tmo',    __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_postpaid_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'cartstartHsi',            TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_social_hsi_cartstart_visits_weekly_tmo',         __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_hsi_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'cartstartByod',           TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_social_byod_cartstart_visits_weekly_tmo',        __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_byod_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'ordersUnassistedPostpaid',TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_social_postpaid_order_weekly_tmo',               __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_postpaid_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'ordersUnassistedHsi',     TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_social_hsi_order_weekly_tmo',                    __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_hsi_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'ordersUnassistedByod',    TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_social_byod_order_weekly_tmo',                   __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_byod_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'ordersAssistedPostpaid',  TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_social_postpaid_order_assisted_weekly_tmo',      __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_postpaid_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'ordersAssistedHsi',       TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_social_hsi_order_assisted_weekly_tmo',           __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_hsi_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Paid Social', 'ordersAssistedByod',      TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_social_byod_order_assisted_weekly_tmo',          __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_social_byod_order_assisted_weekly_tmo

    /* ======= PROGRAMMATIC ======= */
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'upvPostpaid',             TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_programmatic_uvnb_postpaid_flow_visitors_weekly_tmo',  __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_uvnb_postpaid_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'upvHsi',                  TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_programmatic_uvnb_hsi_flow_visitors_weekly_tmo',       __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_uvnb_hsi_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'upvByod',                 TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_programmatic_uvnb_byod_flow_visitors_weekly_tmo',      __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_uvnb_byod_flow_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'upvFlowTotal',            TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_programmatic_flow_total_visitors_weekly_tmo',          __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_flow_total_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'upvTotalAdobe',           TRY_CAST(visitors AS DOUBLE), 'sdi_raw_adobe_pp_uvnb_programmatic_uvnb_visitors_weekly_tmo',                __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_uvnb_visitors_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'cartstartPostpaid',       TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_programmatic_postpaid_cartstart_visits_weekly_tmo',    __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_postpaid_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'cartstartHsi',            TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_programmatic_hsi_cartstart_visits_weekly_tmo',         __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_hsi_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'cartstartByod',           TRY_CAST(visits AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_programmatic_byod_cartstart_visits_weekly_tmo',        __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_byod_cartstart_visits_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'ordersUnassistedPostpaid',TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_programmatic_postpaid_order_weekly_tmo',               __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_postpaid_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'ordersUnassistedHsi',     TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_programmatic_hsi_order_weekly_tmo',                    __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_hsi_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'ordersUnassistedByod',    TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_programmatic_byod_order_weekly_tmo',                   __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_byod_order_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'ordersAssistedPostpaid',  TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_programmatic_postpaid_order_assisted_weekly_tmo',      __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_postpaid_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'ordersAssistedHsi',       TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_programmatic_hsi_order_assisted_weekly_tmo',           __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_hsi_order_assisted_weekly_tmo
    UNION ALL SELECT date_add(to_date(date_yyyymmdd, 'yyyyMMdd'), 6), 'Programmatic', 'ordersAssistedByod',      TRY_CAST(orders AS DOUBLE),   'sdi_raw_adobe_pp_uvnb_programmatic_byod_order_assisted_weekly_tmo',          __insert_date, File_Load_datetime, Filename FROM prd_dbi_analytics.improvado.sdi_raw_adobe_pp_uvnb_programmatic_byod_order_assisted_weekly_tmo
  ),
  Deduped AS (
    SELECT *
    FROM RawUnion
    QUALIFY ROW_NUMBER() OVER (
      PARTITION BY week_sun_sat, channel_group, metric_name, source_table
      ORDER BY file_load_datetime DESC, filename DESC, insert_date DESC
    ) = 1
  )
  SELECT
    week_sun_sat,
    channel_group,
    MAX(IF(metric_name = 'upvPostpaid',              metric_value, NULL)) AS upvPostpaid,
    MAX(IF(metric_name = 'upvHsi',                   metric_value, NULL)) AS upvHsi,
    MAX(IF(metric_name = 'upvByod',                  metric_value, NULL)) AS upvByod,
    MAX(IF(metric_name = 'upvFlowTotal',             metric_value, NULL)) AS upvFlowTotal,
    MAX(IF(metric_name = 'upvTotalAdobe',            metric_value, NULL)) AS upvTotalAdobe,
    MAX(IF(metric_name = 'cartstartPostpaid',        metric_value, NULL)) AS cartstartPostpaid,
    MAX(IF(metric_name = 'cartstartHsi',             metric_value, NULL)) AS cartstartHsi,
    MAX(IF(metric_name = 'cartstartByod',            metric_value, NULL)) AS cartstartByod,
    MAX(IF(metric_name = 'ordersUnassistedPostpaid', metric_value, NULL)) AS ordersUnassistedPostpaid,
    MAX(IF(metric_name = 'ordersUnassistedHsi',      metric_value, NULL)) AS ordersUnassistedHsi,
    MAX(IF(metric_name = 'ordersUnassistedByod',     metric_value, NULL)) AS ordersUnassistedByod,
    MAX(IF(metric_name = 'ordersAssistedPostpaid',   metric_value, NULL)) AS ordersAssistedPostpaid,
    MAX(IF(metric_name = 'ordersAssistedHsi',        metric_value, NULL)) AS ordersAssistedHsi,
    MAX(IF(metric_name = 'ordersAssistedByod',       metric_value, NULL)) AS ordersAssistedByod,
    array_join(sort_array(collect_set(source_table)), ', ')              AS source_tables_used,
    MAX(file_load_datetime)                                               AS max_file_load_datetime,
    array_join(sort_array(collect_set(filename)), ', ')                  AS filenames_used
  FROM Deduped
  GROUP BY week_sun_sat, channel_group;

END;