/* =================================================================================================
FILE:         07_vw_sdi_pulseByod_silver_adobeByodEntryPages_weekly.sql
LAYER:        Silver View
DATASET:      prj-dbi-prd-1.ds_dbi_digitalmedia_automation
VIEW NAME:    vw_sdi_pulseByod_silver_adobeByodEntryPages_weekly

SOURCE:
  prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_adobe_silver_byodFlowEntryPagesByChannelGroupsPlusAll_Weekly

DESTINATION:
  prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseByod_silver_adobeByodEntryPages_weekly

PURPOSE:
  Silver view for Adobe Analytics BYOD funnel entry page metrics.
  Outputs a WIDE table — one row per week_sun_to_sat.
  Pivots ChannelGroup rows into columns so each channel
  becomes its own set of prefixed metric columns.
  Applies WoW/LY comparisons and max_data_date.

  Entry page metrics track where BYOD visitors entered the site:
    byodUvnbVisitors                 — total unique non-bounced BYOD visitors
    byodEntryByodPageVisitors        — entered on BYOD page
    byodEntryHomePageVisitors        — entered on homepage
    byodEntryDevicePageVisitors      — entered on device page
    byodEntryPlansPageVisitors       — entered on plans page
    byodEntryOtherPageVisitors       — entered on other page (NEW: otherpage2 only — true residual)
    byodEntryStorePageVisitors       — entered on store page (NEW)
    byodEntryByodLandingPageVisitors — entered on BYOD landing page (NEW)
    byodEntryOffersSwitchVisitors    — entered on offers/switch page (NEW)

  -- OLD OTHER reference (not a live column):
  -- Old Other = byodEntryStorePageVisitors + byodEntryByodLandingPageVisitors
  --           + byodEntryOffersSwitchVisitors + byodEntryOtherPageVisitors (otherpage2)
  -- Previously sourced from: sdi_raw_adobe_byod_flow_{channel}_byod_entry_otherpage_visitors_weekly_tmo

BUSINESS GRAIN:
  One row per week_sun_to_sat

SOURCE GRAIN:
  One row per WeekSunSat + ChannelGroup
  ChannelGroup values: ALL, PAID SEARCH, ORGANIC SEARCH,
                       DIRECT, SOCIAL, PROGRAMMATIC, OTHER

COLUMN NAMING CONVENTION:
  adobe_{metric}_{channel}
  Channel suffixes: allChannels, paidSearch, organicSearch, direct, social, programmatic, other

BUSINESS LOGIC:
  - No derived/ratio metrics — all metrics are raw visitor counts
  - WoW: self-join on week_sun_to_sat - 7 days (gap-safe)
  - LY:  self-join on custom_week_num - 52 (gap-safe, Sun-to-Sat anchor)
  - wow_pct / yoy_pct as decimals — NULL when prior NULL or 0
  - max_data_date: latest week_sun_to_sat with any non-null metric

CUSTOM WEEK NUMBER:
  custom_week_num = DATE_DIFF(DATE_SUB(week_sun_to_sat, INTERVAL 6 DAY), DATE '2023-01-01', WEEK)
  LY match: current.custom_week_num - prior.custom_week_num = 52

DOWNSTREAM:
  Gold Wide : vw_sdi_pulseByod_gold_unified_wide
  Gold Long : vw_sdi_pulseByod_gold_unified_long

CHANGES:
  2026-06-XX — Other segregation:
               byodEntryOtherPageVisitors redefined to otherpage2 only (from upstream Bronze)
               Added byodEntryStorePageVisitors, byodEntryByodLandingPageVisitors,
               byodEntryOffersSwitchVisitors across all 7 channels with full WoW/LY/pct treatment
================================================================================================= */

CREATE OR REPLACE VIEW `prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseByod_silver_adobeByodEntryPages_weekly`
AS

WITH base AS (
  SELECT
    WeekSunSat                         AS week_sun_to_sat,
    ChannelGroup,
    ByodUvnbVisitors,
    ByodEntryByodPageVisitors,
    ByodEntryHomePageVisitors,
    ByodEntryDevicePageVisitors,
    ByodEntryPlansPageVisitors,
    ByodEntryOtherPageVisitors,
    ByodEntryStorePageVisitors,          -- NEW
    ByodEntryByodLandingPageVisitors,    -- NEW
    ByodEntryOffersSwitchVisitors        -- NEW
  FROM `prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_adobe_silver_byodFlowEntryPagesByChannelGroupsPlusAll_Weekly`
),

pivoted AS (
  SELECT
    week_sun_to_sat,
    -- ALL CHANNELS
    MAX(CASE WHEN ChannelGroup = 'ALL CHANNELS' THEN ByodUvnbVisitors END) AS adobe_byodUvnbVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'ALL CHANNELS' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'ALL CHANNELS' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'ALL CHANNELS' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'ALL CHANNELS' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'ALL CHANNELS' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'ALL CHANNELS' THEN ByodEntryStorePageVisitors END) AS adobe_byodEntryStorePageVisitors_allChannels,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'ALL CHANNELS' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_allChannels,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'ALL CHANNELS' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_allChannels,  -- NEW
    -- PAID SEARCH
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH' THEN ByodUvnbVisitors END) AS adobe_byodUvnbVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH' THEN ByodEntryStorePageVisitors END) AS adobe_byodEntryStorePageVisitors_paidSearch,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_paidSearch,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_paidSearch,  -- NEW
    -- ORGANIC SEARCH
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodUvnbVisitors END) AS adobe_byodUvnbVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodEntryStorePageVisitors END) AS adobe_byodEntryStorePageVisitors_organicSearch,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_organicSearch,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_organicSearch,  -- NEW
    -- DIRECT
    MAX(CASE WHEN ChannelGroup = 'DIRECT' THEN ByodUvnbVisitors END) AS adobe_byodUvnbVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'DIRECT' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'DIRECT' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'DIRECT' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'DIRECT' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'DIRECT' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'DIRECT' THEN ByodEntryStorePageVisitors END) AS adobe_byodEntryStorePageVisitors_direct,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'DIRECT' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_direct,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'DIRECT' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_direct,  -- NEW
    -- SOCIAL
    MAX(CASE WHEN ChannelGroup = 'SOCIAL' THEN ByodUvnbVisitors END) AS adobe_byodUvnbVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'SOCIAL' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'SOCIAL' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'SOCIAL' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'SOCIAL' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'SOCIAL' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'SOCIAL' THEN ByodEntryStorePageVisitors END) AS adobe_byodEntryStorePageVisitors_social,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'SOCIAL' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_social,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'SOCIAL' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_social,  -- NEW
    -- PROGRAMMATIC
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC' THEN ByodUvnbVisitors END) AS adobe_byodUvnbVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC' THEN ByodEntryStorePageVisitors END) AS adobe_byodEntryStorePageVisitors_programmatic,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_programmatic,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_programmatic,  -- NEW
    -- OTHER
    MAX(CASE WHEN ChannelGroup = 'OTHER' THEN ByodUvnbVisitors END) AS adobe_byodUvnbVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'OTHER' THEN ByodEntryByodPageVisitors END) AS adobe_byodEntryByodPageVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'OTHER' THEN ByodEntryHomePageVisitors END) AS adobe_byodEntryHomePageVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'OTHER' THEN ByodEntryDevicePageVisitors END) AS adobe_byodEntryDevicePageVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'OTHER' THEN ByodEntryPlansPageVisitors END) AS adobe_byodEntryPlansPageVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'OTHER' THEN ByodEntryOtherPageVisitors END) AS adobe_byodEntryOtherPageVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'OTHER' THEN ByodEntryStorePageVisitors END) AS adobe_byodEntryStorePageVisitors_other,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'OTHER' THEN ByodEntryByodLandingPageVisitors END) AS adobe_byodEntryByodLandingPageVisitors_other,  -- NEW
    MAX(CASE WHEN ChannelGroup = 'OTHER' THEN ByodEntryOffersSwitchVisitors END) AS adobe_byodEntryOffersSwitchVisitors_other,  -- NEW
  FROM base
  GROUP BY week_sun_to_sat
),

with_week_num AS (
  SELECT
    *,
    DATE_DIFF(DATE_SUB(week_sun_to_sat, INTERVAL 6 DAY), DATE '2023-01-01', WEEK) AS custom_week_num
  FROM pivoted
),

with_comparisons AS (
  SELECT
    c.week_sun_to_sat, c.custom_week_num,
    -- ALL CHANNELS
    c.adobe_byodUvnbVisitors_allChannels, w.adobe_byodUvnbVisitors_allChannels AS adobe_byodUvnbVisitors_allChannels_wow, l.adobe_byodUvnbVisitors_allChannels AS adobe_byodUvnbVisitors_allChannels_ly,
    c.adobe_byodEntryByodPageVisitors_allChannels, w.adobe_byodEntryByodPageVisitors_allChannels AS adobe_byodEntryByodPageVisitors_allChannels_wow, l.adobe_byodEntryByodPageVisitors_allChannels AS adobe_byodEntryByodPageVisitors_allChannels_ly,
    c.adobe_byodEntryHomePageVisitors_allChannels, w.adobe_byodEntryHomePageVisitors_allChannels AS adobe_byodEntryHomePageVisitors_allChannels_wow, l.adobe_byodEntryHomePageVisitors_allChannels AS adobe_byodEntryHomePageVisitors_allChannels_ly,
    c.adobe_byodEntryDevicePageVisitors_allChannels, w.adobe_byodEntryDevicePageVisitors_allChannels AS adobe_byodEntryDevicePageVisitors_allChannels_wow, l.adobe_byodEntryDevicePageVisitors_allChannels AS adobe_byodEntryDevicePageVisitors_allChannels_ly,
    c.adobe_byodEntryPlansPageVisitors_allChannels, w.adobe_byodEntryPlansPageVisitors_allChannels AS adobe_byodEntryPlansPageVisitors_allChannels_wow, l.adobe_byodEntryPlansPageVisitors_allChannels AS adobe_byodEntryPlansPageVisitors_allChannels_ly,
    c.adobe_byodEntryOtherPageVisitors_allChannels, w.adobe_byodEntryOtherPageVisitors_allChannels AS adobe_byodEntryOtherPageVisitors_allChannels_wow, l.adobe_byodEntryOtherPageVisitors_allChannels AS adobe_byodEntryOtherPageVisitors_allChannels_ly,
    c.adobe_byodEntryStorePageVisitors_allChannels, w.adobe_byodEntryStorePageVisitors_allChannels AS adobe_byodEntryStorePageVisitors_allChannels_wow, l.adobe_byodEntryStorePageVisitors_allChannels AS adobe_byodEntryStorePageVisitors_allChannels_ly,
    c.adobe_byodEntryByodLandingPageVisitors_allChannels, w.adobe_byodEntryByodLandingPageVisitors_allChannels AS adobe_byodEntryByodLandingPageVisitors_allChannels_wow, l.adobe_byodEntryByodLandingPageVisitors_allChannels AS adobe_byodEntryByodLandingPageVisitors_allChannels_ly,
    c.adobe_byodEntryOffersSwitchVisitors_allChannels, w.adobe_byodEntryOffersSwitchVisitors_allChannels AS adobe_byodEntryOffersSwitchVisitors_allChannels_wow, l.adobe_byodEntryOffersSwitchVisitors_allChannels AS adobe_byodEntryOffersSwitchVisitors_allChannels_ly,
    -- PAID SEARCH
    c.adobe_byodUvnbVisitors_paidSearch, w.adobe_byodUvnbVisitors_paidSearch AS adobe_byodUvnbVisitors_paidSearch_wow, l.adobe_byodUvnbVisitors_paidSearch AS adobe_byodUvnbVisitors_paidSearch_ly,
    c.adobe_byodEntryByodPageVisitors_paidSearch, w.adobe_byodEntryByodPageVisitors_paidSearch AS adobe_byodEntryByodPageVisitors_paidSearch_wow, l.adobe_byodEntryByodPageVisitors_paidSearch AS adobe_byodEntryByodPageVisitors_paidSearch_ly,
    c.adobe_byodEntryHomePageVisitors_paidSearch, w.adobe_byodEntryHomePageVisitors_paidSearch AS adobe_byodEntryHomePageVisitors_paidSearch_wow, l.adobe_byodEntryHomePageVisitors_paidSearch AS adobe_byodEntryHomePageVisitors_paidSearch_ly,
    c.adobe_byodEntryDevicePageVisitors_paidSearch, w.adobe_byodEntryDevicePageVisitors_paidSearch AS adobe_byodEntryDevicePageVisitors_paidSearch_wow, l.adobe_byodEntryDevicePageVisitors_paidSearch AS adobe_byodEntryDevicePageVisitors_paidSearch_ly,
    c.adobe_byodEntryPlansPageVisitors_paidSearch, w.adobe_byodEntryPlansPageVisitors_paidSearch AS adobe_byodEntryPlansPageVisitors_paidSearch_wow, l.adobe_byodEntryPlansPageVisitors_paidSearch AS adobe_byodEntryPlansPageVisitors_paidSearch_ly,
    c.adobe_byodEntryOtherPageVisitors_paidSearch, w.adobe_byodEntryOtherPageVisitors_paidSearch AS adobe_byodEntryOtherPageVisitors_paidSearch_wow, l.adobe_byodEntryOtherPageVisitors_paidSearch AS adobe_byodEntryOtherPageVisitors_paidSearch_ly,
    c.adobe_byodEntryStorePageVisitors_paidSearch, w.adobe_byodEntryStorePageVisitors_paidSearch AS adobe_byodEntryStorePageVisitors_paidSearch_wow, l.adobe_byodEntryStorePageVisitors_paidSearch AS adobe_byodEntryStorePageVisitors_paidSearch_ly,
    c.adobe_byodEntryByodLandingPageVisitors_paidSearch, w.adobe_byodEntryByodLandingPageVisitors_paidSearch AS adobe_byodEntryByodLandingPageVisitors_paidSearch_wow, l.adobe_byodEntryByodLandingPageVisitors_paidSearch AS adobe_byodEntryByodLandingPageVisitors_paidSearch_ly,
    c.adobe_byodEntryOffersSwitchVisitors_paidSearch, w.adobe_byodEntryOffersSwitchVisitors_paidSearch AS adobe_byodEntryOffersSwitchVisitors_paidSearch_wow, l.adobe_byodEntryOffersSwitchVisitors_paidSearch AS adobe_byodEntryOffersSwitchVisitors_paidSearch_ly,
    -- ORGANIC SEARCH
    c.adobe_byodUvnbVisitors_organicSearch, w.adobe_byodUvnbVisitors_organicSearch AS adobe_byodUvnbVisitors_organicSearch_wow, l.adobe_byodUvnbVisitors_organicSearch AS adobe_byodUvnbVisitors_organicSearch_ly,
    c.adobe_byodEntryByodPageVisitors_organicSearch, w.adobe_byodEntryByodPageVisitors_organicSearch AS adobe_byodEntryByodPageVisitors_organicSearch_wow, l.adobe_byodEntryByodPageVisitors_organicSearch AS adobe_byodEntryByodPageVisitors_organicSearch_ly,
    c.adobe_byodEntryHomePageVisitors_organicSearch, w.adobe_byodEntryHomePageVisitors_organicSearch AS adobe_byodEntryHomePageVisitors_organicSearch_wow, l.adobe_byodEntryHomePageVisitors_organicSearch AS adobe_byodEntryHomePageVisitors_organicSearch_ly,
    c.adobe_byodEntryDevicePageVisitors_organicSearch, w.adobe_byodEntryDevicePageVisitors_organicSearch AS adobe_byodEntryDevicePageVisitors_organicSearch_wow, l.adobe_byodEntryDevicePageVisitors_organicSearch AS adobe_byodEntryDevicePageVisitors_organicSearch_ly,
    c.adobe_byodEntryPlansPageVisitors_organicSearch, w.adobe_byodEntryPlansPageVisitors_organicSearch AS adobe_byodEntryPlansPageVisitors_organicSearch_wow, l.adobe_byodEntryPlansPageVisitors_organicSearch AS adobe_byodEntryPlansPageVisitors_organicSearch_ly,
    c.adobe_byodEntryOtherPageVisitors_organicSearch, w.adobe_byodEntryOtherPageVisitors_organicSearch AS adobe_byodEntryOtherPageVisitors_organicSearch_wow, l.adobe_byodEntryOtherPageVisitors_organicSearch AS adobe_byodEntryOtherPageVisitors_organicSearch_ly,
    c.adobe_byodEntryStorePageVisitors_organicSearch, w.adobe_byodEntryStorePageVisitors_organicSearch AS adobe_byodEntryStorePageVisitors_organicSearch_wow, l.adobe_byodEntryStorePageVisitors_organicSearch AS adobe_byodEntryStorePageVisitors_organicSearch_ly,
    c.adobe_byodEntryByodLandingPageVisitors_organicSearch, w.adobe_byodEntryByodLandingPageVisitors_organicSearch AS adobe_byodEntryByodLandingPageVisitors_organicSearch_wow, l.adobe_byodEntryByodLandingPageVisitors_organicSearch AS adobe_byodEntryByodLandingPageVisitors_organicSearch_ly,
    c.adobe_byodEntryOffersSwitchVisitors_organicSearch, w.adobe_byodEntryOffersSwitchVisitors_organicSearch AS adobe_byodEntryOffersSwitchVisitors_organicSearch_wow, l.adobe_byodEntryOffersSwitchVisitors_organicSearch AS adobe_byodEntryOffersSwitchVisitors_organicSearch_ly,
    -- DIRECT
    c.adobe_byodUvnbVisitors_direct, w.adobe_byodUvnbVisitors_direct AS adobe_byodUvnbVisitors_direct_wow, l.adobe_byodUvnbVisitors_direct AS adobe_byodUvnbVisitors_direct_ly,
    c.adobe_byodEntryByodPageVisitors_direct, w.adobe_byodEntryByodPageVisitors_direct AS adobe_byodEntryByodPageVisitors_direct_wow, l.adobe_byodEntryByodPageVisitors_direct AS adobe_byodEntryByodPageVisitors_direct_ly,
    c.adobe_byodEntryHomePageVisitors_direct, w.adobe_byodEntryHomePageVisitors_direct AS adobe_byodEntryHomePageVisitors_direct_wow, l.adobe_byodEntryHomePageVisitors_direct AS adobe_byodEntryHomePageVisitors_direct_ly,
    c.adobe_byodEntryDevicePageVisitors_direct, w.adobe_byodEntryDevicePageVisitors_direct AS adobe_byodEntryDevicePageVisitors_direct_wow, l.adobe_byodEntryDevicePageVisitors_direct AS adobe_byodEntryDevicePageVisitors_direct_ly,
    c.adobe_byodEntryPlansPageVisitors_direct, w.adobe_byodEntryPlansPageVisitors_direct AS adobe_byodEntryPlansPageVisitors_direct_wow, l.adobe_byodEntryPlansPageVisitors_direct AS adobe_byodEntryPlansPageVisitors_direct_ly,
    c.adobe_byodEntryOtherPageVisitors_direct, w.adobe_byodEntryOtherPageVisitors_direct AS adobe_byodEntryOtherPageVisitors_direct_wow, l.adobe_byodEntryOtherPageVisitors_direct AS adobe_byodEntryOtherPageVisitors_direct_ly,
    c.adobe_byodEntryStorePageVisitors_direct, w.adobe_byodEntryStorePageVisitors_direct AS adobe_byodEntryStorePageVisitors_direct_wow, l.adobe_byodEntryStorePageVisitors_direct AS adobe_byodEntryStorePageVisitors_direct_ly,
    c.adobe_byodEntryByodLandingPageVisitors_direct, w.adobe_byodEntryByodLandingPageVisitors_direct AS adobe_byodEntryByodLandingPageVisitors_direct_wow, l.adobe_byodEntryByodLandingPageVisitors_direct AS adobe_byodEntryByodLandingPageVisitors_direct_ly,
    c.adobe_byodEntryOffersSwitchVisitors_direct, w.adobe_byodEntryOffersSwitchVisitors_direct AS adobe_byodEntryOffersSwitchVisitors_direct_wow, l.adobe_byodEntryOffersSwitchVisitors_direct AS adobe_byodEntryOffersSwitchVisitors_direct_ly,
    -- SOCIAL
    c.adobe_byodUvnbVisitors_social, w.adobe_byodUvnbVisitors_social AS adobe_byodUvnbVisitors_social_wow, l.adobe_byodUvnbVisitors_social AS adobe_byodUvnbVisitors_social_ly,
    c.adobe_byodEntryByodPageVisitors_social, w.adobe_byodEntryByodPageVisitors_social AS adobe_byodEntryByodPageVisitors_social_wow, l.adobe_byodEntryByodPageVisitors_social AS adobe_byodEntryByodPageVisitors_social_ly,
    c.adobe_byodEntryHomePageVisitors_social, w.adobe_byodEntryHomePageVisitors_social AS adobe_byodEntryHomePageVisitors_social_wow, l.adobe_byodEntryHomePageVisitors_social AS adobe_byodEntryHomePageVisitors_social_ly,
    c.adobe_byodEntryDevicePageVisitors_social, w.adobe_byodEntryDevicePageVisitors_social AS adobe_byodEntryDevicePageVisitors_social_wow, l.adobe_byodEntryDevicePageVisitors_social AS adobe_byodEntryDevicePageVisitors_social_ly,
    c.adobe_byodEntryPlansPageVisitors_social, w.adobe_byodEntryPlansPageVisitors_social AS adobe_byodEntryPlansPageVisitors_social_wow, l.adobe_byodEntryPlansPageVisitors_social AS adobe_byodEntryPlansPageVisitors_social_ly,
    c.adobe_byodEntryOtherPageVisitors_social, w.adobe_byodEntryOtherPageVisitors_social AS adobe_byodEntryOtherPageVisitors_social_wow, l.adobe_byodEntryOtherPageVisitors_social AS adobe_byodEntryOtherPageVisitors_social_ly,
    c.adobe_byodEntryStorePageVisitors_social, w.adobe_byodEntryStorePageVisitors_social AS adobe_byodEntryStorePageVisitors_social_wow, l.adobe_byodEntryStorePageVisitors_social AS adobe_byodEntryStorePageVisitors_social_ly,
    c.adobe_byodEntryByodLandingPageVisitors_social, w.adobe_byodEntryByodLandingPageVisitors_social AS adobe_byodEntryByodLandingPageVisitors_social_wow, l.adobe_byodEntryByodLandingPageVisitors_social AS adobe_byodEntryByodLandingPageVisitors_social_ly,
    c.adobe_byodEntryOffersSwitchVisitors_social, w.adobe_byodEntryOffersSwitchVisitors_social AS adobe_byodEntryOffersSwitchVisitors_social_wow, l.adobe_byodEntryOffersSwitchVisitors_social AS adobe_byodEntryOffersSwitchVisitors_social_ly,
    -- PROGRAMMATIC
    c.adobe_byodUvnbVisitors_programmatic, w.adobe_byodUvnbVisitors_programmatic AS adobe_byodUvnbVisitors_programmatic_wow, l.adobe_byodUvnbVisitors_programmatic AS adobe_byodUvnbVisitors_programmatic_ly,
    c.adobe_byodEntryByodPageVisitors_programmatic, w.adobe_byodEntryByodPageVisitors_programmatic AS adobe_byodEntryByodPageVisitors_programmatic_wow, l.adobe_byodEntryByodPageVisitors_programmatic AS adobe_byodEntryByodPageVisitors_programmatic_ly,
    c.adobe_byodEntryHomePageVisitors_programmatic, w.adobe_byodEntryHomePageVisitors_programmatic AS adobe_byodEntryHomePageVisitors_programmatic_wow, l.adobe_byodEntryHomePageVisitors_programmatic AS adobe_byodEntryHomePageVisitors_programmatic_ly,
    c.adobe_byodEntryDevicePageVisitors_programmatic, w.adobe_byodEntryDevicePageVisitors_programmatic AS adobe_byodEntryDevicePageVisitors_programmatic_wow, l.adobe_byodEntryDevicePageVisitors_programmatic AS adobe_byodEntryDevicePageVisitors_programmatic_ly,
    c.adobe_byodEntryPlansPageVisitors_programmatic, w.adobe_byodEntryPlansPageVisitors_programmatic AS adobe_byodEntryPlansPageVisitors_programmatic_wow, l.adobe_byodEntryPlansPageVisitors_programmatic AS adobe_byodEntryPlansPageVisitors_programmatic_ly,
    c.adobe_byodEntryOtherPageVisitors_programmatic, w.adobe_byodEntryOtherPageVisitors_programmatic AS adobe_byodEntryOtherPageVisitors_programmatic_wow, l.adobe_byodEntryOtherPageVisitors_programmatic AS adobe_byodEntryOtherPageVisitors_programmatic_ly,
    c.adobe_byodEntryStorePageVisitors_programmatic, w.adobe_byodEntryStorePageVisitors_programmatic AS adobe_byodEntryStorePageVisitors_programmatic_wow, l.adobe_byodEntryStorePageVisitors_programmatic AS adobe_byodEntryStorePageVisitors_programmatic_ly,
    c.adobe_byodEntryByodLandingPageVisitors_programmatic, w.adobe_byodEntryByodLandingPageVisitors_programmatic AS adobe_byodEntryByodLandingPageVisitors_programmatic_wow, l.adobe_byodEntryByodLandingPageVisitors_programmatic AS adobe_byodEntryByodLandingPageVisitors_programmatic_ly,
    c.adobe_byodEntryOffersSwitchVisitors_programmatic, w.adobe_byodEntryOffersSwitchVisitors_programmatic AS adobe_byodEntryOffersSwitchVisitors_programmatic_wow, l.adobe_byodEntryOffersSwitchVisitors_programmatic AS adobe_byodEntryOffersSwitchVisitors_programmatic_ly,
    -- OTHER
    c.adobe_byodUvnbVisitors_other, w.adobe_byodUvnbVisitors_other AS adobe_byodUvnbVisitors_other_wow, l.adobe_byodUvnbVisitors_other AS adobe_byodUvnbVisitors_other_ly,
    c.adobe_byodEntryByodPageVisitors_other, w.adobe_byodEntryByodPageVisitors_other AS adobe_byodEntryByodPageVisitors_other_wow, l.adobe_byodEntryByodPageVisitors_other AS adobe_byodEntryByodPageVisitors_other_ly,
    c.adobe_byodEntryHomePageVisitors_other, w.adobe_byodEntryHomePageVisitors_other AS adobe_byodEntryHomePageVisitors_other_wow, l.adobe_byodEntryHomePageVisitors_other AS adobe_byodEntryHomePageVisitors_other_ly,
    c.adobe_byodEntryDevicePageVisitors_other, w.adobe_byodEntryDevicePageVisitors_other AS adobe_byodEntryDevicePageVisitors_other_wow, l.adobe_byodEntryDevicePageVisitors_other AS adobe_byodEntryDevicePageVisitors_other_ly,
    c.adobe_byodEntryPlansPageVisitors_other, w.adobe_byodEntryPlansPageVisitors_other AS adobe_byodEntryPlansPageVisitors_other_wow, l.adobe_byodEntryPlansPageVisitors_other AS adobe_byodEntryPlansPageVisitors_other_ly,
    c.adobe_byodEntryOtherPageVisitors_other, w.adobe_byodEntryOtherPageVisitors_other AS adobe_byodEntryOtherPageVisitors_other_wow, l.adobe_byodEntryOtherPageVisitors_other AS adobe_byodEntryOtherPageVisitors_other_ly,
    c.adobe_byodEntryStorePageVisitors_other, w.adobe_byodEntryStorePageVisitors_other AS adobe_byodEntryStorePageVisitors_other_wow, l.adobe_byodEntryStorePageVisitors_other AS adobe_byodEntryStorePageVisitors_other_ly,
    c.adobe_byodEntryByodLandingPageVisitors_other, w.adobe_byodEntryByodLandingPageVisitors_other AS adobe_byodEntryByodLandingPageVisitors_other_wow, l.adobe_byodEntryByodLandingPageVisitors_other AS adobe_byodEntryByodLandingPageVisitors_other_ly,
    c.adobe_byodEntryOffersSwitchVisitors_other, w.adobe_byodEntryOffersSwitchVisitors_other AS adobe_byodEntryOffersSwitchVisitors_other_wow, l.adobe_byodEntryOffersSwitchVisitors_other AS adobe_byodEntryOffersSwitchVisitors_other_ly,
  FROM with_week_num c
  LEFT JOIN with_week_num w ON c.week_sun_to_sat = DATE_ADD(w.week_sun_to_sat, INTERVAL 7 DAY)
  LEFT JOIN with_week_num l ON (c.custom_week_num - l.custom_week_num) = 52
),

with_pcts AS (
  SELECT
    week_sun_to_sat, custom_week_num,
    -- ALL CHANNELS
    adobe_byodUvnbVisitors_allChannels, adobe_byodUvnbVisitors_allChannels_wow, adobe_byodUvnbVisitors_allChannels_ly, CASE WHEN adobe_byodUvnbVisitors_allChannels_wow IS NULL OR adobe_byodUvnbVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_allChannels - adobe_byodUvnbVisitors_allChannels_wow) / adobe_byodUvnbVisitors_allChannels_wow, 6) END AS adobe_byodUvnbVisitors_allChannels_wow_pct, CASE WHEN adobe_byodUvnbVisitors_allChannels_ly  IS NULL OR adobe_byodUvnbVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_allChannels - adobe_byodUvnbVisitors_allChannels_ly)  / adobe_byodUvnbVisitors_allChannels_ly,  6) END AS adobe_byodUvnbVisitors_allChannels_yoy_pct,
    adobe_byodEntryByodPageVisitors_allChannels, adobe_byodEntryByodPageVisitors_allChannels_wow, adobe_byodEntryByodPageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryByodPageVisitors_allChannels_wow IS NULL OR adobe_byodEntryByodPageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_allChannels - adobe_byodEntryByodPageVisitors_allChannels_wow) / adobe_byodEntryByodPageVisitors_allChannels_wow, 6) END AS adobe_byodEntryByodPageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryByodPageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_allChannels - adobe_byodEntryByodPageVisitors_allChannels_ly)  / adobe_byodEntryByodPageVisitors_allChannels_ly,  6) END AS adobe_byodEntryByodPageVisitors_allChannels_yoy_pct,
    adobe_byodEntryHomePageVisitors_allChannels, adobe_byodEntryHomePageVisitors_allChannels_wow, adobe_byodEntryHomePageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryHomePageVisitors_allChannels_wow IS NULL OR adobe_byodEntryHomePageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_allChannels - adobe_byodEntryHomePageVisitors_allChannels_wow) / adobe_byodEntryHomePageVisitors_allChannels_wow, 6) END AS adobe_byodEntryHomePageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryHomePageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_allChannels - adobe_byodEntryHomePageVisitors_allChannels_ly)  / adobe_byodEntryHomePageVisitors_allChannels_ly,  6) END AS adobe_byodEntryHomePageVisitors_allChannels_yoy_pct,
    adobe_byodEntryDevicePageVisitors_allChannels, adobe_byodEntryDevicePageVisitors_allChannels_wow, adobe_byodEntryDevicePageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_allChannels_wow IS NULL OR adobe_byodEntryDevicePageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_allChannels - adobe_byodEntryDevicePageVisitors_allChannels_wow) / adobe_byodEntryDevicePageVisitors_allChannels_wow, 6) END AS adobe_byodEntryDevicePageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_allChannels - adobe_byodEntryDevicePageVisitors_allChannels_ly)  / adobe_byodEntryDevicePageVisitors_allChannels_ly,  6) END AS adobe_byodEntryDevicePageVisitors_allChannels_yoy_pct,
    adobe_byodEntryPlansPageVisitors_allChannels, adobe_byodEntryPlansPageVisitors_allChannels_wow, adobe_byodEntryPlansPageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_allChannels_wow IS NULL OR adobe_byodEntryPlansPageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_allChannels - adobe_byodEntryPlansPageVisitors_allChannels_wow) / adobe_byodEntryPlansPageVisitors_allChannels_wow, 6) END AS adobe_byodEntryPlansPageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_allChannels - adobe_byodEntryPlansPageVisitors_allChannels_ly)  / adobe_byodEntryPlansPageVisitors_allChannels_ly,  6) END AS adobe_byodEntryPlansPageVisitors_allChannels_yoy_pct,
    adobe_byodEntryOtherPageVisitors_allChannels, adobe_byodEntryOtherPageVisitors_allChannels_wow, adobe_byodEntryOtherPageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_allChannels_wow IS NULL OR adobe_byodEntryOtherPageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_allChannels - adobe_byodEntryOtherPageVisitors_allChannels_wow) / adobe_byodEntryOtherPageVisitors_allChannels_wow, 6) END AS adobe_byodEntryOtherPageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_allChannels - adobe_byodEntryOtherPageVisitors_allChannels_ly)  / adobe_byodEntryOtherPageVisitors_allChannels_ly,  6) END AS adobe_byodEntryOtherPageVisitors_allChannels_yoy_pct,
    adobe_byodEntryStorePageVisitors_allChannels, adobe_byodEntryStorePageVisitors_allChannels_wow, adobe_byodEntryStorePageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryStorePageVisitors_allChannels_wow IS NULL OR adobe_byodEntryStorePageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_allChannels - adobe_byodEntryStorePageVisitors_allChannels_wow) / adobe_byodEntryStorePageVisitors_allChannels_wow, 6) END AS adobe_byodEntryStorePageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryStorePageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryStorePageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_allChannels - adobe_byodEntryStorePageVisitors_allChannels_ly)  / adobe_byodEntryStorePageVisitors_allChannels_ly,  6) END AS adobe_byodEntryStorePageVisitors_allChannels_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_allChannels, adobe_byodEntryByodLandingPageVisitors_allChannels_wow, adobe_byodEntryByodLandingPageVisitors_allChannels_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_allChannels_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_allChannels - adobe_byodEntryByodLandingPageVisitors_allChannels_wow) / adobe_byodEntryByodLandingPageVisitors_allChannels_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_allChannels_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_allChannels - adobe_byodEntryByodLandingPageVisitors_allChannels_ly)  / adobe_byodEntryByodLandingPageVisitors_allChannels_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_allChannels_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_allChannels, adobe_byodEntryOffersSwitchVisitors_allChannels_wow, adobe_byodEntryOffersSwitchVisitors_allChannels_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_allChannels_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_allChannels - adobe_byodEntryOffersSwitchVisitors_allChannels_wow) / adobe_byodEntryOffersSwitchVisitors_allChannels_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_allChannels_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_allChannels_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_allChannels - adobe_byodEntryOffersSwitchVisitors_allChannels_ly)  / adobe_byodEntryOffersSwitchVisitors_allChannels_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_allChannels_yoy_pct,
    -- PAID SEARCH
    adobe_byodUvnbVisitors_paidSearch, adobe_byodUvnbVisitors_paidSearch_wow, adobe_byodUvnbVisitors_paidSearch_ly, CASE WHEN adobe_byodUvnbVisitors_paidSearch_wow IS NULL OR adobe_byodUvnbVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_paidSearch - adobe_byodUvnbVisitors_paidSearch_wow) / adobe_byodUvnbVisitors_paidSearch_wow, 6) END AS adobe_byodUvnbVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodUvnbVisitors_paidSearch_ly  IS NULL OR adobe_byodUvnbVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_paidSearch - adobe_byodUvnbVisitors_paidSearch_ly)  / adobe_byodUvnbVisitors_paidSearch_ly,  6) END AS adobe_byodUvnbVisitors_paidSearch_yoy_pct,
    adobe_byodEntryByodPageVisitors_paidSearch, adobe_byodEntryByodPageVisitors_paidSearch_wow, adobe_byodEntryByodPageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryByodPageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryByodPageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_paidSearch - adobe_byodEntryByodPageVisitors_paidSearch_wow) / adobe_byodEntryByodPageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryByodPageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryByodPageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_paidSearch - adobe_byodEntryByodPageVisitors_paidSearch_ly)  / adobe_byodEntryByodPageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryByodPageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryHomePageVisitors_paidSearch, adobe_byodEntryHomePageVisitors_paidSearch_wow, adobe_byodEntryHomePageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryHomePageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryHomePageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_paidSearch - adobe_byodEntryHomePageVisitors_paidSearch_wow) / adobe_byodEntryHomePageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryHomePageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryHomePageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_paidSearch - adobe_byodEntryHomePageVisitors_paidSearch_ly)  / adobe_byodEntryHomePageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryHomePageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryDevicePageVisitors_paidSearch, adobe_byodEntryDevicePageVisitors_paidSearch_wow, adobe_byodEntryDevicePageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryDevicePageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_paidSearch - adobe_byodEntryDevicePageVisitors_paidSearch_wow) / adobe_byodEntryDevicePageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryDevicePageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_paidSearch - adobe_byodEntryDevicePageVisitors_paidSearch_ly)  / adobe_byodEntryDevicePageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryDevicePageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryPlansPageVisitors_paidSearch, adobe_byodEntryPlansPageVisitors_paidSearch_wow, adobe_byodEntryPlansPageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryPlansPageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_paidSearch - adobe_byodEntryPlansPageVisitors_paidSearch_wow) / adobe_byodEntryPlansPageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryPlansPageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_paidSearch - adobe_byodEntryPlansPageVisitors_paidSearch_ly)  / adobe_byodEntryPlansPageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryPlansPageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryOtherPageVisitors_paidSearch, adobe_byodEntryOtherPageVisitors_paidSearch_wow, adobe_byodEntryOtherPageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryOtherPageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_paidSearch - adobe_byodEntryOtherPageVisitors_paidSearch_wow) / adobe_byodEntryOtherPageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryOtherPageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_paidSearch - adobe_byodEntryOtherPageVisitors_paidSearch_ly)  / adobe_byodEntryOtherPageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryOtherPageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryStorePageVisitors_paidSearch, adobe_byodEntryStorePageVisitors_paidSearch_wow, adobe_byodEntryStorePageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryStorePageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryStorePageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_paidSearch - adobe_byodEntryStorePageVisitors_paidSearch_wow) / adobe_byodEntryStorePageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryStorePageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryStorePageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryStorePageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_paidSearch - adobe_byodEntryStorePageVisitors_paidSearch_ly)  / adobe_byodEntryStorePageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryStorePageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_paidSearch, adobe_byodEntryByodLandingPageVisitors_paidSearch_wow, adobe_byodEntryByodLandingPageVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_paidSearch_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_paidSearch - adobe_byodEntryByodLandingPageVisitors_paidSearch_wow) / adobe_byodEntryByodLandingPageVisitors_paidSearch_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_paidSearch - adobe_byodEntryByodLandingPageVisitors_paidSearch_ly)  / adobe_byodEntryByodLandingPageVisitors_paidSearch_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_paidSearch_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_paidSearch, adobe_byodEntryOffersSwitchVisitors_paidSearch_wow, adobe_byodEntryOffersSwitchVisitors_paidSearch_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_paidSearch_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_paidSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_paidSearch - adobe_byodEntryOffersSwitchVisitors_paidSearch_wow) / adobe_byodEntryOffersSwitchVisitors_paidSearch_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_paidSearch_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_paidSearch_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_paidSearch - adobe_byodEntryOffersSwitchVisitors_paidSearch_ly)  / adobe_byodEntryOffersSwitchVisitors_paidSearch_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_paidSearch_yoy_pct,
    -- ORGANIC SEARCH
    adobe_byodUvnbVisitors_organicSearch, adobe_byodUvnbVisitors_organicSearch_wow, adobe_byodUvnbVisitors_organicSearch_ly, CASE WHEN adobe_byodUvnbVisitors_organicSearch_wow IS NULL OR adobe_byodUvnbVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_organicSearch - adobe_byodUvnbVisitors_organicSearch_wow) / adobe_byodUvnbVisitors_organicSearch_wow, 6) END AS adobe_byodUvnbVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodUvnbVisitors_organicSearch_ly  IS NULL OR adobe_byodUvnbVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_organicSearch - adobe_byodUvnbVisitors_organicSearch_ly)  / adobe_byodUvnbVisitors_organicSearch_ly,  6) END AS adobe_byodUvnbVisitors_organicSearch_yoy_pct,
    adobe_byodEntryByodPageVisitors_organicSearch, adobe_byodEntryByodPageVisitors_organicSearch_wow, adobe_byodEntryByodPageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryByodPageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryByodPageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_organicSearch - adobe_byodEntryByodPageVisitors_organicSearch_wow) / adobe_byodEntryByodPageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryByodPageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryByodPageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_organicSearch - adobe_byodEntryByodPageVisitors_organicSearch_ly)  / adobe_byodEntryByodPageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryByodPageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryHomePageVisitors_organicSearch, adobe_byodEntryHomePageVisitors_organicSearch_wow, adobe_byodEntryHomePageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryHomePageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryHomePageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_organicSearch - adobe_byodEntryHomePageVisitors_organicSearch_wow) / adobe_byodEntryHomePageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryHomePageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryHomePageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_organicSearch - adobe_byodEntryHomePageVisitors_organicSearch_ly)  / adobe_byodEntryHomePageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryHomePageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryDevicePageVisitors_organicSearch, adobe_byodEntryDevicePageVisitors_organicSearch_wow, adobe_byodEntryDevicePageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryDevicePageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_organicSearch - adobe_byodEntryDevicePageVisitors_organicSearch_wow) / adobe_byodEntryDevicePageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryDevicePageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_organicSearch - adobe_byodEntryDevicePageVisitors_organicSearch_ly)  / adobe_byodEntryDevicePageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryDevicePageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryPlansPageVisitors_organicSearch, adobe_byodEntryPlansPageVisitors_organicSearch_wow, adobe_byodEntryPlansPageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryPlansPageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_organicSearch - adobe_byodEntryPlansPageVisitors_organicSearch_wow) / adobe_byodEntryPlansPageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryPlansPageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_organicSearch - adobe_byodEntryPlansPageVisitors_organicSearch_ly)  / adobe_byodEntryPlansPageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryPlansPageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryOtherPageVisitors_organicSearch, adobe_byodEntryOtherPageVisitors_organicSearch_wow, adobe_byodEntryOtherPageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryOtherPageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_organicSearch - adobe_byodEntryOtherPageVisitors_organicSearch_wow) / adobe_byodEntryOtherPageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryOtherPageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_organicSearch - adobe_byodEntryOtherPageVisitors_organicSearch_ly)  / adobe_byodEntryOtherPageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryOtherPageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryStorePageVisitors_organicSearch, adobe_byodEntryStorePageVisitors_organicSearch_wow, adobe_byodEntryStorePageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryStorePageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryStorePageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_organicSearch - adobe_byodEntryStorePageVisitors_organicSearch_wow) / adobe_byodEntryStorePageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryStorePageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryStorePageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryStorePageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_organicSearch - adobe_byodEntryStorePageVisitors_organicSearch_ly)  / adobe_byodEntryStorePageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryStorePageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_organicSearch, adobe_byodEntryByodLandingPageVisitors_organicSearch_wow, adobe_byodEntryByodLandingPageVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_organicSearch_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_organicSearch - adobe_byodEntryByodLandingPageVisitors_organicSearch_wow) / adobe_byodEntryByodLandingPageVisitors_organicSearch_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_organicSearch - adobe_byodEntryByodLandingPageVisitors_organicSearch_ly)  / adobe_byodEntryByodLandingPageVisitors_organicSearch_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_organicSearch_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_organicSearch, adobe_byodEntryOffersSwitchVisitors_organicSearch_wow, adobe_byodEntryOffersSwitchVisitors_organicSearch_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_organicSearch_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_organicSearch - adobe_byodEntryOffersSwitchVisitors_organicSearch_wow) / adobe_byodEntryOffersSwitchVisitors_organicSearch_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_organicSearch_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_organicSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_organicSearch - adobe_byodEntryOffersSwitchVisitors_organicSearch_ly)  / adobe_byodEntryOffersSwitchVisitors_organicSearch_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_organicSearch_yoy_pct,
    -- DIRECT
    adobe_byodUvnbVisitors_direct, adobe_byodUvnbVisitors_direct_wow, adobe_byodUvnbVisitors_direct_ly, CASE WHEN adobe_byodUvnbVisitors_direct_wow IS NULL OR adobe_byodUvnbVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_direct - adobe_byodUvnbVisitors_direct_wow) / adobe_byodUvnbVisitors_direct_wow, 6) END AS adobe_byodUvnbVisitors_direct_wow_pct, CASE WHEN adobe_byodUvnbVisitors_direct_ly  IS NULL OR adobe_byodUvnbVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_direct - adobe_byodUvnbVisitors_direct_ly)  / adobe_byodUvnbVisitors_direct_ly,  6) END AS adobe_byodUvnbVisitors_direct_yoy_pct,
    adobe_byodEntryByodPageVisitors_direct, adobe_byodEntryByodPageVisitors_direct_wow, adobe_byodEntryByodPageVisitors_direct_ly, CASE WHEN adobe_byodEntryByodPageVisitors_direct_wow IS NULL OR adobe_byodEntryByodPageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_direct - adobe_byodEntryByodPageVisitors_direct_wow) / adobe_byodEntryByodPageVisitors_direct_wow, 6) END AS adobe_byodEntryByodPageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_direct_ly  IS NULL OR adobe_byodEntryByodPageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_direct - adobe_byodEntryByodPageVisitors_direct_ly)  / adobe_byodEntryByodPageVisitors_direct_ly,  6) END AS adobe_byodEntryByodPageVisitors_direct_yoy_pct,
    adobe_byodEntryHomePageVisitors_direct, adobe_byodEntryHomePageVisitors_direct_wow, adobe_byodEntryHomePageVisitors_direct_ly, CASE WHEN adobe_byodEntryHomePageVisitors_direct_wow IS NULL OR adobe_byodEntryHomePageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_direct - adobe_byodEntryHomePageVisitors_direct_wow) / adobe_byodEntryHomePageVisitors_direct_wow, 6) END AS adobe_byodEntryHomePageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_direct_ly  IS NULL OR adobe_byodEntryHomePageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_direct - adobe_byodEntryHomePageVisitors_direct_ly)  / adobe_byodEntryHomePageVisitors_direct_ly,  6) END AS adobe_byodEntryHomePageVisitors_direct_yoy_pct,
    adobe_byodEntryDevicePageVisitors_direct, adobe_byodEntryDevicePageVisitors_direct_wow, adobe_byodEntryDevicePageVisitors_direct_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_direct_wow IS NULL OR adobe_byodEntryDevicePageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_direct - adobe_byodEntryDevicePageVisitors_direct_wow) / adobe_byodEntryDevicePageVisitors_direct_wow, 6) END AS adobe_byodEntryDevicePageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_direct_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_direct - adobe_byodEntryDevicePageVisitors_direct_ly)  / adobe_byodEntryDevicePageVisitors_direct_ly,  6) END AS adobe_byodEntryDevicePageVisitors_direct_yoy_pct,
    adobe_byodEntryPlansPageVisitors_direct, adobe_byodEntryPlansPageVisitors_direct_wow, adobe_byodEntryPlansPageVisitors_direct_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_direct_wow IS NULL OR adobe_byodEntryPlansPageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_direct - adobe_byodEntryPlansPageVisitors_direct_wow) / adobe_byodEntryPlansPageVisitors_direct_wow, 6) END AS adobe_byodEntryPlansPageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_direct_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_direct - adobe_byodEntryPlansPageVisitors_direct_ly)  / adobe_byodEntryPlansPageVisitors_direct_ly,  6) END AS adobe_byodEntryPlansPageVisitors_direct_yoy_pct,
    adobe_byodEntryOtherPageVisitors_direct, adobe_byodEntryOtherPageVisitors_direct_wow, adobe_byodEntryOtherPageVisitors_direct_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_direct_wow IS NULL OR adobe_byodEntryOtherPageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_direct - adobe_byodEntryOtherPageVisitors_direct_wow) / adobe_byodEntryOtherPageVisitors_direct_wow, 6) END AS adobe_byodEntryOtherPageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_direct_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_direct - adobe_byodEntryOtherPageVisitors_direct_ly)  / adobe_byodEntryOtherPageVisitors_direct_ly,  6) END AS adobe_byodEntryOtherPageVisitors_direct_yoy_pct,
    adobe_byodEntryStorePageVisitors_direct, adobe_byodEntryStorePageVisitors_direct_wow, adobe_byodEntryStorePageVisitors_direct_ly, CASE WHEN adobe_byodEntryStorePageVisitors_direct_wow IS NULL OR adobe_byodEntryStorePageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_direct - adobe_byodEntryStorePageVisitors_direct_wow) / adobe_byodEntryStorePageVisitors_direct_wow, 6) END AS adobe_byodEntryStorePageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryStorePageVisitors_direct_ly  IS NULL OR adobe_byodEntryStorePageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_direct - adobe_byodEntryStorePageVisitors_direct_ly)  / adobe_byodEntryStorePageVisitors_direct_ly,  6) END AS adobe_byodEntryStorePageVisitors_direct_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_direct, adobe_byodEntryByodLandingPageVisitors_direct_wow, adobe_byodEntryByodLandingPageVisitors_direct_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_direct_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_direct - adobe_byodEntryByodLandingPageVisitors_direct_wow) / adobe_byodEntryByodLandingPageVisitors_direct_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_direct_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_direct - adobe_byodEntryByodLandingPageVisitors_direct_ly)  / adobe_byodEntryByodLandingPageVisitors_direct_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_direct_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_direct, adobe_byodEntryOffersSwitchVisitors_direct_wow, adobe_byodEntryOffersSwitchVisitors_direct_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_direct_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_direct_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_direct - adobe_byodEntryOffersSwitchVisitors_direct_wow) / adobe_byodEntryOffersSwitchVisitors_direct_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_direct_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_direct_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_direct_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_direct - adobe_byodEntryOffersSwitchVisitors_direct_ly)  / adobe_byodEntryOffersSwitchVisitors_direct_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_direct_yoy_pct,
    -- SOCIAL
    adobe_byodUvnbVisitors_social, adobe_byodUvnbVisitors_social_wow, adobe_byodUvnbVisitors_social_ly, CASE WHEN adobe_byodUvnbVisitors_social_wow IS NULL OR adobe_byodUvnbVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_social - adobe_byodUvnbVisitors_social_wow) / adobe_byodUvnbVisitors_social_wow, 6) END AS adobe_byodUvnbVisitors_social_wow_pct, CASE WHEN adobe_byodUvnbVisitors_social_ly  IS NULL OR adobe_byodUvnbVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_social - adobe_byodUvnbVisitors_social_ly)  / adobe_byodUvnbVisitors_social_ly,  6) END AS adobe_byodUvnbVisitors_social_yoy_pct,
    adobe_byodEntryByodPageVisitors_social, adobe_byodEntryByodPageVisitors_social_wow, adobe_byodEntryByodPageVisitors_social_ly, CASE WHEN adobe_byodEntryByodPageVisitors_social_wow IS NULL OR adobe_byodEntryByodPageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_social - adobe_byodEntryByodPageVisitors_social_wow) / adobe_byodEntryByodPageVisitors_social_wow, 6) END AS adobe_byodEntryByodPageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_social_ly  IS NULL OR adobe_byodEntryByodPageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_social - adobe_byodEntryByodPageVisitors_social_ly)  / adobe_byodEntryByodPageVisitors_social_ly,  6) END AS adobe_byodEntryByodPageVisitors_social_yoy_pct,
    adobe_byodEntryHomePageVisitors_social, adobe_byodEntryHomePageVisitors_social_wow, adobe_byodEntryHomePageVisitors_social_ly, CASE WHEN adobe_byodEntryHomePageVisitors_social_wow IS NULL OR adobe_byodEntryHomePageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_social - adobe_byodEntryHomePageVisitors_social_wow) / adobe_byodEntryHomePageVisitors_social_wow, 6) END AS adobe_byodEntryHomePageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_social_ly  IS NULL OR adobe_byodEntryHomePageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_social - adobe_byodEntryHomePageVisitors_social_ly)  / adobe_byodEntryHomePageVisitors_social_ly,  6) END AS adobe_byodEntryHomePageVisitors_social_yoy_pct,
    adobe_byodEntryDevicePageVisitors_social, adobe_byodEntryDevicePageVisitors_social_wow, adobe_byodEntryDevicePageVisitors_social_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_social_wow IS NULL OR adobe_byodEntryDevicePageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_social - adobe_byodEntryDevicePageVisitors_social_wow) / adobe_byodEntryDevicePageVisitors_social_wow, 6) END AS adobe_byodEntryDevicePageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_social_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_social - adobe_byodEntryDevicePageVisitors_social_ly)  / adobe_byodEntryDevicePageVisitors_social_ly,  6) END AS adobe_byodEntryDevicePageVisitors_social_yoy_pct,
    adobe_byodEntryPlansPageVisitors_social, adobe_byodEntryPlansPageVisitors_social_wow, adobe_byodEntryPlansPageVisitors_social_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_social_wow IS NULL OR adobe_byodEntryPlansPageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_social - adobe_byodEntryPlansPageVisitors_social_wow) / adobe_byodEntryPlansPageVisitors_social_wow, 6) END AS adobe_byodEntryPlansPageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_social_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_social - adobe_byodEntryPlansPageVisitors_social_ly)  / adobe_byodEntryPlansPageVisitors_social_ly,  6) END AS adobe_byodEntryPlansPageVisitors_social_yoy_pct,
    adobe_byodEntryOtherPageVisitors_social, adobe_byodEntryOtherPageVisitors_social_wow, adobe_byodEntryOtherPageVisitors_social_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_social_wow IS NULL OR adobe_byodEntryOtherPageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_social - adobe_byodEntryOtherPageVisitors_social_wow) / adobe_byodEntryOtherPageVisitors_social_wow, 6) END AS adobe_byodEntryOtherPageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_social_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_social - adobe_byodEntryOtherPageVisitors_social_ly)  / adobe_byodEntryOtherPageVisitors_social_ly,  6) END AS adobe_byodEntryOtherPageVisitors_social_yoy_pct,
    adobe_byodEntryStorePageVisitors_social, adobe_byodEntryStorePageVisitors_social_wow, adobe_byodEntryStorePageVisitors_social_ly, CASE WHEN adobe_byodEntryStorePageVisitors_social_wow IS NULL OR adobe_byodEntryStorePageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_social - adobe_byodEntryStorePageVisitors_social_wow) / adobe_byodEntryStorePageVisitors_social_wow, 6) END AS adobe_byodEntryStorePageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryStorePageVisitors_social_ly  IS NULL OR adobe_byodEntryStorePageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_social - adobe_byodEntryStorePageVisitors_social_ly)  / adobe_byodEntryStorePageVisitors_social_ly,  6) END AS adobe_byodEntryStorePageVisitors_social_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_social, adobe_byodEntryByodLandingPageVisitors_social_wow, adobe_byodEntryByodLandingPageVisitors_social_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_social_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_social - adobe_byodEntryByodLandingPageVisitors_social_wow) / adobe_byodEntryByodLandingPageVisitors_social_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_social_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_social_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_social - adobe_byodEntryByodLandingPageVisitors_social_ly)  / adobe_byodEntryByodLandingPageVisitors_social_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_social_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_social, adobe_byodEntryOffersSwitchVisitors_social_wow, adobe_byodEntryOffersSwitchVisitors_social_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_social_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_social_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_social - adobe_byodEntryOffersSwitchVisitors_social_wow) / adobe_byodEntryOffersSwitchVisitors_social_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_social_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_social_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_social_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_social - adobe_byodEntryOffersSwitchVisitors_social_ly)  / adobe_byodEntryOffersSwitchVisitors_social_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_social_yoy_pct,
    -- PROGRAMMATIC
    adobe_byodUvnbVisitors_programmatic, adobe_byodUvnbVisitors_programmatic_wow, adobe_byodUvnbVisitors_programmatic_ly, CASE WHEN adobe_byodUvnbVisitors_programmatic_wow IS NULL OR adobe_byodUvnbVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_programmatic - adobe_byodUvnbVisitors_programmatic_wow) / adobe_byodUvnbVisitors_programmatic_wow, 6) END AS adobe_byodUvnbVisitors_programmatic_wow_pct, CASE WHEN adobe_byodUvnbVisitors_programmatic_ly  IS NULL OR adobe_byodUvnbVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_programmatic - adobe_byodUvnbVisitors_programmatic_ly)  / adobe_byodUvnbVisitors_programmatic_ly,  6) END AS adobe_byodUvnbVisitors_programmatic_yoy_pct,
    adobe_byodEntryByodPageVisitors_programmatic, adobe_byodEntryByodPageVisitors_programmatic_wow, adobe_byodEntryByodPageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryByodPageVisitors_programmatic_wow IS NULL OR adobe_byodEntryByodPageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_programmatic - adobe_byodEntryByodPageVisitors_programmatic_wow) / adobe_byodEntryByodPageVisitors_programmatic_wow, 6) END AS adobe_byodEntryByodPageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryByodPageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_programmatic - adobe_byodEntryByodPageVisitors_programmatic_ly)  / adobe_byodEntryByodPageVisitors_programmatic_ly,  6) END AS adobe_byodEntryByodPageVisitors_programmatic_yoy_pct,
    adobe_byodEntryHomePageVisitors_programmatic, adobe_byodEntryHomePageVisitors_programmatic_wow, adobe_byodEntryHomePageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryHomePageVisitors_programmatic_wow IS NULL OR adobe_byodEntryHomePageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_programmatic - adobe_byodEntryHomePageVisitors_programmatic_wow) / adobe_byodEntryHomePageVisitors_programmatic_wow, 6) END AS adobe_byodEntryHomePageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryHomePageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_programmatic - adobe_byodEntryHomePageVisitors_programmatic_ly)  / adobe_byodEntryHomePageVisitors_programmatic_ly,  6) END AS adobe_byodEntryHomePageVisitors_programmatic_yoy_pct,
    adobe_byodEntryDevicePageVisitors_programmatic, adobe_byodEntryDevicePageVisitors_programmatic_wow, adobe_byodEntryDevicePageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_programmatic_wow IS NULL OR adobe_byodEntryDevicePageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_programmatic - adobe_byodEntryDevicePageVisitors_programmatic_wow) / adobe_byodEntryDevicePageVisitors_programmatic_wow, 6) END AS adobe_byodEntryDevicePageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_programmatic - adobe_byodEntryDevicePageVisitors_programmatic_ly)  / adobe_byodEntryDevicePageVisitors_programmatic_ly,  6) END AS adobe_byodEntryDevicePageVisitors_programmatic_yoy_pct,
    adobe_byodEntryPlansPageVisitors_programmatic, adobe_byodEntryPlansPageVisitors_programmatic_wow, adobe_byodEntryPlansPageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_programmatic_wow IS NULL OR adobe_byodEntryPlansPageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_programmatic - adobe_byodEntryPlansPageVisitors_programmatic_wow) / adobe_byodEntryPlansPageVisitors_programmatic_wow, 6) END AS adobe_byodEntryPlansPageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_programmatic - adobe_byodEntryPlansPageVisitors_programmatic_ly)  / adobe_byodEntryPlansPageVisitors_programmatic_ly,  6) END AS adobe_byodEntryPlansPageVisitors_programmatic_yoy_pct,
    adobe_byodEntryOtherPageVisitors_programmatic, adobe_byodEntryOtherPageVisitors_programmatic_wow, adobe_byodEntryOtherPageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_programmatic_wow IS NULL OR adobe_byodEntryOtherPageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_programmatic - adobe_byodEntryOtherPageVisitors_programmatic_wow) / adobe_byodEntryOtherPageVisitors_programmatic_wow, 6) END AS adobe_byodEntryOtherPageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_programmatic - adobe_byodEntryOtherPageVisitors_programmatic_ly)  / adobe_byodEntryOtherPageVisitors_programmatic_ly,  6) END AS adobe_byodEntryOtherPageVisitors_programmatic_yoy_pct,
    adobe_byodEntryStorePageVisitors_programmatic, adobe_byodEntryStorePageVisitors_programmatic_wow, adobe_byodEntryStorePageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryStorePageVisitors_programmatic_wow IS NULL OR adobe_byodEntryStorePageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_programmatic - adobe_byodEntryStorePageVisitors_programmatic_wow) / adobe_byodEntryStorePageVisitors_programmatic_wow, 6) END AS adobe_byodEntryStorePageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryStorePageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryStorePageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_programmatic - adobe_byodEntryStorePageVisitors_programmatic_ly)  / adobe_byodEntryStorePageVisitors_programmatic_ly,  6) END AS adobe_byodEntryStorePageVisitors_programmatic_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_programmatic, adobe_byodEntryByodLandingPageVisitors_programmatic_wow, adobe_byodEntryByodLandingPageVisitors_programmatic_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_programmatic_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_programmatic - adobe_byodEntryByodLandingPageVisitors_programmatic_wow) / adobe_byodEntryByodLandingPageVisitors_programmatic_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_programmatic_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_programmatic - adobe_byodEntryByodLandingPageVisitors_programmatic_ly)  / adobe_byodEntryByodLandingPageVisitors_programmatic_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_programmatic_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_programmatic, adobe_byodEntryOffersSwitchVisitors_programmatic_wow, adobe_byodEntryOffersSwitchVisitors_programmatic_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_programmatic_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_programmatic - adobe_byodEntryOffersSwitchVisitors_programmatic_wow) / adobe_byodEntryOffersSwitchVisitors_programmatic_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_programmatic_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_programmatic_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_programmatic_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_programmatic - adobe_byodEntryOffersSwitchVisitors_programmatic_ly)  / adobe_byodEntryOffersSwitchVisitors_programmatic_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_programmatic_yoy_pct,
    -- OTHER
    adobe_byodUvnbVisitors_other, adobe_byodUvnbVisitors_other_wow, adobe_byodUvnbVisitors_other_ly, CASE WHEN adobe_byodUvnbVisitors_other_wow IS NULL OR adobe_byodUvnbVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_other - adobe_byodUvnbVisitors_other_wow) / adobe_byodUvnbVisitors_other_wow, 6) END AS adobe_byodUvnbVisitors_other_wow_pct, CASE WHEN adobe_byodUvnbVisitors_other_ly  IS NULL OR adobe_byodUvnbVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodUvnbVisitors_other - adobe_byodUvnbVisitors_other_ly)  / adobe_byodUvnbVisitors_other_ly,  6) END AS adobe_byodUvnbVisitors_other_yoy_pct,
    adobe_byodEntryByodPageVisitors_other, adobe_byodEntryByodPageVisitors_other_wow, adobe_byodEntryByodPageVisitors_other_ly, CASE WHEN adobe_byodEntryByodPageVisitors_other_wow IS NULL OR adobe_byodEntryByodPageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_other - adobe_byodEntryByodPageVisitors_other_wow) / adobe_byodEntryByodPageVisitors_other_wow, 6) END AS adobe_byodEntryByodPageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryByodPageVisitors_other_ly  IS NULL OR adobe_byodEntryByodPageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodPageVisitors_other - adobe_byodEntryByodPageVisitors_other_ly)  / adobe_byodEntryByodPageVisitors_other_ly,  6) END AS adobe_byodEntryByodPageVisitors_other_yoy_pct,
    adobe_byodEntryHomePageVisitors_other, adobe_byodEntryHomePageVisitors_other_wow, adobe_byodEntryHomePageVisitors_other_ly, CASE WHEN adobe_byodEntryHomePageVisitors_other_wow IS NULL OR adobe_byodEntryHomePageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_other - adobe_byodEntryHomePageVisitors_other_wow) / adobe_byodEntryHomePageVisitors_other_wow, 6) END AS adobe_byodEntryHomePageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryHomePageVisitors_other_ly  IS NULL OR adobe_byodEntryHomePageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryHomePageVisitors_other - adobe_byodEntryHomePageVisitors_other_ly)  / adobe_byodEntryHomePageVisitors_other_ly,  6) END AS adobe_byodEntryHomePageVisitors_other_yoy_pct,
    adobe_byodEntryDevicePageVisitors_other, adobe_byodEntryDevicePageVisitors_other_wow, adobe_byodEntryDevicePageVisitors_other_ly, CASE WHEN adobe_byodEntryDevicePageVisitors_other_wow IS NULL OR adobe_byodEntryDevicePageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_other - adobe_byodEntryDevicePageVisitors_other_wow) / adobe_byodEntryDevicePageVisitors_other_wow, 6) END AS adobe_byodEntryDevicePageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryDevicePageVisitors_other_ly  IS NULL OR adobe_byodEntryDevicePageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryDevicePageVisitors_other - adobe_byodEntryDevicePageVisitors_other_ly)  / adobe_byodEntryDevicePageVisitors_other_ly,  6) END AS adobe_byodEntryDevicePageVisitors_other_yoy_pct,
    adobe_byodEntryPlansPageVisitors_other, adobe_byodEntryPlansPageVisitors_other_wow, adobe_byodEntryPlansPageVisitors_other_ly, CASE WHEN adobe_byodEntryPlansPageVisitors_other_wow IS NULL OR adobe_byodEntryPlansPageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_other - adobe_byodEntryPlansPageVisitors_other_wow) / adobe_byodEntryPlansPageVisitors_other_wow, 6) END AS adobe_byodEntryPlansPageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryPlansPageVisitors_other_ly  IS NULL OR adobe_byodEntryPlansPageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryPlansPageVisitors_other - adobe_byodEntryPlansPageVisitors_other_ly)  / adobe_byodEntryPlansPageVisitors_other_ly,  6) END AS adobe_byodEntryPlansPageVisitors_other_yoy_pct,
    adobe_byodEntryOtherPageVisitors_other, adobe_byodEntryOtherPageVisitors_other_wow, adobe_byodEntryOtherPageVisitors_other_ly, CASE WHEN adobe_byodEntryOtherPageVisitors_other_wow IS NULL OR adobe_byodEntryOtherPageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_other - adobe_byodEntryOtherPageVisitors_other_wow) / adobe_byodEntryOtherPageVisitors_other_wow, 6) END AS adobe_byodEntryOtherPageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryOtherPageVisitors_other_ly  IS NULL OR adobe_byodEntryOtherPageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOtherPageVisitors_other - adobe_byodEntryOtherPageVisitors_other_ly)  / adobe_byodEntryOtherPageVisitors_other_ly,  6) END AS adobe_byodEntryOtherPageVisitors_other_yoy_pct,
    adobe_byodEntryStorePageVisitors_other, adobe_byodEntryStorePageVisitors_other_wow, adobe_byodEntryStorePageVisitors_other_ly, CASE WHEN adobe_byodEntryStorePageVisitors_other_wow IS NULL OR adobe_byodEntryStorePageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_other - adobe_byodEntryStorePageVisitors_other_wow) / adobe_byodEntryStorePageVisitors_other_wow, 6) END AS adobe_byodEntryStorePageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryStorePageVisitors_other_ly  IS NULL OR adobe_byodEntryStorePageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryStorePageVisitors_other - adobe_byodEntryStorePageVisitors_other_ly)  / adobe_byodEntryStorePageVisitors_other_ly,  6) END AS adobe_byodEntryStorePageVisitors_other_yoy_pct,
    adobe_byodEntryByodLandingPageVisitors_other, adobe_byodEntryByodLandingPageVisitors_other_wow, adobe_byodEntryByodLandingPageVisitors_other_ly, CASE WHEN adobe_byodEntryByodLandingPageVisitors_other_wow IS NULL OR adobe_byodEntryByodLandingPageVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_other - adobe_byodEntryByodLandingPageVisitors_other_wow) / adobe_byodEntryByodLandingPageVisitors_other_wow, 6) END AS adobe_byodEntryByodLandingPageVisitors_other_wow_pct, CASE WHEN adobe_byodEntryByodLandingPageVisitors_other_ly  IS NULL OR adobe_byodEntryByodLandingPageVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryByodLandingPageVisitors_other - adobe_byodEntryByodLandingPageVisitors_other_ly)  / adobe_byodEntryByodLandingPageVisitors_other_ly,  6) END AS adobe_byodEntryByodLandingPageVisitors_other_yoy_pct,
    adobe_byodEntryOffersSwitchVisitors_other, adobe_byodEntryOffersSwitchVisitors_other_wow, adobe_byodEntryOffersSwitchVisitors_other_ly, CASE WHEN adobe_byodEntryOffersSwitchVisitors_other_wow IS NULL OR adobe_byodEntryOffersSwitchVisitors_other_wow = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_other - adobe_byodEntryOffersSwitchVisitors_other_wow) / adobe_byodEntryOffersSwitchVisitors_other_wow, 6) END AS adobe_byodEntryOffersSwitchVisitors_other_wow_pct, CASE WHEN adobe_byodEntryOffersSwitchVisitors_other_ly  IS NULL OR adobe_byodEntryOffersSwitchVisitors_other_ly  = 0 THEN NULL ELSE ROUND((adobe_byodEntryOffersSwitchVisitors_other - adobe_byodEntryOffersSwitchVisitors_other_ly)  / adobe_byodEntryOffersSwitchVisitors_other_ly,  6) END AS adobe_byodEntryOffersSwitchVisitors_other_yoy_pct,
  FROM with_comparisons
),

with_max_date AS (
  SELECT
    *,
    MAX(CASE WHEN adobe_byodUvnbVisitors_allChannels IS NOT NULL THEN week_sun_to_sat END) OVER () AS max_data_date
  FROM with_pcts
)

SELECT
  week_sun_to_sat,
  'ADOBE_BYOD_ENTRY_PAGES' AS data_source,
  max_data_date,
  -- ALL CHANNELS
  adobe_byodUvnbVisitors_allChannels, adobe_byodUvnbVisitors_allChannels_wow, adobe_byodUvnbVisitors_allChannels_ly, adobe_byodUvnbVisitors_allChannels_wow_pct, adobe_byodUvnbVisitors_allChannels_yoy_pct,
  adobe_byodEntryByodPageVisitors_allChannels, adobe_byodEntryByodPageVisitors_allChannels_wow, adobe_byodEntryByodPageVisitors_allChannels_ly, adobe_byodEntryByodPageVisitors_allChannels_wow_pct, adobe_byodEntryByodPageVisitors_allChannels_yoy_pct,
  adobe_byodEntryHomePageVisitors_allChannels, adobe_byodEntryHomePageVisitors_allChannels_wow, adobe_byodEntryHomePageVisitors_allChannels_ly, adobe_byodEntryHomePageVisitors_allChannels_wow_pct, adobe_byodEntryHomePageVisitors_allChannels_yoy_pct,
  adobe_byodEntryDevicePageVisitors_allChannels, adobe_byodEntryDevicePageVisitors_allChannels_wow, adobe_byodEntryDevicePageVisitors_allChannels_ly, adobe_byodEntryDevicePageVisitors_allChannels_wow_pct, adobe_byodEntryDevicePageVisitors_allChannels_yoy_pct,
  adobe_byodEntryPlansPageVisitors_allChannels, adobe_byodEntryPlansPageVisitors_allChannels_wow, adobe_byodEntryPlansPageVisitors_allChannels_ly, adobe_byodEntryPlansPageVisitors_allChannels_wow_pct, adobe_byodEntryPlansPageVisitors_allChannels_yoy_pct,
  adobe_byodEntryOtherPageVisitors_allChannels, adobe_byodEntryOtherPageVisitors_allChannels_wow, adobe_byodEntryOtherPageVisitors_allChannels_ly, adobe_byodEntryOtherPageVisitors_allChannels_wow_pct, adobe_byodEntryOtherPageVisitors_allChannels_yoy_pct,
  adobe_byodEntryStorePageVisitors_allChannels, adobe_byodEntryStorePageVisitors_allChannels_wow, adobe_byodEntryStorePageVisitors_allChannels_ly, adobe_byodEntryStorePageVisitors_allChannels_wow_pct, adobe_byodEntryStorePageVisitors_allChannels_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_allChannels, adobe_byodEntryByodLandingPageVisitors_allChannels_wow, adobe_byodEntryByodLandingPageVisitors_allChannels_ly, adobe_byodEntryByodLandingPageVisitors_allChannels_wow_pct, adobe_byodEntryByodLandingPageVisitors_allChannels_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_allChannels, adobe_byodEntryOffersSwitchVisitors_allChannels_wow, adobe_byodEntryOffersSwitchVisitors_allChannels_ly, adobe_byodEntryOffersSwitchVisitors_allChannels_wow_pct, adobe_byodEntryOffersSwitchVisitors_allChannels_yoy_pct,  -- NEW
  -- PAID SEARCH
  adobe_byodUvnbVisitors_paidSearch, adobe_byodUvnbVisitors_paidSearch_wow, adobe_byodUvnbVisitors_paidSearch_ly, adobe_byodUvnbVisitors_paidSearch_wow_pct, adobe_byodUvnbVisitors_paidSearch_yoy_pct,
  adobe_byodEntryByodPageVisitors_paidSearch, adobe_byodEntryByodPageVisitors_paidSearch_wow, adobe_byodEntryByodPageVisitors_paidSearch_ly, adobe_byodEntryByodPageVisitors_paidSearch_wow_pct, adobe_byodEntryByodPageVisitors_paidSearch_yoy_pct,
  adobe_byodEntryHomePageVisitors_paidSearch, adobe_byodEntryHomePageVisitors_paidSearch_wow, adobe_byodEntryHomePageVisitors_paidSearch_ly, adobe_byodEntryHomePageVisitors_paidSearch_wow_pct, adobe_byodEntryHomePageVisitors_paidSearch_yoy_pct,
  adobe_byodEntryDevicePageVisitors_paidSearch, adobe_byodEntryDevicePageVisitors_paidSearch_wow, adobe_byodEntryDevicePageVisitors_paidSearch_ly, adobe_byodEntryDevicePageVisitors_paidSearch_wow_pct, adobe_byodEntryDevicePageVisitors_paidSearch_yoy_pct,
  adobe_byodEntryPlansPageVisitors_paidSearch, adobe_byodEntryPlansPageVisitors_paidSearch_wow, adobe_byodEntryPlansPageVisitors_paidSearch_ly, adobe_byodEntryPlansPageVisitors_paidSearch_wow_pct, adobe_byodEntryPlansPageVisitors_paidSearch_yoy_pct,
  adobe_byodEntryOtherPageVisitors_paidSearch, adobe_byodEntryOtherPageVisitors_paidSearch_wow, adobe_byodEntryOtherPageVisitors_paidSearch_ly, adobe_byodEntryOtherPageVisitors_paidSearch_wow_pct, adobe_byodEntryOtherPageVisitors_paidSearch_yoy_pct,
  adobe_byodEntryStorePageVisitors_paidSearch, adobe_byodEntryStorePageVisitors_paidSearch_wow, adobe_byodEntryStorePageVisitors_paidSearch_ly, adobe_byodEntryStorePageVisitors_paidSearch_wow_pct, adobe_byodEntryStorePageVisitors_paidSearch_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_paidSearch, adobe_byodEntryByodLandingPageVisitors_paidSearch_wow, adobe_byodEntryByodLandingPageVisitors_paidSearch_ly, adobe_byodEntryByodLandingPageVisitors_paidSearch_wow_pct, adobe_byodEntryByodLandingPageVisitors_paidSearch_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_paidSearch, adobe_byodEntryOffersSwitchVisitors_paidSearch_wow, adobe_byodEntryOffersSwitchVisitors_paidSearch_ly, adobe_byodEntryOffersSwitchVisitors_paidSearch_wow_pct, adobe_byodEntryOffersSwitchVisitors_paidSearch_yoy_pct,  -- NEW
  -- ORGANIC SEARCH
  adobe_byodUvnbVisitors_organicSearch, adobe_byodUvnbVisitors_organicSearch_wow, adobe_byodUvnbVisitors_organicSearch_ly, adobe_byodUvnbVisitors_organicSearch_wow_pct, adobe_byodUvnbVisitors_organicSearch_yoy_pct,
  adobe_byodEntryByodPageVisitors_organicSearch, adobe_byodEntryByodPageVisitors_organicSearch_wow, adobe_byodEntryByodPageVisitors_organicSearch_ly, adobe_byodEntryByodPageVisitors_organicSearch_wow_pct, adobe_byodEntryByodPageVisitors_organicSearch_yoy_pct,
  adobe_byodEntryHomePageVisitors_organicSearch, adobe_byodEntryHomePageVisitors_organicSearch_wow, adobe_byodEntryHomePageVisitors_organicSearch_ly, adobe_byodEntryHomePageVisitors_organicSearch_wow_pct, adobe_byodEntryHomePageVisitors_organicSearch_yoy_pct,
  adobe_byodEntryDevicePageVisitors_organicSearch, adobe_byodEntryDevicePageVisitors_organicSearch_wow, adobe_byodEntryDevicePageVisitors_organicSearch_ly, adobe_byodEntryDevicePageVisitors_organicSearch_wow_pct, adobe_byodEntryDevicePageVisitors_organicSearch_yoy_pct,
  adobe_byodEntryPlansPageVisitors_organicSearch, adobe_byodEntryPlansPageVisitors_organicSearch_wow, adobe_byodEntryPlansPageVisitors_organicSearch_ly, adobe_byodEntryPlansPageVisitors_organicSearch_wow_pct, adobe_byodEntryPlansPageVisitors_organicSearch_yoy_pct,
  adobe_byodEntryOtherPageVisitors_organicSearch, adobe_byodEntryOtherPageVisitors_organicSearch_wow, adobe_byodEntryOtherPageVisitors_organicSearch_ly, adobe_byodEntryOtherPageVisitors_organicSearch_wow_pct, adobe_byodEntryOtherPageVisitors_organicSearch_yoy_pct,
  adobe_byodEntryStorePageVisitors_organicSearch, adobe_byodEntryStorePageVisitors_organicSearch_wow, adobe_byodEntryStorePageVisitors_organicSearch_ly, adobe_byodEntryStorePageVisitors_organicSearch_wow_pct, adobe_byodEntryStorePageVisitors_organicSearch_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_organicSearch, adobe_byodEntryByodLandingPageVisitors_organicSearch_wow, adobe_byodEntryByodLandingPageVisitors_organicSearch_ly, adobe_byodEntryByodLandingPageVisitors_organicSearch_wow_pct, adobe_byodEntryByodLandingPageVisitors_organicSearch_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_organicSearch, adobe_byodEntryOffersSwitchVisitors_organicSearch_wow, adobe_byodEntryOffersSwitchVisitors_organicSearch_ly, adobe_byodEntryOffersSwitchVisitors_organicSearch_wow_pct, adobe_byodEntryOffersSwitchVisitors_organicSearch_yoy_pct,  -- NEW
  -- DIRECT
  adobe_byodUvnbVisitors_direct, adobe_byodUvnbVisitors_direct_wow, adobe_byodUvnbVisitors_direct_ly, adobe_byodUvnbVisitors_direct_wow_pct, adobe_byodUvnbVisitors_direct_yoy_pct,
  adobe_byodEntryByodPageVisitors_direct, adobe_byodEntryByodPageVisitors_direct_wow, adobe_byodEntryByodPageVisitors_direct_ly, adobe_byodEntryByodPageVisitors_direct_wow_pct, adobe_byodEntryByodPageVisitors_direct_yoy_pct,
  adobe_byodEntryHomePageVisitors_direct, adobe_byodEntryHomePageVisitors_direct_wow, adobe_byodEntryHomePageVisitors_direct_ly, adobe_byodEntryHomePageVisitors_direct_wow_pct, adobe_byodEntryHomePageVisitors_direct_yoy_pct,
  adobe_byodEntryDevicePageVisitors_direct, adobe_byodEntryDevicePageVisitors_direct_wow, adobe_byodEntryDevicePageVisitors_direct_ly, adobe_byodEntryDevicePageVisitors_direct_wow_pct, adobe_byodEntryDevicePageVisitors_direct_yoy_pct,
  adobe_byodEntryPlansPageVisitors_direct, adobe_byodEntryPlansPageVisitors_direct_wow, adobe_byodEntryPlansPageVisitors_direct_ly, adobe_byodEntryPlansPageVisitors_direct_wow_pct, adobe_byodEntryPlansPageVisitors_direct_yoy_pct,
  adobe_byodEntryOtherPageVisitors_direct, adobe_byodEntryOtherPageVisitors_direct_wow, adobe_byodEntryOtherPageVisitors_direct_ly, adobe_byodEntryOtherPageVisitors_direct_wow_pct, adobe_byodEntryOtherPageVisitors_direct_yoy_pct,
  adobe_byodEntryStorePageVisitors_direct, adobe_byodEntryStorePageVisitors_direct_wow, adobe_byodEntryStorePageVisitors_direct_ly, adobe_byodEntryStorePageVisitors_direct_wow_pct, adobe_byodEntryStorePageVisitors_direct_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_direct, adobe_byodEntryByodLandingPageVisitors_direct_wow, adobe_byodEntryByodLandingPageVisitors_direct_ly, adobe_byodEntryByodLandingPageVisitors_direct_wow_pct, adobe_byodEntryByodLandingPageVisitors_direct_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_direct, adobe_byodEntryOffersSwitchVisitors_direct_wow, adobe_byodEntryOffersSwitchVisitors_direct_ly, adobe_byodEntryOffersSwitchVisitors_direct_wow_pct, adobe_byodEntryOffersSwitchVisitors_direct_yoy_pct,  -- NEW
  -- SOCIAL
  adobe_byodUvnbVisitors_social, adobe_byodUvnbVisitors_social_wow, adobe_byodUvnbVisitors_social_ly, adobe_byodUvnbVisitors_social_wow_pct, adobe_byodUvnbVisitors_social_yoy_pct,
  adobe_byodEntryByodPageVisitors_social, adobe_byodEntryByodPageVisitors_social_wow, adobe_byodEntryByodPageVisitors_social_ly, adobe_byodEntryByodPageVisitors_social_wow_pct, adobe_byodEntryByodPageVisitors_social_yoy_pct,
  adobe_byodEntryHomePageVisitors_social, adobe_byodEntryHomePageVisitors_social_wow, adobe_byodEntryHomePageVisitors_social_ly, adobe_byodEntryHomePageVisitors_social_wow_pct, adobe_byodEntryHomePageVisitors_social_yoy_pct,
  adobe_byodEntryDevicePageVisitors_social, adobe_byodEntryDevicePageVisitors_social_wow, adobe_byodEntryDevicePageVisitors_social_ly, adobe_byodEntryDevicePageVisitors_social_wow_pct, adobe_byodEntryDevicePageVisitors_social_yoy_pct,
  adobe_byodEntryPlansPageVisitors_social, adobe_byodEntryPlansPageVisitors_social_wow, adobe_byodEntryPlansPageVisitors_social_ly, adobe_byodEntryPlansPageVisitors_social_wow_pct, adobe_byodEntryPlansPageVisitors_social_yoy_pct,
  adobe_byodEntryOtherPageVisitors_social, adobe_byodEntryOtherPageVisitors_social_wow, adobe_byodEntryOtherPageVisitors_social_ly, adobe_byodEntryOtherPageVisitors_social_wow_pct, adobe_byodEntryOtherPageVisitors_social_yoy_pct,
  adobe_byodEntryStorePageVisitors_social, adobe_byodEntryStorePageVisitors_social_wow, adobe_byodEntryStorePageVisitors_social_ly, adobe_byodEntryStorePageVisitors_social_wow_pct, adobe_byodEntryStorePageVisitors_social_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_social, adobe_byodEntryByodLandingPageVisitors_social_wow, adobe_byodEntryByodLandingPageVisitors_social_ly, adobe_byodEntryByodLandingPageVisitors_social_wow_pct, adobe_byodEntryByodLandingPageVisitors_social_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_social, adobe_byodEntryOffersSwitchVisitors_social_wow, adobe_byodEntryOffersSwitchVisitors_social_ly, adobe_byodEntryOffersSwitchVisitors_social_wow_pct, adobe_byodEntryOffersSwitchVisitors_social_yoy_pct,  -- NEW
  -- PROGRAMMATIC
  adobe_byodUvnbVisitors_programmatic, adobe_byodUvnbVisitors_programmatic_wow, adobe_byodUvnbVisitors_programmatic_ly, adobe_byodUvnbVisitors_programmatic_wow_pct, adobe_byodUvnbVisitors_programmatic_yoy_pct,
  adobe_byodEntryByodPageVisitors_programmatic, adobe_byodEntryByodPageVisitors_programmatic_wow, adobe_byodEntryByodPageVisitors_programmatic_ly, adobe_byodEntryByodPageVisitors_programmatic_wow_pct, adobe_byodEntryByodPageVisitors_programmatic_yoy_pct,
  adobe_byodEntryHomePageVisitors_programmatic, adobe_byodEntryHomePageVisitors_programmatic_wow, adobe_byodEntryHomePageVisitors_programmatic_ly, adobe_byodEntryHomePageVisitors_programmatic_wow_pct, adobe_byodEntryHomePageVisitors_programmatic_yoy_pct,
  adobe_byodEntryDevicePageVisitors_programmatic, adobe_byodEntryDevicePageVisitors_programmatic_wow, adobe_byodEntryDevicePageVisitors_programmatic_ly, adobe_byodEntryDevicePageVisitors_programmatic_wow_pct, adobe_byodEntryDevicePageVisitors_programmatic_yoy_pct,
  adobe_byodEntryPlansPageVisitors_programmatic, adobe_byodEntryPlansPageVisitors_programmatic_wow, adobe_byodEntryPlansPageVisitors_programmatic_ly, adobe_byodEntryPlansPageVisitors_programmatic_wow_pct, adobe_byodEntryPlansPageVisitors_programmatic_yoy_pct,
  adobe_byodEntryOtherPageVisitors_programmatic, adobe_byodEntryOtherPageVisitors_programmatic_wow, adobe_byodEntryOtherPageVisitors_programmatic_ly, adobe_byodEntryOtherPageVisitors_programmatic_wow_pct, adobe_byodEntryOtherPageVisitors_programmatic_yoy_pct,
  adobe_byodEntryStorePageVisitors_programmatic, adobe_byodEntryStorePageVisitors_programmatic_wow, adobe_byodEntryStorePageVisitors_programmatic_ly, adobe_byodEntryStorePageVisitors_programmatic_wow_pct, adobe_byodEntryStorePageVisitors_programmatic_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_programmatic, adobe_byodEntryByodLandingPageVisitors_programmatic_wow, adobe_byodEntryByodLandingPageVisitors_programmatic_ly, adobe_byodEntryByodLandingPageVisitors_programmatic_wow_pct, adobe_byodEntryByodLandingPageVisitors_programmatic_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_programmatic, adobe_byodEntryOffersSwitchVisitors_programmatic_wow, adobe_byodEntryOffersSwitchVisitors_programmatic_ly, adobe_byodEntryOffersSwitchVisitors_programmatic_wow_pct, adobe_byodEntryOffersSwitchVisitors_programmatic_yoy_pct,  -- NEW
  -- OTHER
  adobe_byodUvnbVisitors_other, adobe_byodUvnbVisitors_other_wow, adobe_byodUvnbVisitors_other_ly, adobe_byodUvnbVisitors_other_wow_pct, adobe_byodUvnbVisitors_other_yoy_pct,
  adobe_byodEntryByodPageVisitors_other, adobe_byodEntryByodPageVisitors_other_wow, adobe_byodEntryByodPageVisitors_other_ly, adobe_byodEntryByodPageVisitors_other_wow_pct, adobe_byodEntryByodPageVisitors_other_yoy_pct,
  adobe_byodEntryHomePageVisitors_other, adobe_byodEntryHomePageVisitors_other_wow, adobe_byodEntryHomePageVisitors_other_ly, adobe_byodEntryHomePageVisitors_other_wow_pct, adobe_byodEntryHomePageVisitors_other_yoy_pct,
  adobe_byodEntryDevicePageVisitors_other, adobe_byodEntryDevicePageVisitors_other_wow, adobe_byodEntryDevicePageVisitors_other_ly, adobe_byodEntryDevicePageVisitors_other_wow_pct, adobe_byodEntryDevicePageVisitors_other_yoy_pct,
  adobe_byodEntryPlansPageVisitors_other, adobe_byodEntryPlansPageVisitors_other_wow, adobe_byodEntryPlansPageVisitors_other_ly, adobe_byodEntryPlansPageVisitors_other_wow_pct, adobe_byodEntryPlansPageVisitors_other_yoy_pct,
  adobe_byodEntryOtherPageVisitors_other, adobe_byodEntryOtherPageVisitors_other_wow, adobe_byodEntryOtherPageVisitors_other_ly, adobe_byodEntryOtherPageVisitors_other_wow_pct, adobe_byodEntryOtherPageVisitors_other_yoy_pct,
  adobe_byodEntryStorePageVisitors_other, adobe_byodEntryStorePageVisitors_other_wow, adobe_byodEntryStorePageVisitors_other_ly, adobe_byodEntryStorePageVisitors_other_wow_pct, adobe_byodEntryStorePageVisitors_other_yoy_pct,  -- NEW
  adobe_byodEntryByodLandingPageVisitors_other, adobe_byodEntryByodLandingPageVisitors_other_wow, adobe_byodEntryByodLandingPageVisitors_other_ly, adobe_byodEntryByodLandingPageVisitors_other_wow_pct, adobe_byodEntryByodLandingPageVisitors_other_yoy_pct,  -- NEW
  adobe_byodEntryOffersSwitchVisitors_other, adobe_byodEntryOffersSwitchVisitors_other_wow, adobe_byodEntryOffersSwitchVisitors_other_ly, adobe_byodEntryOffersSwitchVisitors_other_wow_pct, adobe_byodEntryOffersSwitchVisitors_other_yoy_pct,  -- NEW
FROM with_max_date
;