/* =================================================================================================
FILE:         08_vw_sdi_pulseByod_silver_adobeByodOutcomes_weekly.sql
LAYER:        Silver View
DATASET:      prj-dbi-prd-1.ds_dbi_digitalmedia_automation
VIEW NAME:    vw_sdi_pulseByod_silver_adobeByodOutcomes_weekly

SOURCE:
  prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_adobe_silver_byodFlowOutcomesByChannelGroupsPlusAll_Weekly

DESTINATION:
  prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseByod_silver_adobeByodOutcomes_weekly

PURPOSE:
  Silver view for Adobe Analytics BYOD funnel outcome metrics.
  Outputs a WIDE table — one row per week_sun_to_sat.
  Pivots ChannelGroup rows into columns so each channel
  becomes its own set of prefixed metric columns.
  Applies WoW/LY comparisons and max_data_date.

  Outcome metrics track what BYOD visitors did after entering the site:
    byodVrChatVisitors      — engaged via virtual/chat support
    byodCallVisitors        — engaged via phone call
    byodStoreLocatorVisitors — used store locator
    byodInternalTmoVisitors — identified as internal T-Mobile traffic
    byodBouncersVisitors    — bounced without meaningful engagement
    byodOrders              — completed a BYOD order (count of orders, not visitors)

BUSINESS GRAIN:
  One row per week_sun_to_sat

SOURCE GRAIN:
  One row per WeekSunSat + ChannelGroup
  ChannelGroup values: ALL, PAID SEARCH, ORGANIC SEARCH,
                       DIRECT, SOCIAL, PROGRAMMATIC, OTHER

COLUMN NAMING CONVENTION:
  adobe_{metric}_{channel}
  Channel suffixes: allChannels, paidSearch, organicSearch, direct, social, programmatic, other

BUSINESS LOGIC:
  - No derived/ratio metrics — all metrics are raw visitor/order counts
  - WoW: self-join on week_sun_to_sat - 7 days (gap-safe)
  - LY:  self-join on custom_week_num - 52 (gap-safe, Sun-to-Sat anchor)
  - wow_pct / yoy_pct as decimals — NULL when prior NULL or 0
  - max_data_date: latest week_sun_to_sat with any non-null metric

CUSTOM WEEK NUMBER:
  custom_week_num = DATE_DIFF(DATE_SUB(week_sun_to_sat, INTERVAL 6 DAY), DATE '2023-01-01', WEEK)
  LY match: current.custom_week_num - prior.custom_week_num = 52

DOWNSTREAM:
  Gold Wide : vw_sdi_pulseByod_gold_unified_wide
  Gold Long : vw_sdi_pulseByod_gold_unified_long
================================================================================================= */

CREATE OR REPLACE VIEW `prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_pulseByod_silver_adobeByodOutcomes_weekly`
AS

-- -----------------------------------------------------------------------
-- STEP 1: Extract metrics per channel row
-- -----------------------------------------------------------------------
WITH base AS (
  SELECT
    WeekSunSat               AS week_sun_to_sat,
    ChannelGroup,
    ByodVrChatVisitors,
    ByodCallVisitors,
    ByodStoreLocatorVisitors,
    ByodInternalTmoVisitors,
    ByodBouncersVisitors,
    ByodOrders
  FROM `prj-dbi-prd-1.ds_dbi_digitalmedia_automation.vw_sdi_adobe_silver_byodFlowOutcomesByChannelGroupsPlusAll_Weekly`
),

-- -----------------------------------------------------------------------
-- STEP 2: Pivot long → wide (one row per week)
-- -----------------------------------------------------------------------
pivoted AS (
  SELECT
    week_sun_to_sat,
    MAX(CASE WHEN ChannelGroup = 'ALL'            THEN ByodVrChatVisitors      END) AS adobe_byodVrChatVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'ALL'            THEN ByodCallVisitors         END) AS adobe_byodCallVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'ALL'            THEN ByodStoreLocatorVisitors END) AS adobe_byodStoreLocatorVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'ALL'            THEN ByodInternalTmoVisitors  END) AS adobe_byodInternalTmoVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'ALL'            THEN ByodBouncersVisitors     END) AS adobe_byodBouncersVisitors_allChannels,
    MAX(CASE WHEN ChannelGroup = 'ALL'            THEN ByodOrders               END) AS adobe_byodOrders_allChannels,
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH'    THEN ByodVrChatVisitors      END) AS adobe_byodVrChatVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH'    THEN ByodCallVisitors         END) AS adobe_byodCallVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH'    THEN ByodStoreLocatorVisitors END) AS adobe_byodStoreLocatorVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH'    THEN ByodInternalTmoVisitors  END) AS adobe_byodInternalTmoVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH'    THEN ByodBouncersVisitors     END) AS adobe_byodBouncersVisitors_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'PAID SEARCH'    THEN ByodOrders               END) AS adobe_byodOrders_paidSearch,
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodVrChatVisitors      END) AS adobe_byodVrChatVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodCallVisitors         END) AS adobe_byodCallVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodStoreLocatorVisitors END) AS adobe_byodStoreLocatorVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodInternalTmoVisitors  END) AS adobe_byodInternalTmoVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodBouncersVisitors     END) AS adobe_byodBouncersVisitors_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'ORGANIC SEARCH' THEN ByodOrders               END) AS adobe_byodOrders_organicSearch,
    MAX(CASE WHEN ChannelGroup = 'DIRECT'         THEN ByodVrChatVisitors      END) AS adobe_byodVrChatVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'DIRECT'         THEN ByodCallVisitors         END) AS adobe_byodCallVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'DIRECT'         THEN ByodStoreLocatorVisitors END) AS adobe_byodStoreLocatorVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'DIRECT'         THEN ByodInternalTmoVisitors  END) AS adobe_byodInternalTmoVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'DIRECT'         THEN ByodBouncersVisitors     END) AS adobe_byodBouncersVisitors_direct,
    MAX(CASE WHEN ChannelGroup = 'DIRECT'         THEN ByodOrders               END) AS adobe_byodOrders_direct,
    MAX(CASE WHEN ChannelGroup = 'SOCIAL'         THEN ByodVrChatVisitors      END) AS adobe_byodVrChatVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'SOCIAL'         THEN ByodCallVisitors         END) AS adobe_byodCallVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'SOCIAL'         THEN ByodStoreLocatorVisitors END) AS adobe_byodStoreLocatorVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'SOCIAL'         THEN ByodInternalTmoVisitors  END) AS adobe_byodInternalTmoVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'SOCIAL'         THEN ByodBouncersVisitors     END) AS adobe_byodBouncersVisitors_social,
    MAX(CASE WHEN ChannelGroup = 'SOCIAL'         THEN ByodOrders               END) AS adobe_byodOrders_social,
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC'   THEN ByodVrChatVisitors      END) AS adobe_byodVrChatVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC'   THEN ByodCallVisitors         END) AS adobe_byodCallVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC'   THEN ByodStoreLocatorVisitors END) AS adobe_byodStoreLocatorVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC'   THEN ByodInternalTmoVisitors  END) AS adobe_byodInternalTmoVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC'   THEN ByodBouncersVisitors     END) AS adobe_byodBouncersVisitors_programmatic,
    MAX(CASE WHEN ChannelGroup = 'PROGRAMMATIC'   THEN ByodOrders               END) AS adobe_byodOrders_programmatic,
    MAX(CASE WHEN ChannelGroup = 'OTHER'          THEN ByodVrChatVisitors      END) AS adobe_byodVrChatVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'OTHER'          THEN ByodCallVisitors         END) AS adobe_byodCallVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'OTHER'          THEN ByodStoreLocatorVisitors END) AS adobe_byodStoreLocatorVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'OTHER'          THEN ByodInternalTmoVisitors  END) AS adobe_byodInternalTmoVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'OTHER'          THEN ByodBouncersVisitors     END) AS adobe_byodBouncersVisitors_other,
    MAX(CASE WHEN ChannelGroup = 'OTHER'          THEN ByodOrders               END) AS adobe_byodOrders_other
  FROM base
  GROUP BY week_sun_to_sat
),

-- -----------------------------------------------------------------------
-- STEP 3: Custom week number for gap-safe LY matching
-- -----------------------------------------------------------------------
with_week_num AS (
  SELECT
    *,
    DATE_DIFF(DATE_SUB(week_sun_to_sat, INTERVAL 6 DAY), DATE '2023-01-01', WEEK) AS custom_week_num
  FROM pivoted
),

-- -----------------------------------------------------------------------
-- STEP 4: WoW and LY self-joins
-- -----------------------------------------------------------------------
with_comparisons AS (
  SELECT
    c.week_sun_to_sat, c.custom_week_num,
    -- ALL CHANNELS
    c.adobe_byodVrChatVisitors_allChannels,       w.adobe_byodVrChatVisitors_allChannels       AS adobe_byodVrChatVisitors_allChannels_wow,       l.adobe_byodVrChatVisitors_allChannels       AS adobe_byodVrChatVisitors_allChannels_ly,
    c.adobe_byodCallVisitors_allChannels,          w.adobe_byodCallVisitors_allChannels          AS adobe_byodCallVisitors_allChannels_wow,          l.adobe_byodCallVisitors_allChannels          AS adobe_byodCallVisitors_allChannels_ly,
    c.adobe_byodStoreLocatorVisitors_allChannels,  w.adobe_byodStoreLocatorVisitors_allChannels  AS adobe_byodStoreLocatorVisitors_allChannels_wow,  l.adobe_byodStoreLocatorVisitors_allChannels  AS adobe_byodStoreLocatorVisitors_allChannels_ly,
    c.adobe_byodInternalTmoVisitors_allChannels,   w.adobe_byodInternalTmoVisitors_allChannels   AS adobe_byodInternalTmoVisitors_allChannels_wow,   l.adobe_byodInternalTmoVisitors_allChannels   AS adobe_byodInternalTmoVisitors_allChannels_ly,
    c.adobe_byodBouncersVisitors_allChannels,      w.adobe_byodBouncersVisitors_allChannels      AS adobe_byodBouncersVisitors_allChannels_wow,      l.adobe_byodBouncersVisitors_allChannels      AS adobe_byodBouncersVisitors_allChannels_ly,
    c.adobe_byodOrders_allChannels,                w.adobe_byodOrders_allChannels                AS adobe_byodOrders_allChannels_wow,                l.adobe_byodOrders_allChannels                AS adobe_byodOrders_allChannels_ly,
    -- PAID SEARCH
    c.adobe_byodVrChatVisitors_paidSearch,         w.adobe_byodVrChatVisitors_paidSearch         AS adobe_byodVrChatVisitors_paidSearch_wow,         l.adobe_byodVrChatVisitors_paidSearch         AS adobe_byodVrChatVisitors_paidSearch_ly,
    c.adobe_byodCallVisitors_paidSearch,           w.adobe_byodCallVisitors_paidSearch           AS adobe_byodCallVisitors_paidSearch_wow,           l.adobe_byodCallVisitors_paidSearch           AS adobe_byodCallVisitors_paidSearch_ly,
    c.adobe_byodStoreLocatorVisitors_paidSearch,   w.adobe_byodStoreLocatorVisitors_paidSearch   AS adobe_byodStoreLocatorVisitors_paidSearch_wow,   l.adobe_byodStoreLocatorVisitors_paidSearch   AS adobe_byodStoreLocatorVisitors_paidSearch_ly,
    c.adobe_byodInternalTmoVisitors_paidSearch,    w.adobe_byodInternalTmoVisitors_paidSearch    AS adobe_byodInternalTmoVisitors_paidSearch_wow,    l.adobe_byodInternalTmoVisitors_paidSearch    AS adobe_byodInternalTmoVisitors_paidSearch_ly,
    c.adobe_byodBouncersVisitors_paidSearch,       w.adobe_byodBouncersVisitors_paidSearch       AS adobe_byodBouncersVisitors_paidSearch_wow,       l.adobe_byodBouncersVisitors_paidSearch       AS adobe_byodBouncersVisitors_paidSearch_ly,
    c.adobe_byodOrders_paidSearch,                 w.adobe_byodOrders_paidSearch                 AS adobe_byodOrders_paidSearch_wow,                 l.adobe_byodOrders_paidSearch                 AS adobe_byodOrders_paidSearch_ly,
    -- ORGANIC SEARCH
    c.adobe_byodVrChatVisitors_organicSearch,      w.adobe_byodVrChatVisitors_organicSearch      AS adobe_byodVrChatVisitors_organicSearch_wow,      l.adobe_byodVrChatVisitors_organicSearch      AS adobe_byodVrChatVisitors_organicSearch_ly,
    c.adobe_byodCallVisitors_organicSearch,        w.adobe_byodCallVisitors_organicSearch        AS adobe_byodCallVisitors_organicSearch_wow,        l.adobe_byodCallVisitors_organicSearch        AS adobe_byodCallVisitors_organicSearch_ly,
    c.adobe_byodStoreLocatorVisitors_organicSearch,w.adobe_byodStoreLocatorVisitors_organicSearch AS adobe_byodStoreLocatorVisitors_organicSearch_wow,l.adobe_byodStoreLocatorVisitors_organicSearch AS adobe_byodStoreLocatorVisitors_organicSearch_ly,
    c.adobe_byodInternalTmoVisitors_organicSearch, w.adobe_byodInternalTmoVisitors_organicSearch  AS adobe_byodInternalTmoVisitors_organicSearch_wow, l.adobe_byodInternalTmoVisitors_organicSearch  AS adobe_byodInternalTmoVisitors_organicSearch_ly,
    c.adobe_byodBouncersVisitors_organicSearch,    w.adobe_byodBouncersVisitors_organicSearch    AS adobe_byodBouncersVisitors_organicSearch_wow,    l.adobe_byodBouncersVisitors_organicSearch    AS adobe_byodBouncersVisitors_organicSearch_ly,
    c.adobe_byodOrders_organicSearch,              w.adobe_byodOrders_organicSearch              AS adobe_byodOrders_organicSearch_wow,              l.adobe_byodOrders_organicSearch              AS adobe_byodOrders_organicSearch_ly,
    -- DIRECT
    c.adobe_byodVrChatVisitors_direct,             w.adobe_byodVrChatVisitors_direct             AS adobe_byodVrChatVisitors_direct_wow,             l.adobe_byodVrChatVisitors_direct             AS adobe_byodVrChatVisitors_direct_ly,
    c.adobe_byodCallVisitors_direct,               w.adobe_byodCallVisitors_direct               AS adobe_byodCallVisitors_direct_wow,               l.adobe_byodCallVisitors_direct               AS adobe_byodCallVisitors_direct_ly,
    c.adobe_byodStoreLocatorVisitors_direct,       w.adobe_byodStoreLocatorVisitors_direct       AS adobe_byodStoreLocatorVisitors_direct_wow,       l.adobe_byodStoreLocatorVisitors_direct       AS adobe_byodStoreLocatorVisitors_direct_ly,
    c.adobe_byodInternalTmoVisitors_direct,        w.adobe_byodInternalTmoVisitors_direct        AS adobe_byodInternalTmoVisitors_direct_wow,        l.adobe_byodInternalTmoVisitors_direct        AS adobe_byodInternalTmoVisitors_direct_ly,
    c.adobe_byodBouncersVisitors_direct,           w.adobe_byodBouncersVisitors_direct           AS adobe_byodBouncersVisitors_direct_wow,           l.adobe_byodBouncersVisitors_direct           AS adobe_byodBouncersVisitors_direct_ly,
    c.adobe_byodOrders_direct,                     w.adobe_byodOrders_direct                     AS adobe_byodOrders_direct_wow,                     l.adobe_byodOrders_direct                     AS adobe_byodOrders_direct_ly,
    -- SOCIAL
    c.adobe_byodVrChatVisitors_social,             w.adobe_byodVrChatVisitors_social             AS adobe_byodVrChatVisitors_social_wow,             l.adobe_byodVrChatVisitors_social             AS adobe_byodVrChatVisitors_social_ly,
    c.adobe_byodCallVisitors_social,               w.adobe_byodCallVisitors_social               AS adobe_byodCallVisitors_social_wow,               l.adobe_byodCallVisitors_social               AS adobe_byodCallVisitors_social_ly,
    c.adobe_byodStoreLocatorVisitors_social,       w.adobe_byodStoreLocatorVisitors_social       AS adobe_byodStoreLocatorVisitors_social_wow,       l.adobe_byodStoreLocatorVisitors_social       AS adobe_byodStoreLocatorVisitors_social_ly,
    c.adobe_byodInternalTmoVisitors_social,        w.adobe_byodInternalTmoVisitors_social        AS adobe_byodInternalTmoVisitors_social_wow,        l.adobe_byodInternalTmoVisitors_social        AS adobe_byodInternalTmoVisitors_social_ly,
    c.adobe_byodBouncersVisitors_social,           w.adobe_byodBouncersVisitors_social           AS adobe_byodBouncersVisitors_social_wow,           l.adobe_byodBouncersVisitors_social           AS adobe_byodBouncersVisitors_social_ly,
    c.adobe_byodOrders_social,                     w.adobe_byodOrders_social                     AS adobe_byodOrders_social_wow,                     l.adobe_byodOrders_social                     AS adobe_byodOrders_social_ly,
    -- PROGRAMMATIC
    c.adobe_byodVrChatVisitors_programmatic,       w.adobe_byodVrChatVisitors_programmatic       AS adobe_byodVrChatVisitors_programmatic_wow,       l.adobe_byodVrChatVisitors_programmatic       AS adobe_byodVrChatVisitors_programmatic_ly,
    c.adobe_byodCallVisitors_programmatic,         w.adobe_byodCallVisitors_programmatic         AS adobe_byodCallVisitors_programmatic_wow,         l.adobe_byodCallVisitors_programmatic         AS adobe_byodCallVisitors_programmatic_ly,
    c.adobe_byodStoreLocatorVisitors_programmatic, w.adobe_byodStoreLocatorVisitors_programmatic AS adobe_byodStoreLocatorVisitors_programmatic_wow, l.adobe_byodStoreLocatorVisitors_programmatic AS adobe_byodStoreLocatorVisitors_programmatic_ly,
    c.adobe_byodInternalTmoVisitors_programmatic,  w.adobe_byodInternalTmoVisitors_programmatic  AS adobe_byodInternalTmoVisitors_programmatic_wow,  l.adobe_byodInternalTmoVisitors_programmatic  AS adobe_byodInternalTmoVisitors_programmatic_ly,
    c.adobe_byodBouncersVisitors_programmatic,     w.adobe_byodBouncersVisitors_programmatic     AS adobe_byodBouncersVisitors_programmatic_wow,     l.adobe_byodBouncersVisitors_programmatic     AS adobe_byodBouncersVisitors_programmatic_ly,
    c.adobe_byodOrders_programmatic,               w.adobe_byodOrders_programmatic               AS adobe_byodOrders_programmatic_wow,               l.adobe_byodOrders_programmatic               AS adobe_byodOrders_programmatic_ly,
    -- OTHER
    c.adobe_byodVrChatVisitors_other,              w.adobe_byodVrChatVisitors_other              AS adobe_byodVrChatVisitors_other_wow,              l.adobe_byodVrChatVisitors_other              AS adobe_byodVrChatVisitors_other_ly,
    c.adobe_byodCallVisitors_other,                w.adobe_byodCallVisitors_other                AS adobe_byodCallVisitors_other_wow,                l.adobe_byodCallVisitors_other                AS adobe_byodCallVisitors_other_ly,
    c.adobe_byodStoreLocatorVisitors_other,        w.adobe_byodStoreLocatorVisitors_other        AS adobe_byodStoreLocatorVisitors_other_wow,        l.adobe_byodStoreLocatorVisitors_other        AS adobe_byodStoreLocatorVisitors_other_ly,
    c.adobe_byodInternalTmoVisitors_other,         w.adobe_byodInternalTmoVisitors_other         AS adobe_byodInternalTmoVisitors_other_wow,         l.adobe_byodInternalTmoVisitors_other         AS adobe_byodInternalTmoVisitors_other_ly,
    c.adobe_byodBouncersVisitors_other,            w.adobe_byodBouncersVisitors_other            AS adobe_byodBouncersVisitors_other_wow,            l.adobe_byodBouncersVisitors_other            AS adobe_byodBouncersVisitors_other_ly,
    c.adobe_byodOrders_other,                      w.adobe_byodOrders_other                      AS adobe_byodOrders_other_wow,                      l.adobe_byodOrders_other                      AS adobe_byodOrders_other_ly
  FROM with_week_num c
  LEFT JOIN with_week_num w ON c.week_sun_to_sat = DATE_ADD(w.week_sun_to_sat, INTERVAL 7 DAY)
  LEFT JOIN with_week_num l ON (c.custom_week_num - l.custom_week_num) = 52
),

-- -----------------------------------------------------------------------
-- STEP 5: wow_pct and yoy_pct for all metrics
-- NULL when prior is NULL or 0 — no fake zeroes
-- -----------------------------------------------------------------------
with_pcts AS (
  SELECT
    week_sun_to_sat, custom_week_num,
    -- ALL CHANNELS
    adobe_byodVrChatVisitors_allChannels,      adobe_byodVrChatVisitors_allChannels_wow,      adobe_byodVrChatVisitors_allChannels_ly,      CASE WHEN adobe_byodVrChatVisitors_allChannels_wow      IS NULL OR adobe_byodVrChatVisitors_allChannels_wow      = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_allChannels      - adobe_byodVrChatVisitors_allChannels_wow)      / adobe_byodVrChatVisitors_allChannels_wow,      6) END AS adobe_byodVrChatVisitors_allChannels_wow_pct,      CASE WHEN adobe_byodVrChatVisitors_allChannels_ly      IS NULL OR adobe_byodVrChatVisitors_allChannels_ly      = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_allChannels      - adobe_byodVrChatVisitors_allChannels_ly)      / adobe_byodVrChatVisitors_allChannels_ly,      6) END AS adobe_byodVrChatVisitors_allChannels_yoy_pct,
    adobe_byodCallVisitors_allChannels,         adobe_byodCallVisitors_allChannels_wow,         adobe_byodCallVisitors_allChannels_ly,         CASE WHEN adobe_byodCallVisitors_allChannels_wow         IS NULL OR adobe_byodCallVisitors_allChannels_wow         = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_allChannels         - adobe_byodCallVisitors_allChannels_wow)         / adobe_byodCallVisitors_allChannels_wow,         6) END AS adobe_byodCallVisitors_allChannels_wow_pct,         CASE WHEN adobe_byodCallVisitors_allChannels_ly         IS NULL OR adobe_byodCallVisitors_allChannels_ly         = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_allChannels         - adobe_byodCallVisitors_allChannels_ly)         / adobe_byodCallVisitors_allChannels_ly,         6) END AS adobe_byodCallVisitors_allChannels_yoy_pct,
    adobe_byodStoreLocatorVisitors_allChannels, adobe_byodStoreLocatorVisitors_allChannels_wow, adobe_byodStoreLocatorVisitors_allChannels_ly, CASE WHEN adobe_byodStoreLocatorVisitors_allChannels_wow IS NULL OR adobe_byodStoreLocatorVisitors_allChannels_wow = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_allChannels - adobe_byodStoreLocatorVisitors_allChannels_wow) / adobe_byodStoreLocatorVisitors_allChannels_wow, 6) END AS adobe_byodStoreLocatorVisitors_allChannels_wow_pct, CASE WHEN adobe_byodStoreLocatorVisitors_allChannels_ly IS NULL OR adobe_byodStoreLocatorVisitors_allChannels_ly = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_allChannels - adobe_byodStoreLocatorVisitors_allChannels_ly) / adobe_byodStoreLocatorVisitors_allChannels_ly, 6) END AS adobe_byodStoreLocatorVisitors_allChannels_yoy_pct,
    adobe_byodInternalTmoVisitors_allChannels,  adobe_byodInternalTmoVisitors_allChannels_wow,  adobe_byodInternalTmoVisitors_allChannels_ly,  CASE WHEN adobe_byodInternalTmoVisitors_allChannels_wow  IS NULL OR adobe_byodInternalTmoVisitors_allChannels_wow  = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_allChannels  - adobe_byodInternalTmoVisitors_allChannels_wow)  / adobe_byodInternalTmoVisitors_allChannels_wow,  6) END AS adobe_byodInternalTmoVisitors_allChannels_wow_pct,  CASE WHEN adobe_byodInternalTmoVisitors_allChannels_ly  IS NULL OR adobe_byodInternalTmoVisitors_allChannels_ly  = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_allChannels  - adobe_byodInternalTmoVisitors_allChannels_ly)  / adobe_byodInternalTmoVisitors_allChannels_ly,  6) END AS adobe_byodInternalTmoVisitors_allChannels_yoy_pct,
    adobe_byodBouncersVisitors_allChannels,     adobe_byodBouncersVisitors_allChannels_wow,     adobe_byodBouncersVisitors_allChannels_ly,     CASE WHEN adobe_byodBouncersVisitors_allChannels_wow     IS NULL OR adobe_byodBouncersVisitors_allChannels_wow     = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_allChannels     - adobe_byodBouncersVisitors_allChannels_wow)     / adobe_byodBouncersVisitors_allChannels_wow,     6) END AS adobe_byodBouncersVisitors_allChannels_wow_pct,     CASE WHEN adobe_byodBouncersVisitors_allChannels_ly     IS NULL OR adobe_byodBouncersVisitors_allChannels_ly     = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_allChannels     - adobe_byodBouncersVisitors_allChannels_ly)     / adobe_byodBouncersVisitors_allChannels_ly,     6) END AS adobe_byodBouncersVisitors_allChannels_yoy_pct,
    adobe_byodOrders_allChannels,               adobe_byodOrders_allChannels_wow,               adobe_byodOrders_allChannels_ly,               CASE WHEN adobe_byodOrders_allChannels_wow               IS NULL OR adobe_byodOrders_allChannels_wow               = 0 THEN NULL ELSE ROUND((adobe_byodOrders_allChannels               - adobe_byodOrders_allChannels_wow)               / adobe_byodOrders_allChannels_wow,               6) END AS adobe_byodOrders_allChannels_wow_pct,               CASE WHEN adobe_byodOrders_allChannels_ly               IS NULL OR adobe_byodOrders_allChannels_ly               = 0 THEN NULL ELSE ROUND((adobe_byodOrders_allChannels               - adobe_byodOrders_allChannels_ly)               / adobe_byodOrders_allChannels_ly,               6) END AS adobe_byodOrders_allChannels_yoy_pct,
    -- PAID SEARCH
    adobe_byodVrChatVisitors_paidSearch,        adobe_byodVrChatVisitors_paidSearch_wow,        adobe_byodVrChatVisitors_paidSearch_ly,        CASE WHEN adobe_byodVrChatVisitors_paidSearch_wow        IS NULL OR adobe_byodVrChatVisitors_paidSearch_wow        = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_paidSearch        - adobe_byodVrChatVisitors_paidSearch_wow)        / adobe_byodVrChatVisitors_paidSearch_wow,        6) END AS adobe_byodVrChatVisitors_paidSearch_wow_pct,        CASE WHEN adobe_byodVrChatVisitors_paidSearch_ly        IS NULL OR adobe_byodVrChatVisitors_paidSearch_ly        = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_paidSearch        - adobe_byodVrChatVisitors_paidSearch_ly)        / adobe_byodVrChatVisitors_paidSearch_ly,        6) END AS adobe_byodVrChatVisitors_paidSearch_yoy_pct,
    adobe_byodCallVisitors_paidSearch,          adobe_byodCallVisitors_paidSearch_wow,          adobe_byodCallVisitors_paidSearch_ly,          CASE WHEN adobe_byodCallVisitors_paidSearch_wow          IS NULL OR adobe_byodCallVisitors_paidSearch_wow          = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_paidSearch          - adobe_byodCallVisitors_paidSearch_wow)          / adobe_byodCallVisitors_paidSearch_wow,          6) END AS adobe_byodCallVisitors_paidSearch_wow_pct,          CASE WHEN adobe_byodCallVisitors_paidSearch_ly          IS NULL OR adobe_byodCallVisitors_paidSearch_ly          = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_paidSearch          - adobe_byodCallVisitors_paidSearch_ly)          / adobe_byodCallVisitors_paidSearch_ly,          6) END AS adobe_byodCallVisitors_paidSearch_yoy_pct,
    adobe_byodStoreLocatorVisitors_paidSearch,  adobe_byodStoreLocatorVisitors_paidSearch_wow,  adobe_byodStoreLocatorVisitors_paidSearch_ly,  CASE WHEN adobe_byodStoreLocatorVisitors_paidSearch_wow  IS NULL OR adobe_byodStoreLocatorVisitors_paidSearch_wow  = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_paidSearch  - adobe_byodStoreLocatorVisitors_paidSearch_wow)  / adobe_byodStoreLocatorVisitors_paidSearch_wow,  6) END AS adobe_byodStoreLocatorVisitors_paidSearch_wow_pct,  CASE WHEN adobe_byodStoreLocatorVisitors_paidSearch_ly  IS NULL OR adobe_byodStoreLocatorVisitors_paidSearch_ly  = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_paidSearch  - adobe_byodStoreLocatorVisitors_paidSearch_ly)  / adobe_byodStoreLocatorVisitors_paidSearch_ly,  6) END AS adobe_byodStoreLocatorVisitors_paidSearch_yoy_pct,
    adobe_byodInternalTmoVisitors_paidSearch,   adobe_byodInternalTmoVisitors_paidSearch_wow,   adobe_byodInternalTmoVisitors_paidSearch_ly,   CASE WHEN adobe_byodInternalTmoVisitors_paidSearch_wow   IS NULL OR adobe_byodInternalTmoVisitors_paidSearch_wow   = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_paidSearch   - adobe_byodInternalTmoVisitors_paidSearch_wow)   / adobe_byodInternalTmoVisitors_paidSearch_wow,   6) END AS adobe_byodInternalTmoVisitors_paidSearch_wow_pct,   CASE WHEN adobe_byodInternalTmoVisitors_paidSearch_ly   IS NULL OR adobe_byodInternalTmoVisitors_paidSearch_ly   = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_paidSearch   - adobe_byodInternalTmoVisitors_paidSearch_ly)   / adobe_byodInternalTmoVisitors_paidSearch_ly,   6) END AS adobe_byodInternalTmoVisitors_paidSearch_yoy_pct,
    adobe_byodBouncersVisitors_paidSearch,      adobe_byodBouncersVisitors_paidSearch_wow,      adobe_byodBouncersVisitors_paidSearch_ly,      CASE WHEN adobe_byodBouncersVisitors_paidSearch_wow      IS NULL OR adobe_byodBouncersVisitors_paidSearch_wow      = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_paidSearch      - adobe_byodBouncersVisitors_paidSearch_wow)      / adobe_byodBouncersVisitors_paidSearch_wow,      6) END AS adobe_byodBouncersVisitors_paidSearch_wow_pct,      CASE WHEN adobe_byodBouncersVisitors_paidSearch_ly      IS NULL OR adobe_byodBouncersVisitors_paidSearch_ly      = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_paidSearch      - adobe_byodBouncersVisitors_paidSearch_ly)      / adobe_byodBouncersVisitors_paidSearch_ly,      6) END AS adobe_byodBouncersVisitors_paidSearch_yoy_pct,
    adobe_byodOrders_paidSearch,                adobe_byodOrders_paidSearch_wow,                adobe_byodOrders_paidSearch_ly,                CASE WHEN adobe_byodOrders_paidSearch_wow                IS NULL OR adobe_byodOrders_paidSearch_wow                = 0 THEN NULL ELSE ROUND((adobe_byodOrders_paidSearch                - adobe_byodOrders_paidSearch_wow)                / adobe_byodOrders_paidSearch_wow,                6) END AS adobe_byodOrders_paidSearch_wow_pct,                CASE WHEN adobe_byodOrders_paidSearch_ly                IS NULL OR adobe_byodOrders_paidSearch_ly                = 0 THEN NULL ELSE ROUND((adobe_byodOrders_paidSearch                - adobe_byodOrders_paidSearch_ly)                / adobe_byodOrders_paidSearch_ly,                6) END AS adobe_byodOrders_paidSearch_yoy_pct,
    -- ORGANIC SEARCH
    adobe_byodVrChatVisitors_organicSearch,     adobe_byodVrChatVisitors_organicSearch_wow,     adobe_byodVrChatVisitors_organicSearch_ly,     CASE WHEN adobe_byodVrChatVisitors_organicSearch_wow     IS NULL OR adobe_byodVrChatVisitors_organicSearch_wow     = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_organicSearch     - adobe_byodVrChatVisitors_organicSearch_wow)     / adobe_byodVrChatVisitors_organicSearch_wow,     6) END AS adobe_byodVrChatVisitors_organicSearch_wow_pct,     CASE WHEN adobe_byodVrChatVisitors_organicSearch_ly     IS NULL OR adobe_byodVrChatVisitors_organicSearch_ly     = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_organicSearch     - adobe_byodVrChatVisitors_organicSearch_ly)     / adobe_byodVrChatVisitors_organicSearch_ly,     6) END AS adobe_byodVrChatVisitors_organicSearch_yoy_pct,
    adobe_byodCallVisitors_organicSearch,       adobe_byodCallVisitors_organicSearch_wow,       adobe_byodCallVisitors_organicSearch_ly,       CASE WHEN adobe_byodCallVisitors_organicSearch_wow       IS NULL OR adobe_byodCallVisitors_organicSearch_wow       = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_organicSearch       - adobe_byodCallVisitors_organicSearch_wow)       / adobe_byodCallVisitors_organicSearch_wow,       6) END AS adobe_byodCallVisitors_organicSearch_wow_pct,       CASE WHEN adobe_byodCallVisitors_organicSearch_ly       IS NULL OR adobe_byodCallVisitors_organicSearch_ly       = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_organicSearch       - adobe_byodCallVisitors_organicSearch_ly)       / adobe_byodCallVisitors_organicSearch_ly,       6) END AS adobe_byodCallVisitors_organicSearch_yoy_pct,
    adobe_byodStoreLocatorVisitors_organicSearch,adobe_byodStoreLocatorVisitors_organicSearch_wow,adobe_byodStoreLocatorVisitors_organicSearch_ly,CASE WHEN adobe_byodStoreLocatorVisitors_organicSearch_wow IS NULL OR adobe_byodStoreLocatorVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_organicSearch - adobe_byodStoreLocatorVisitors_organicSearch_wow) / adobe_byodStoreLocatorVisitors_organicSearch_wow, 6) END AS adobe_byodStoreLocatorVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodStoreLocatorVisitors_organicSearch_ly IS NULL OR adobe_byodStoreLocatorVisitors_organicSearch_ly = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_organicSearch - adobe_byodStoreLocatorVisitors_organicSearch_ly) / adobe_byodStoreLocatorVisitors_organicSearch_ly, 6) END AS adobe_byodStoreLocatorVisitors_organicSearch_yoy_pct,
    adobe_byodInternalTmoVisitors_organicSearch, adobe_byodInternalTmoVisitors_organicSearch_wow, adobe_byodInternalTmoVisitors_organicSearch_ly, CASE WHEN adobe_byodInternalTmoVisitors_organicSearch_wow IS NULL OR adobe_byodInternalTmoVisitors_organicSearch_wow = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_organicSearch - adobe_byodInternalTmoVisitors_organicSearch_wow) / adobe_byodInternalTmoVisitors_organicSearch_wow, 6) END AS adobe_byodInternalTmoVisitors_organicSearch_wow_pct, CASE WHEN adobe_byodInternalTmoVisitors_organicSearch_ly IS NULL OR adobe_byodInternalTmoVisitors_organicSearch_ly = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_organicSearch - adobe_byodInternalTmoVisitors_organicSearch_ly) / adobe_byodInternalTmoVisitors_organicSearch_ly, 6) END AS adobe_byodInternalTmoVisitors_organicSearch_yoy_pct,
    adobe_byodBouncersVisitors_organicSearch,   adobe_byodBouncersVisitors_organicSearch_wow,   adobe_byodBouncersVisitors_organicSearch_ly,   CASE WHEN adobe_byodBouncersVisitors_organicSearch_wow   IS NULL OR adobe_byodBouncersVisitors_organicSearch_wow   = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_organicSearch   - adobe_byodBouncersVisitors_organicSearch_wow)   / adobe_byodBouncersVisitors_organicSearch_wow,   6) END AS adobe_byodBouncersVisitors_organicSearch_wow_pct,   CASE WHEN adobe_byodBouncersVisitors_organicSearch_ly   IS NULL OR adobe_byodBouncersVisitors_organicSearch_ly   = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_organicSearch   - adobe_byodBouncersVisitors_organicSearch_ly)   / adobe_byodBouncersVisitors_organicSearch_ly,   6) END AS adobe_byodBouncersVisitors_organicSearch_yoy_pct,
    adobe_byodOrders_organicSearch,             adobe_byodOrders_organicSearch_wow,             adobe_byodOrders_organicSearch_ly,             CASE WHEN adobe_byodOrders_organicSearch_wow             IS NULL OR adobe_byodOrders_organicSearch_wow             = 0 THEN NULL ELSE ROUND((adobe_byodOrders_organicSearch             - adobe_byodOrders_organicSearch_wow)             / adobe_byodOrders_organicSearch_wow,             6) END AS adobe_byodOrders_organicSearch_wow_pct,             CASE WHEN adobe_byodOrders_organicSearch_ly             IS NULL OR adobe_byodOrders_organicSearch_ly             = 0 THEN NULL ELSE ROUND((adobe_byodOrders_organicSearch             - adobe_byodOrders_organicSearch_ly)             / adobe_byodOrders_organicSearch_ly,             6) END AS adobe_byodOrders_organicSearch_yoy_pct,
    -- DIRECT
    adobe_byodVrChatVisitors_direct,            adobe_byodVrChatVisitors_direct_wow,            adobe_byodVrChatVisitors_direct_ly,            CASE WHEN adobe_byodVrChatVisitors_direct_wow            IS NULL OR adobe_byodVrChatVisitors_direct_wow            = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_direct            - adobe_byodVrChatVisitors_direct_wow)            / adobe_byodVrChatVisitors_direct_wow,            6) END AS adobe_byodVrChatVisitors_direct_wow_pct,            CASE WHEN adobe_byodVrChatVisitors_direct_ly            IS NULL OR adobe_byodVrChatVisitors_direct_ly            = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_direct            - adobe_byodVrChatVisitors_direct_ly)            / adobe_byodVrChatVisitors_direct_ly,            6) END AS adobe_byodVrChatVisitors_direct_yoy_pct,
    adobe_byodCallVisitors_direct,              adobe_byodCallVisitors_direct_wow,              adobe_byodCallVisitors_direct_ly,              CASE WHEN adobe_byodCallVisitors_direct_wow              IS NULL OR adobe_byodCallVisitors_direct_wow              = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_direct              - adobe_byodCallVisitors_direct_wow)              / adobe_byodCallVisitors_direct_wow,              6) END AS adobe_byodCallVisitors_direct_wow_pct,              CASE WHEN adobe_byodCallVisitors_direct_ly              IS NULL OR adobe_byodCallVisitors_direct_ly              = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_direct              - adobe_byodCallVisitors_direct_ly)              / adobe_byodCallVisitors_direct_ly,              6) END AS adobe_byodCallVisitors_direct_yoy_pct,
    adobe_byodStoreLocatorVisitors_direct,      adobe_byodStoreLocatorVisitors_direct_wow,      adobe_byodStoreLocatorVisitors_direct_ly,      CASE WHEN adobe_byodStoreLocatorVisitors_direct_wow      IS NULL OR adobe_byodStoreLocatorVisitors_direct_wow      = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_direct      - adobe_byodStoreLocatorVisitors_direct_wow)      / adobe_byodStoreLocatorVisitors_direct_wow,      6) END AS adobe_byodStoreLocatorVisitors_direct_wow_pct,      CASE WHEN adobe_byodStoreLocatorVisitors_direct_ly      IS NULL OR adobe_byodStoreLocatorVisitors_direct_ly      = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_direct      - adobe_byodStoreLocatorVisitors_direct_ly)      / adobe_byodStoreLocatorVisitors_direct_ly,      6) END AS adobe_byodStoreLocatorVisitors_direct_yoy_pct,
    adobe_byodInternalTmoVisitors_direct,       adobe_byodInternalTmoVisitors_direct_wow,       adobe_byodInternalTmoVisitors_direct_ly,       CASE WHEN adobe_byodInternalTmoVisitors_direct_wow       IS NULL OR adobe_byodInternalTmoVisitors_direct_wow       = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_direct       - adobe_byodInternalTmoVisitors_direct_wow)       / adobe_byodInternalTmoVisitors_direct_wow,       6) END AS adobe_byodInternalTmoVisitors_direct_wow_pct,       CASE WHEN adobe_byodInternalTmoVisitors_direct_ly       IS NULL OR adobe_byodInternalTmoVisitors_direct_ly       = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_direct       - adobe_byodInternalTmoVisitors_direct_ly)       / adobe_byodInternalTmoVisitors_direct_ly,       6) END AS adobe_byodInternalTmoVisitors_direct_yoy_pct,
    adobe_byodBouncersVisitors_direct,          adobe_byodBouncersVisitors_direct_wow,          adobe_byodBouncersVisitors_direct_ly,          CASE WHEN adobe_byodBouncersVisitors_direct_wow          IS NULL OR adobe_byodBouncersVisitors_direct_wow          = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_direct          - adobe_byodBouncersVisitors_direct_wow)          / adobe_byodBouncersVisitors_direct_wow,          6) END AS adobe_byodBouncersVisitors_direct_wow_pct,          CASE WHEN adobe_byodBouncersVisitors_direct_ly          IS NULL OR adobe_byodBouncersVisitors_direct_ly          = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_direct          - adobe_byodBouncersVisitors_direct_ly)          / adobe_byodBouncersVisitors_direct_ly,          6) END AS adobe_byodBouncersVisitors_direct_yoy_pct,
    adobe_byodOrders_direct,                    adobe_byodOrders_direct_wow,                    adobe_byodOrders_direct_ly,                    CASE WHEN adobe_byodOrders_direct_wow                    IS NULL OR adobe_byodOrders_direct_wow                    = 0 THEN NULL ELSE ROUND((adobe_byodOrders_direct                    - adobe_byodOrders_direct_wow)                    / adobe_byodOrders_direct_wow,                    6) END AS adobe_byodOrders_direct_wow_pct,                    CASE WHEN adobe_byodOrders_direct_ly                    IS NULL OR adobe_byodOrders_direct_ly                    = 0 THEN NULL ELSE ROUND((adobe_byodOrders_direct                    - adobe_byodOrders_direct_ly)                    / adobe_byodOrders_direct_ly,                    6) END AS adobe_byodOrders_direct_yoy_pct,
    -- SOCIAL
    adobe_byodVrChatVisitors_social,            adobe_byodVrChatVisitors_social_wow,            adobe_byodVrChatVisitors_social_ly,            CASE WHEN adobe_byodVrChatVisitors_social_wow            IS NULL OR adobe_byodVrChatVisitors_social_wow            = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_social            - adobe_byodVrChatVisitors_social_wow)            / adobe_byodVrChatVisitors_social_wow,            6) END AS adobe_byodVrChatVisitors_social_wow_pct,            CASE WHEN adobe_byodVrChatVisitors_social_ly            IS NULL OR adobe_byodVrChatVisitors_social_ly            = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_social            - adobe_byodVrChatVisitors_social_ly)            / adobe_byodVrChatVisitors_social_ly,            6) END AS adobe_byodVrChatVisitors_social_yoy_pct,
    adobe_byodCallVisitors_social,              adobe_byodCallVisitors_social_wow,              adobe_byodCallVisitors_social_ly,              CASE WHEN adobe_byodCallVisitors_social_wow              IS NULL OR adobe_byodCallVisitors_social_wow              = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_social              - adobe_byodCallVisitors_social_wow)              / adobe_byodCallVisitors_social_wow,              6) END AS adobe_byodCallVisitors_social_wow_pct,              CASE WHEN adobe_byodCallVisitors_social_ly              IS NULL OR adobe_byodCallVisitors_social_ly              = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_social              - adobe_byodCallVisitors_social_ly)              / adobe_byodCallVisitors_social_ly,              6) END AS adobe_byodCallVisitors_social_yoy_pct,
    adobe_byodStoreLocatorVisitors_social,      adobe_byodStoreLocatorVisitors_social_wow,      adobe_byodStoreLocatorVisitors_social_ly,      CASE WHEN adobe_byodStoreLocatorVisitors_social_wow      IS NULL OR adobe_byodStoreLocatorVisitors_social_wow      = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_social      - adobe_byodStoreLocatorVisitors_social_wow)      / adobe_byodStoreLocatorVisitors_social_wow,      6) END AS adobe_byodStoreLocatorVisitors_social_wow_pct,      CASE WHEN adobe_byodStoreLocatorVisitors_social_ly      IS NULL OR adobe_byodStoreLocatorVisitors_social_ly      = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_social      - adobe_byodStoreLocatorVisitors_social_ly)      / adobe_byodStoreLocatorVisitors_social_ly,      6) END AS adobe_byodStoreLocatorVisitors_social_yoy_pct,
    adobe_byodInternalTmoVisitors_social,       adobe_byodInternalTmoVisitors_social_wow,       adobe_byodInternalTmoVisitors_social_ly,       CASE WHEN adobe_byodInternalTmoVisitors_social_wow       IS NULL OR adobe_byodInternalTmoVisitors_social_wow       = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_social       - adobe_byodInternalTmoVisitors_social_wow)       / adobe_byodInternalTmoVisitors_social_wow,       6) END AS adobe_byodInternalTmoVisitors_social_wow_pct,       CASE WHEN adobe_byodInternalTmoVisitors_social_ly       IS NULL OR adobe_byodInternalTmoVisitors_social_ly       = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_social       - adobe_byodInternalTmoVisitors_social_ly)       / adobe_byodInternalTmoVisitors_social_ly,       6) END AS adobe_byodInternalTmoVisitors_social_yoy_pct,
    adobe_byodBouncersVisitors_social,          adobe_byodBouncersVisitors_social_wow,          adobe_byodBouncersVisitors_social_ly,          CASE WHEN adobe_byodBouncersVisitors_social_wow          IS NULL OR adobe_byodBouncersVisitors_social_wow          = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_social          - adobe_byodBouncersVisitors_social_wow)          / adobe_byodBouncersVisitors_social_wow,          6) END AS adobe_byodBouncersVisitors_social_wow_pct,          CASE WHEN adobe_byodBouncersVisitors_social_ly          IS NULL OR adobe_byodBouncersVisitors_social_ly          = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_social          - adobe_byodBouncersVisitors_social_ly)          / adobe_byodBouncersVisitors_social_ly,          6) END AS adobe_byodBouncersVisitors_social_yoy_pct,
    adobe_byodOrders_social,                    adobe_byodOrders_social_wow,                    adobe_byodOrders_social_ly,                    CASE WHEN adobe_byodOrders_social_wow                    IS NULL OR adobe_byodOrders_social_wow                    = 0 THEN NULL ELSE ROUND((adobe_byodOrders_social                    - adobe_byodOrders_social_wow)                    / adobe_byodOrders_social_wow,                    6) END AS adobe_byodOrders_social_wow_pct,                    CASE WHEN adobe_byodOrders_social_ly                    IS NULL OR adobe_byodOrders_social_ly                    = 0 THEN NULL ELSE ROUND((adobe_byodOrders_social                    - adobe_byodOrders_social_ly)                    / adobe_byodOrders_social_ly,                    6) END AS adobe_byodOrders_social_yoy_pct,
    -- PROGRAMMATIC
    adobe_byodVrChatVisitors_programmatic,      adobe_byodVrChatVisitors_programmatic_wow,      adobe_byodVrChatVisitors_programmatic_ly,      CASE WHEN adobe_byodVrChatVisitors_programmatic_wow      IS NULL OR adobe_byodVrChatVisitors_programmatic_wow      = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_programmatic      - adobe_byodVrChatVisitors_programmatic_wow)      / adobe_byodVrChatVisitors_programmatic_wow,      6) END AS adobe_byodVrChatVisitors_programmatic_wow_pct,      CASE WHEN adobe_byodVrChatVisitors_programmatic_ly      IS NULL OR adobe_byodVrChatVisitors_programmatic_ly      = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_programmatic      - adobe_byodVrChatVisitors_programmatic_ly)      / adobe_byodVrChatVisitors_programmatic_ly,      6) END AS adobe_byodVrChatVisitors_programmatic_yoy_pct,
    adobe_byodCallVisitors_programmatic,        adobe_byodCallVisitors_programmatic_wow,        adobe_byodCallVisitors_programmatic_ly,        CASE WHEN adobe_byodCallVisitors_programmatic_wow        IS NULL OR adobe_byodCallVisitors_programmatic_wow        = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_programmatic        - adobe_byodCallVisitors_programmatic_wow)        / adobe_byodCallVisitors_programmatic_wow,        6) END AS adobe_byodCallVisitors_programmatic_wow_pct,        CASE WHEN adobe_byodCallVisitors_programmatic_ly        IS NULL OR adobe_byodCallVisitors_programmatic_ly        = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_programmatic        - adobe_byodCallVisitors_programmatic_ly)        / adobe_byodCallVisitors_programmatic_ly,        6) END AS adobe_byodCallVisitors_programmatic_yoy_pct,
    adobe_byodStoreLocatorVisitors_programmatic,adobe_byodStoreLocatorVisitors_programmatic_wow,adobe_byodStoreLocatorVisitors_programmatic_ly,CASE WHEN adobe_byodStoreLocatorVisitors_programmatic_wow IS NULL OR adobe_byodStoreLocatorVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_programmatic - adobe_byodStoreLocatorVisitors_programmatic_wow) / adobe_byodStoreLocatorVisitors_programmatic_wow, 6) END AS adobe_byodStoreLocatorVisitors_programmatic_wow_pct, CASE WHEN adobe_byodStoreLocatorVisitors_programmatic_ly IS NULL OR adobe_byodStoreLocatorVisitors_programmatic_ly = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_programmatic - adobe_byodStoreLocatorVisitors_programmatic_ly) / adobe_byodStoreLocatorVisitors_programmatic_ly, 6) END AS adobe_byodStoreLocatorVisitors_programmatic_yoy_pct,
    adobe_byodInternalTmoVisitors_programmatic, adobe_byodInternalTmoVisitors_programmatic_wow, adobe_byodInternalTmoVisitors_programmatic_ly, CASE WHEN adobe_byodInternalTmoVisitors_programmatic_wow IS NULL OR adobe_byodInternalTmoVisitors_programmatic_wow = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_programmatic - adobe_byodInternalTmoVisitors_programmatic_wow) / adobe_byodInternalTmoVisitors_programmatic_wow, 6) END AS adobe_byodInternalTmoVisitors_programmatic_wow_pct, CASE WHEN adobe_byodInternalTmoVisitors_programmatic_ly IS NULL OR adobe_byodInternalTmoVisitors_programmatic_ly = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_programmatic - adobe_byodInternalTmoVisitors_programmatic_ly) / adobe_byodInternalTmoVisitors_programmatic_ly, 6) END AS adobe_byodInternalTmoVisitors_programmatic_yoy_pct,
    adobe_byodBouncersVisitors_programmatic,    adobe_byodBouncersVisitors_programmatic_wow,    adobe_byodBouncersVisitors_programmatic_ly,    CASE WHEN adobe_byodBouncersVisitors_programmatic_wow    IS NULL OR adobe_byodBouncersVisitors_programmatic_wow    = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_programmatic    - adobe_byodBouncersVisitors_programmatic_wow)    / adobe_byodBouncersVisitors_programmatic_wow,    6) END AS adobe_byodBouncersVisitors_programmatic_wow_pct,    CASE WHEN adobe_byodBouncersVisitors_programmatic_ly    IS NULL OR adobe_byodBouncersVisitors_programmatic_ly    = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_programmatic    - adobe_byodBouncersVisitors_programmatic_ly)    / adobe_byodBouncersVisitors_programmatic_ly,    6) END AS adobe_byodBouncersVisitors_programmatic_yoy_pct,
    adobe_byodOrders_programmatic,              adobe_byodOrders_programmatic_wow,              adobe_byodOrders_programmatic_ly,              CASE WHEN adobe_byodOrders_programmatic_wow              IS NULL OR adobe_byodOrders_programmatic_wow              = 0 THEN NULL ELSE ROUND((adobe_byodOrders_programmatic              - adobe_byodOrders_programmatic_wow)              / adobe_byodOrders_programmatic_wow,              6) END AS adobe_byodOrders_programmatic_wow_pct,              CASE WHEN adobe_byodOrders_programmatic_ly              IS NULL OR adobe_byodOrders_programmatic_ly              = 0 THEN NULL ELSE ROUND((adobe_byodOrders_programmatic              - adobe_byodOrders_programmatic_ly)              / adobe_byodOrders_programmatic_ly,              6) END AS adobe_byodOrders_programmatic_yoy_pct,
    -- OTHER
    adobe_byodVrChatVisitors_other,             adobe_byodVrChatVisitors_other_wow,             adobe_byodVrChatVisitors_other_ly,             CASE WHEN adobe_byodVrChatVisitors_other_wow             IS NULL OR adobe_byodVrChatVisitors_other_wow             = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_other             - adobe_byodVrChatVisitors_other_wow)             / adobe_byodVrChatVisitors_other_wow,             6) END AS adobe_byodVrChatVisitors_other_wow_pct,             CASE WHEN adobe_byodVrChatVisitors_other_ly             IS NULL OR adobe_byodVrChatVisitors_other_ly             = 0 THEN NULL ELSE ROUND((adobe_byodVrChatVisitors_other             - adobe_byodVrChatVisitors_other_ly)             / adobe_byodVrChatVisitors_other_ly,             6) END AS adobe_byodVrChatVisitors_other_yoy_pct,
    adobe_byodCallVisitors_other,               adobe_byodCallVisitors_other_wow,               adobe_byodCallVisitors_other_ly,               CASE WHEN adobe_byodCallVisitors_other_wow               IS NULL OR adobe_byodCallVisitors_other_wow               = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_other               - adobe_byodCallVisitors_other_wow)               / adobe_byodCallVisitors_other_wow,               6) END AS adobe_byodCallVisitors_other_wow_pct,               CASE WHEN adobe_byodCallVisitors_other_ly               IS NULL OR adobe_byodCallVisitors_other_ly               = 0 THEN NULL ELSE ROUND((adobe_byodCallVisitors_other               - adobe_byodCallVisitors_other_ly)               / adobe_byodCallVisitors_other_ly,               6) END AS adobe_byodCallVisitors_other_yoy_pct,
    adobe_byodStoreLocatorVisitors_other,       adobe_byodStoreLocatorVisitors_other_wow,       adobe_byodStoreLocatorVisitors_other_ly,       CASE WHEN adobe_byodStoreLocatorVisitors_other_wow       IS NULL OR adobe_byodStoreLocatorVisitors_other_wow       = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_other       - adobe_byodStoreLocatorVisitors_other_wow)       / adobe_byodStoreLocatorVisitors_other_wow,       6) END AS adobe_byodStoreLocatorVisitors_other_wow_pct,       CASE WHEN adobe_byodStoreLocatorVisitors_other_ly       IS NULL OR adobe_byodStoreLocatorVisitors_other_ly       = 0 THEN NULL ELSE ROUND((adobe_byodStoreLocatorVisitors_other       - adobe_byodStoreLocatorVisitors_other_ly)       / adobe_byodStoreLocatorVisitors_other_ly,       6) END AS adobe_byodStoreLocatorVisitors_other_yoy_pct,
    adobe_byodInternalTmoVisitors_other,        adobe_byodInternalTmoVisitors_other_wow,        adobe_byodInternalTmoVisitors_other_ly,        CASE WHEN adobe_byodInternalTmoVisitors_other_wow        IS NULL OR adobe_byodInternalTmoVisitors_other_wow        = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_other        - adobe_byodInternalTmoVisitors_other_wow)        / adobe_byodInternalTmoVisitors_other_wow,        6) END AS adobe_byodInternalTmoVisitors_other_wow_pct,        CASE WHEN adobe_byodInternalTmoVisitors_other_ly        IS NULL OR adobe_byodInternalTmoVisitors_other_ly        = 0 THEN NULL ELSE ROUND((adobe_byodInternalTmoVisitors_other        - adobe_byodInternalTmoVisitors_other_ly)        / adobe_byodInternalTmoVisitors_other_ly,        6) END AS adobe_byodInternalTmoVisitors_other_yoy_pct,
    adobe_byodBouncersVisitors_other,           adobe_byodBouncersVisitors_other_wow,           adobe_byodBouncersVisitors_other_ly,           CASE WHEN adobe_byodBouncersVisitors_other_wow           IS NULL OR adobe_byodBouncersVisitors_other_wow           = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_other           - adobe_byodBouncersVisitors_other_wow)           / adobe_byodBouncersVisitors_other_wow,           6) END AS adobe_byodBouncersVisitors_other_wow_pct,           CASE WHEN adobe_byodBouncersVisitors_other_ly           IS NULL OR adobe_byodBouncersVisitors_other_ly           = 0 THEN NULL ELSE ROUND((adobe_byodBouncersVisitors_other           - adobe_byodBouncersVisitors_other_ly)           / adobe_byodBouncersVisitors_other_ly,           6) END AS adobe_byodBouncersVisitors_other_yoy_pct,
    adobe_byodOrders_other,                     adobe_byodOrders_other_wow,                     adobe_byodOrders_other_ly,                     CASE WHEN adobe_byodOrders_other_wow                     IS NULL OR adobe_byodOrders_other_wow                     = 0 THEN NULL ELSE ROUND((adobe_byodOrders_other                     - adobe_byodOrders_other_wow)                     / adobe_byodOrders_other_wow,                     6) END AS adobe_byodOrders_other_wow_pct,                     CASE WHEN adobe_byodOrders_other_ly                     IS NULL OR adobe_byodOrders_other_ly                     = 0 THEN NULL ELSE ROUND((adobe_byodOrders_other                     - adobe_byodOrders_other_ly)                     / adobe_byodOrders_other_ly,                     6) END AS adobe_byodOrders_other_yoy_pct
  FROM with_comparisons
),

-- -----------------------------------------------------------------------
-- STEP 6: max_data_date
-- -----------------------------------------------------------------------
with_max_date AS (
  SELECT
    *,
    MAX(CASE WHEN adobe_byodVrChatVisitors_allChannels IS NOT NULL THEN week_sun_to_sat END) OVER () AS max_data_date
  FROM with_pcts
)

-- -----------------------------------------------------------------------
-- FINAL OUTPUT — wide table, one row per week
-- -----------------------------------------------------------------------
SELECT
  week_sun_to_sat,
  'ADOBE_BYOD_OUTCOMES'  AS data_source,
  max_data_date,
  -- ALL CHANNELS
  adobe_byodVrChatVisitors_allChannels,      adobe_byodVrChatVisitors_allChannels_wow,      adobe_byodVrChatVisitors_allChannels_ly,      adobe_byodVrChatVisitors_allChannels_wow_pct,      adobe_byodVrChatVisitors_allChannels_yoy_pct,
  adobe_byodCallVisitors_allChannels,         adobe_byodCallVisitors_allChannels_wow,         adobe_byodCallVisitors_allChannels_ly,         adobe_byodCallVisitors_allChannels_wow_pct,         adobe_byodCallVisitors_allChannels_yoy_pct,
  adobe_byodStoreLocatorVisitors_allChannels, adobe_byodStoreLocatorVisitors_allChannels_wow, adobe_byodStoreLocatorVisitors_allChannels_ly, adobe_byodStoreLocatorVisitors_allChannels_wow_pct, adobe_byodStoreLocatorVisitors_allChannels_yoy_pct,
  adobe_byodInternalTmoVisitors_allChannels,  adobe_byodInternalTmoVisitors_allChannels_wow,  adobe_byodInternalTmoVisitors_allChannels_ly,  adobe_byodInternalTmoVisitors_allChannels_wow_pct,  adobe_byodInternalTmoVisitors_allChannels_yoy_pct,
  adobe_byodBouncersVisitors_allChannels,     adobe_byodBouncersVisitors_allChannels_wow,     adobe_byodBouncersVisitors_allChannels_ly,     adobe_byodBouncersVisitors_allChannels_wow_pct,     adobe_byodBouncersVisitors_allChannels_yoy_pct,
  adobe_byodOrders_allChannels,               adobe_byodOrders_allChannels_wow,               adobe_byodOrders_allChannels_ly,               adobe_byodOrders_allChannels_wow_pct,               adobe_byodOrders_allChannels_yoy_pct,
  -- PAID SEARCH
  adobe_byodVrChatVisitors_paidSearch,        adobe_byodVrChatVisitors_paidSearch_wow,        adobe_byodVrChatVisitors_paidSearch_ly,        adobe_byodVrChatVisitors_paidSearch_wow_pct,        adobe_byodVrChatVisitors_paidSearch_yoy_pct,
  adobe_byodCallVisitors_paidSearch,          adobe_byodCallVisitors_paidSearch_wow,          adobe_byodCallVisitors_paidSearch_ly,          adobe_byodCallVisitors_paidSearch_wow_pct,          adobe_byodCallVisitors_paidSearch_yoy_pct,
  adobe_byodStoreLocatorVisitors_paidSearch,  adobe_byodStoreLocatorVisitors_paidSearch_wow,  adobe_byodStoreLocatorVisitors_paidSearch_ly,  adobe_byodStoreLocatorVisitors_paidSearch_wow_pct,  adobe_byodStoreLocatorVisitors_paidSearch_yoy_pct,
  adobe_byodInternalTmoVisitors_paidSearch,   adobe_byodInternalTmoVisitors_paidSearch_wow,   adobe_byodInternalTmoVisitors_paidSearch_ly,   adobe_byodInternalTmoVisitors_paidSearch_wow_pct,   adobe_byodInternalTmoVisitors_paidSearch_yoy_pct,
  adobe_byodBouncersVisitors_paidSearch,      adobe_byodBouncersVisitors_paidSearch_wow,      adobe_byodBouncersVisitors_paidSearch_ly,      adobe_byodBouncersVisitors_paidSearch_wow_pct,      adobe_byodBouncersVisitors_paidSearch_yoy_pct,
  adobe_byodOrders_paidSearch,                adobe_byodOrders_paidSearch_wow,                adobe_byodOrders_paidSearch_ly,                adobe_byodOrders_paidSearch_wow_pct,                adobe_byodOrders_paidSearch_yoy_pct,
  -- ORGANIC SEARCH
  adobe_byodVrChatVisitors_organicSearch,     adobe_byodVrChatVisitors_organicSearch_wow,     adobe_byodVrChatVisitors_organicSearch_ly,     adobe_byodVrChatVisitors_organicSearch_wow_pct,     adobe_byodVrChatVisitors_organicSearch_yoy_pct,
  adobe_byodCallVisitors_organicSearch,       adobe_byodCallVisitors_organicSearch_wow,       adobe_byodCallVisitors_organicSearch_ly,       adobe_byodCallVisitors_organicSearch_wow_pct,       adobe_byodCallVisitors_organicSearch_yoy_pct,
  adobe_byodStoreLocatorVisitors_organicSearch,adobe_byodStoreLocatorVisitors_organicSearch_wow,adobe_byodStoreLocatorVisitors_organicSearch_ly,adobe_byodStoreLocatorVisitors_organicSearch_wow_pct,adobe_byodStoreLocatorVisitors_organicSearch_yoy_pct,
  adobe_byodInternalTmoVisitors_organicSearch, adobe_byodInternalTmoVisitors_organicSearch_wow, adobe_byodInternalTmoVisitors_organicSearch_ly, adobe_byodInternalTmoVisitors_organicSearch_wow_pct, adobe_byodInternalTmoVisitors_organicSearch_yoy_pct,
  adobe_byodBouncersVisitors_organicSearch,   adobe_byodBouncersVisitors_organicSearch_wow,   adobe_byodBouncersVisitors_organicSearch_ly,   adobe_byodBouncersVisitors_organicSearch_wow_pct,   adobe_byodBouncersVisitors_organicSearch_yoy_pct,
  adobe_byodOrders_organicSearch,             adobe_byodOrders_organicSearch_wow,             adobe_byodOrders_organicSearch_ly,             adobe_byodOrders_organicSearch_wow_pct,             adobe_byodOrders_organicSearch_yoy_pct,
  -- DIRECT
  adobe_byodVrChatVisitors_direct,            adobe_byodVrChatVisitors_direct_wow,            adobe_byodVrChatVisitors_direct_ly,            adobe_byodVrChatVisitors_direct_wow_pct,            adobe_byodVrChatVisitors_direct_yoy_pct,
  adobe_byodCallVisitors_direct,              adobe_byodCallVisitors_direct_wow,              adobe_byodCallVisitors_direct_ly,              adobe_byodCallVisitors_direct_wow_pct,              adobe_byodCallVisitors_direct_yoy_pct,
  adobe_byodStoreLocatorVisitors_direct,      adobe_byodStoreLocatorVisitors_direct_wow,      adobe_byodStoreLocatorVisitors_direct_ly,      adobe_byodStoreLocatorVisitors_direct_wow_pct,      adobe_byodStoreLocatorVisitors_direct_yoy_pct,
  adobe_byodInternalTmoVisitors_direct,       adobe_byodInternalTmoVisitors_direct_wow,       adobe_byodInternalTmoVisitors_direct_ly,       adobe_byodInternalTmoVisitors_direct_wow_pct,       adobe_byodInternalTmoVisitors_direct_yoy_pct,
  adobe_byodBouncersVisitors_direct,          adobe_byodBouncersVisitors_direct_wow,          adobe_byodBouncersVisitors_direct_ly,          adobe_byodBouncersVisitors_direct_wow_pct,          adobe_byodBouncersVisitors_direct_yoy_pct,
  adobe_byodOrders_direct,                    adobe_byodOrders_direct_wow,                    adobe_byodOrders_direct_ly,                    adobe_byodOrders_direct_wow_pct,                    adobe_byodOrders_direct_yoy_pct,
  -- SOCIAL
  adobe_byodVrChatVisitors_social,            adobe_byodVrChatVisitors_social_wow,            adobe_byodVrChatVisitors_social_ly,            adobe_byodVrChatVisitors_social_wow_pct,            adobe_byodVrChatVisitors_social_yoy_pct,
  adobe_byodCallVisitors_social,              adobe_byodCallVisitors_social_wow,              adobe_byodCallVisitors_social_ly,              adobe_byodCallVisitors_social_wow_pct,              adobe_byodCallVisitors_social_yoy_pct,
  adobe_byodStoreLocatorVisitors_social,      adobe_byodStoreLocatorVisitors_social_wow,      adobe_byodStoreLocatorVisitors_social_ly,      adobe_byodStoreLocatorVisitors_social_wow_pct,      adobe_byodStoreLocatorVisitors_social_yoy_pct,
  adobe_byodInternalTmoVisitors_social,       adobe_byodInternalTmoVisitors_social_wow,       adobe_byodInternalTmoVisitors_social_ly,       adobe_byodInternalTmoVisitors_social_wow_pct,       adobe_byodInternalTmoVisitors_social_yoy_pct,
  adobe_byodBouncersVisitors_social,          adobe_byodBouncersVisitors_social_wow,          adobe_byodBouncersVisitors_social_ly,          adobe_byodBouncersVisitors_social_wow_pct,          adobe_byodBouncersVisitors_social_yoy_pct,
  adobe_byodOrders_social,                    adobe_byodOrders_social_wow,                    adobe_byodOrders_social_ly,                    adobe_byodOrders_social_wow_pct,                    adobe_byodOrders_social_yoy_pct,
  -- PROGRAMMATIC
  adobe_byodVrChatVisitors_programmatic,      adobe_byodVrChatVisitors_programmatic_wow,      adobe_byodVrChatVisitors_programmatic_ly,      adobe_byodVrChatVisitors_programmatic_wow_pct,      adobe_byodVrChatVisitors_programmatic_yoy_pct,
  adobe_byodCallVisitors_programmatic,        adobe_byodCallVisitors_programmatic_wow,        adobe_byodCallVisitors_programmatic_ly,        adobe_byodCallVisitors_programmatic_wow_pct,        adobe_byodCallVisitors_programmatic_yoy_pct,
  adobe_byodStoreLocatorVisitors_programmatic,adobe_byodStoreLocatorVisitors_programmatic_wow,adobe_byodStoreLocatorVisitors_programmatic_ly,adobe_byodStoreLocatorVisitors_programmatic_wow_pct,adobe_byodStoreLocatorVisitors_programmatic_yoy_pct,
  adobe_byodInternalTmoVisitors_programmatic, adobe_byodInternalTmoVisitors_programmatic_wow, adobe_byodInternalTmoVisitors_programmatic_ly, adobe_byodInternalTmoVisitors_programmatic_wow_pct, adobe_byodInternalTmoVisitors_programmatic_yoy_pct,
  adobe_byodBouncersVisitors_programmatic,    adobe_byodBouncersVisitors_programmatic_wow,    adobe_byodBouncersVisitors_programmatic_ly,    adobe_byodBouncersVisitors_programmatic_wow_pct,    adobe_byodBouncersVisitors_programmatic_yoy_pct,
  adobe_byodOrders_programmatic,              adobe_byodOrders_programmatic_wow,              adobe_byodOrders_programmatic_ly,              adobe_byodOrders_programmatic_wow_pct,              adobe_byodOrders_programmatic_yoy_pct,
  -- OTHER
  adobe_byodVrChatVisitors_other,             adobe_byodVrChatVisitors_other_wow,             adobe_byodVrChatVisitors_other_ly,             adobe_byodVrChatVisitors_other_wow_pct,             adobe_byodVrChatVisitors_other_yoy_pct,
  adobe_byodCallVisitors_other,               adobe_byodCallVisitors_other_wow,               adobe_byodCallVisitors_other_ly,               adobe_byodCallVisitors_other_wow_pct,               adobe_byodCallVisitors_other_yoy_pct,
  adobe_byodStoreLocatorVisitors_other,       adobe_byodStoreLocatorVisitors_other_wow,       adobe_byodStoreLocatorVisitors_other_ly,       adobe_byodStoreLocatorVisitors_other_wow_pct,       adobe_byodStoreLocatorVisitors_other_yoy_pct,
  adobe_byodInternalTmoVisitors_other,        adobe_byodInternalTmoVisitors_other_wow,        adobe_byodInternalTmoVisitors_other_ly,        adobe_byodInternalTmoVisitors_other_wow_pct,        adobe_byodInternalTmoVisitors_other_yoy_pct,
  adobe_byodBouncersVisitors_other,           adobe_byodBouncersVisitors_other_wow,           adobe_byodBouncersVisitors_other_ly,           adobe_byodBouncersVisitors_other_wow_pct,           adobe_byodBouncersVisitors_other_yoy_pct,
  adobe_byodOrders_other,                     adobe_byodOrders_other_wow,                     adobe_byodOrders_other_ly,                     adobe_byodOrders_other_wow_pct,                     adobe_byodOrders_other_yoy_pct
FROM with_max_date
;